### ISSUE TITLE
close() called during concurrent operation on the same file object.

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#1016]
I got this error from a toil worker after a workflow restart:

```
ip-172-31-25-21: 2016-06-26 16:54:36,349 WARNING: toil.leader: 4ea158e8-a4bf-42e8-bcbe-2d8cdf1c40b7:    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 319, in main
        job = Job._loadJob(jobWrapper.command, jobStore)
      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 2178, in _loadJob
        return cls._unpickle(userModule, fileHandle)
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 487, in readFileStream
        yield readable
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1088, in downloadStream
        thread.join()
    IOError: close() called during concurrent operation on the same file object.
    Exiting the worker because of a failed jobWrapper on host ip-172-31-17-148
    ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-17-148
    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 51, in run
        self.tryRun( )
      File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 57, in tryRun
        super( ExceptionalThread, self ).run( )
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1067, in writer
        writable.write(self.content)
    IOError: [Errno 32] Broken pipe
    Exception in thread Thread-5:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 51, in run
        self.tryRun( )
      File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 57, in tryRun
        super( ExceptionalThread, self ).run( )
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1077, in writer
        assert False
```

**Comment by hannes-ucsc** [comment]
I think it's the assert at the bottom of the log that's the primary exception here. Toil is trying to load the pickled job from the store and neither the inlined content nor the S3 object exist.  The full log might be helpful, as well as some more information about why the previous workflow run failed.
