### ISSUE TITLE
Mesos driver abort

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#1017]
I attempted to add a new node to a cluster using `cgcloud grow-cluster` but it seems to crash toil:

```
ip-172-31-25-21: 2016-06-27 13:21:28,001 DEBUG: toil.batchSystems.mesos.batchSystem: Received offer 628ad5c0-d39f-4574-b9d4-a6f62bb7cfd4-O5861 with 29135.00 MiB memory, 8.00 core(s) and 138165.00 MiB of disk.
ip-172-31-25-21: 2016-06-27 13:21:28,003 INFO: toil.batchSystems.mesos.batchSystem: Preparing to launch Mesos task 0 using offer 628ad5c0-d39f-4574-b9d4-a6f62bb7cfd4-O5861 ...
ip-172-31-25-21: 2016-06-27 13:21:28,003 DEBUG: toil.batchSystems.mesos.batchSystem: Offer 628ad5c0-d39f-4574-b9d4-a6f62bb7cfd4-O5861 not suitable to run the tasks with requirements _ResourceRequirement(memory=2147483648.0, cores=1.0, disk=2147483648.0). Mesos offered 30550261760.0 memory, 8 cores and 1.4487650304e+11 of disk.
ip-172-31-25-21: 2016-06-27 13:21:28,003 INFO: toil.batchSystems.mesos.batchSystem: Launched Mesos task 0.
Failed to call scheduler's frameworkMessage
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 478, in frameworkMessage
    message = ast.literal_eval(message)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    CPU usage: 12.9, memory usage: 1.0
            ^
SyntaxError: invalid syntax
I0627 13:21:33.074718  9199 sched.cpp:1805] Asked to abort the driver
I0627 13:21:33.074784  9199 sched.cpp:1070] Aborting framework '628ad5c0-d39f-4574-b9d4-a6f62bb7cfd4-0002'
```

**Comment by hannes-ucsc** [comment]
@tetron, could you post the entire log? If not for this one, then maybe in future issues. Gists or pastebins would be useful.

**Comment by hannes-ucsc** [comment]
Never mind. This is a worker with Toil 3.1.x installed on it joining a cluster whose leader is Toil 3.2.x or 3.3.0a1. You can't use grow-cluster after you've manually upgraded Toil on the leader. Upgrade to the latest unstable cgcloud (`pip install --pre cgcloud-core cgcloud-toil`), run `cgcloud create -IT toil-box` for Toil 3.2.1 or `cgcloud create -IT toil-latest-box` for Toil 3.3.0a1.
