### ISSUE TITLE
Cannot index promise if job returns another promise

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#1021]
If I have 4 chained functions:

A -> B -> C -> D

Where A returns `job.AddChildJobFn(B).rv()` and so forth until D returns a tuple ('foo', 'bar'),

```
a = job.wrapJobFn(A)
a.rv(0)
```
will return an error as it attempts to return the index of A, which is a promise, instead of the tuple in D.  @hannes-ucsc knows where in the code this bug originates.

**Comment by hannes-ucsc** [comment]
Reproduction yields the following:

```
hannes-mbpr: 2016-06-30 12:51:33,855 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: C/i/jobp8XllY
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: Reporting file: C/i/jobp8XllY
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	---TOIL WORKER OUTPUT LOG---
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	Traceback (most recent call last):
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	  File "/Users/hannes/workspace/bd2k/toil/src/toil/worker.py", line 338, in main
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	    job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	  File "/Users/hannes/workspace/bd2k/toil/src/toil/job.py", line 2599, in _runner
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	    self._serialiseExistingJob(jobWrapper, jobStore, returnValues)
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	  File "/Users/hannes/workspace/bd2k/toil/src/toil/job.py", line 2524, in _serialiseExistingJob
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	    self._serialiseJobGraph(jobWrapper, jobStore, returnValues, False)
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	  File "/Users/hannes/workspace/bd2k/toil/src/toil/job.py", line 2494, in _serialiseJobGraph
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	    self._setReturnValuesForPromises(returnValues, jobStore)
hannes-mbpr: 2016-06-30 12:51:33,856 WARNING: toil.leader: C/i/jobp8XllY:	  File "/Users/hannes/workspace/bd2k/toil/src/toil/job.py", line 2221, in _setReturnValuesForPromises
hannes-mbpr: 2016-06-30 12:51:33,857 WARNING: toil.leader: C/i/jobp8XllY:	    promisedValue = returnValues if index is None else returnValues[index]
hannes-mbpr: 2016-06-30 12:51:33,857 WARNING: toil.leader: C/i/jobp8XllY:	TypeError: 'Promise' object does not support indexing
hannes-mbpr: 2016-06-30 12:51:33,857 WARNING: toil.leader: C/i/jobp8XllY:	Exiting the worker because of a failed jobWrapper on host hannes-mbpr
hannes-mbpr: 2016-06-30 12:51:33,857 WARNING: toil.leader: C/i/jobp8XllY:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host hannes-mbpr
hannes-mbpr: 2016-06-30 12:51:33,857 WARNING: toil.leader: C/i/jobp8XllY:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job C/i/jobp8XllY to 0
```
