### ISSUE TITLE
PromisedRequirement doesn't work with static DAGs defined in job functions

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#1039]
```
#!/usr/bin/env python2.7
'''
Author : Arjun Arkal Rao
Affiliation : UCSC BME, UCSC Genomics Institute
File : toy_code_for_unfulfilled_promise_error.py
'''
from __future__ import print_function
from toil.job import Job, PromisedRequirement

import argparse


def test_test():
    '''
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('--dummy', dest='dummy', default=None, required=False)
    Job.Runner.addToilOptions(parser)
    params = parser.parse_args()
    
    F1 = Job.wrapJobFn(returner, disk='100M')
    F2 = Job.wrapJobFn(caller, F1.rv(), disk='200M')
    F1.addChild(F2)
    Job.Runner.startToil(F1, params)


def returner(job):
    job.fileStore.logToMaster(str(job.effectiveRequirements(job.fileStore.jobStore.config).disk))
    return 10


def caller(job, x):
    G = job.wrapJobFn(returner, disk=PromisedRequirement(oop, x))
    H = job.wrapJobFn(returner, disk=PromisedRequirement(lambda x: x, G.rv()))
    job.addChild(G)
    G.addChild(H)


def oop(x):
    return x + 1000


if __name__ == '__main__':
    test_test()
```
Gives an unpickling error
```
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,817 INFO: toil.lib.bioio: Logging set at level: INFO
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,817 INFO: toil.lib.bioio: Logging set at level: INFO
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,822 INFO: toil.jobStores.fileJobStore: Jobstore directory is: /tmp/oppo
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,823 INFO: toil.jobStores.abstractJobStore: The workflow ID is: '6bd05e7c-68b1-4480-9d6e-63a3d8620fb1'
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,834 INFO: toil.common: Using the single machine batch system
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,834 WARNING: toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (4).
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,834 WARNING: toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (8589934592).
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,834 INFO: toil.batchSystems.singleMachine: Setting up the thread pool with 40 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 4.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,841 INFO: toil.common: Written the environment for the jobs to the environment file
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,841 INFO: toil.common: Caching all jobs in job store
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,841 INFO: toil.common: 0 jobs downloaded.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,846 INFO: toil.realtimeLogger: Real-time logging disabled
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,846 INFO: toil.leader: (Re)building internal scheduler state
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,847 INFO: toil.leader: Checked batch system has no running jobs and no updated jobs
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,847 INFO: toil.leader: Found 1 jobs to start and 0 jobs with successors to run
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,850 INFO: toil.leader: Starting the main loop
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:54,852 INFO: toil.batchSystems.singleMachine: Executing command: '/Users/arjun/cached_toil/toil/venv/bin/_toil_worker /tmp/oppo I/G/job79W4uy'.
INFO:toil.common:Created the workflow directory at /tmp/toil-6bd05e7c-68b1-4480-9d6e-63a3d8620fb1
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,189 INFO: toil.batchSystems.singleMachine: Executing command: '/Users/arjun/cached_toil/toil/venv/bin/_toil_worker /tmp/oppo s/p/jobYpr2z2'.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,355 INFO: toil.leader: Got message from job at time 07-03-2016 00:49:55: 104857600
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,415 INFO: toil.batchSystems.singleMachine: Executing command: '/Users/arjun/cached_toil/toil/venv/bin/_toil_worker /tmp/oppo 3/L/jobp7fI6l'.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,417 INFO: toil.batchSystems.singleMachine: Executing command: '/Users/arjun/cached_toil/toil/venv/bin/_toil_worker /tmp/oppo o/Y/jobtB78cQ'.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: The jobWrapper seems to have left a log file, indicating failure: o/Y/jobtB78cQ
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: Reporting file: o/Y/jobtB78cQ
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: o/Y/jobtB78cQ:	---TOIL WORKER OUTPUT LOG---
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: o/Y/jobtB78cQ:	WARNING:toil.resource:The localize() method should only be invoked on a worker.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: o/Y/jobtB78cQ:	WARNING:toil.resource:Can't find resource for leader path '/Users/arjun/LUSC_scaling'
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,649 WARNING: toil.leader: o/Y/jobtB78cQ:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/arjun/LUSC_scaling', name='pootest')
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /tmp/oppo
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	Traceback (most recent call last):
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	  File "/Users/arjun/cached_toil/toil/src/toil/worker.py", line 318, in main
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	    job = Job._loadJob(jobWrapper.command, jobStore)
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	  File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 1911, in _loadJob
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	    return cls._unpickle(userModule, fileHandle)
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	  File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 1934, in _unpickle
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	    return unpickler.load()
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	EOFError
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	Exiting the worker because of a failed jobWrapper on host Arjuns-MacBook-Pro.local
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,650 WARNING: toil.leader: o/Y/jobtB78cQ:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host Arjuns-MacBook-Pro.local
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,651 WARNING: toil.leader: o/Y/jobtB78cQ:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job o/Y/jobtB78cQ to 0
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,651 WARNING: toil.leader: Job: o/Y/jobtB78cQ is completely failed
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,858 INFO: toil.leader: Got message from job at time 07-03-2016 00:49:55: 1010
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:55,859 INFO: toil.leader: Got message from job at time 07-03-2016 00:49:55: Added file with ID 's/N/tmpVn48W4.tmp' to the list of files to be globally deleted.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:57,654 INFO: toil.leader: No jobs left to run so exiting.
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:57,655 INFO: toil.leader: Finished the main loop
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:57,655 INFO: toil.leader: Waiting for stats and logging collator process to finish ...
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:57,870 INFO: toil.leader: ... finished collating stats and logs. Took 0.214813947678 seconds
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:57,870 INFO: toil.leader: Waiting for service manager thread to finish ...
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:58,857 INFO: toil.leader: ... finished shutting down the service manager. Took 0.986219882965 seconds
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:58,857 INFO: toil.leader: Finished toil run with 3 failed jobs
Arjuns-MacBook-Pro.local: 2016-07-03 00:49:58,857 INFO: toil.leader: Failed jobs at end of the run: set(['s/p/jobYpr2z2', 'o/Y/jobtB78cQ', 'I/G/job79W4uy'])
Traceback (most recent call last):
  File "/Users/arjun/LUSC_scaling/pootest.py", line 44, in <module>
    test_test()
  File "/Users/arjun/LUSC_scaling/pootest.py", line 24, in test_test
    Job.Runner.startToil(F1, params)
  File "/Users/arjun/cached_toil/toil/src/toil/job.py", line 515, in startToil
    return toil.start(job)
  File "/Users/arjun/cached_toil/toil/src/toil/common.py", line 546, in start
    return self._runMainLoop(job)
  File "/Users/arjun/cached_toil/toil/src/toil/common.py", line 756, in _runMainLoop
    jobCache=self._jobCache)
  File "/Users/arjun/cached_toil/toil/src/toil/leader.py", line 694, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store '/tmp/oppo' contains 3 failed jobs
```

On the plus side, functions can be passed to PromisedRequirement, the second call (function H) fails whether its a lambda or a function.

@jpfeil @hannes-ucsc can you look at this?

*As always pay no attention to the names of my files lol.

**Comment by arkal** [comment]
works if H is a followOn to G (kinda makes sense) but... and i say this in caps... WHAT THE ACTUAL FUCK.... it works if F2 is a followOn to F1 with H still being a child to G.

**Comment by jpfeil** [comment]
This works on my machine. What version of Toil are you using?

**Comment by hannes-ucsc** [comment]
@arkal, I edited your post. No swearing please.

**Comment by arkal** [comment]
haha sorry i was very exasperated.

@jpfeil i'm on 3.3.0a1. you?

**Comment by arkal** [comment]
OK So this is a race condition and I believe it has something to do with a job creating a child to resolve the promises. @jpfeil will look into it.
