### ISSUE TITLE
Harbingerfile deletion race condition

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#1046]
```
l/k/jobIi7VIc:  Traceback (most recent call last):
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/worker.py", line 332, in main
l/k/jobIi7VIc:      job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/job.py", line 2323, in _runner
l/k/jobIi7VIc:      returnValues = self._run(jobWrapper, fileStore)
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/job.py", line 2271, in _run
l/k/jobIi7VIc:      return self.run(fileStore)
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/submodules/cactus/pipeline/cactus_workflow.py", line 900, in run
l/k/jobIi7VIc:      self.cactusSequencesPath = fileStore.readGlobalFile(self.cactusSequencesID)
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/job.py", line 816, in readGlobalFile
l/k/jobIi7VIc:      harbingerFile.waitOnDownload(lockFileHandle)
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/job.py", line 1603, in waitOnDownload
l/k/jobIi7VIc:      pid = self.read()
l/k/jobIi7VIc:    File "/home/alden/progressiveCactus3/python/local/lib/python2.7/site-packages/toil/job.py", line 1616, in read
l/k/jobIi7VIc:      return int(open(self.harbingerFileName).read())
l/k/jobIi7VIc:  IOError: [Errno 2] No such file or directory: '/tmp/toil-269fb642-c572-42a1-8c9f-aa751fa3e5e9/cache-269fb642-c572-42a1-8c9f-aa751fa3e5e9/.di9QL3RtcHo0d3RtVC50bXA=.harbinger'
```

I haven't fully investigated this yet, but it looks like the harbinger file can be deleted by the asyncWrite thread after self.exists() is checked but before self.read() is called in waitOnDownload(). Maybe HarbingerFile.delete() should acquire the cache lock? Also, should line https://github.com/BD2KGenomics/toil/blob/edf86b5e253e9003a441a68773e79ecaded1a599/src/toil/job.py#L1613 be self.delete() instead of harbingerFile.delete()?

**Comment by arkal** [comment]
I'll look into this. As for the second point, yes it is self.delete. Jacob and I found that yesterday and I was going to put it into my next PR.

Thanks for being patient with all this Alden

**Comment by arkal** [comment]
wow lol what a race. Yes, it is possible for the async write threads to delete the file between those 2 events in a very small probability.

**Comment by arkal** [comment]
Wrote in the fix. Good catch @adderan . From next time, could you please tag/assign cache-related bugs to me so they pop up on my unread notifications? I don't parse through the main Toil issues as often as I should
