### ISSUE TITLE
Option --restart produces error when running CWL pipeline

### ISSUE THREAD

**Issue by zichner** [BD2KGenomics/toil#1100]
``` bash
> cwltoil --restart --jobStore file:jobStore ppeline.cwl job.yml
pc: 2016-08-02 10:24:27,230 INFO: toil.lib.bioio: Logging set at level: INFO
pc: 2016-08-02 10:24:44,319 INFO: toil.lib.bioio: Logging set at level: INFO
pc: 2016-08-02 10:24:44,654 INFO: toil.jobStores.fileJobStore: Path to job store directory is '/data/cwl-test/jobStore'.
Traceback (most recent call last):
  File "/data/cwl-test/toil/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/data/cwl-test/toil/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 595, in main
    outobj = toil.start(wf1)
  File "/data/cwl-test/toil/lib/python2.7/site-packages/toil/common.py", line 536, in start
    raise ToilRestartException('A Toil workflow can only be started once. Use '
toil.common.ToilRestartException: A Toil workflow can only be started once. Use Toil.restart() to resume it.
```

Is the restart feature implemented for CWL?

Thanks!

**Comment by chapmanb** [comment]
Apologies, `--restart` is not yet implemented for cwltoil but this is something we're actively working on. You can see the discussion in #1025 For the short term you'll have to remove the previous jobStore directory and re-run from the start.

**Comment by zichner** [comment]
Great to see that you guys are already working on this. And thanks for pointing me to the pull request discussion, I somehow overlooked it.
