### ISSUE TITLE
Missing module concurrent.futures

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil#1104]
I am attempting to run toil-bwa and toil-cgl, versions:
```
bd2k-python-lib (1.14a1.dev33)
boto (2.42.0)
dill (0.2.5)
PyYAML (3.11)
toil (3.5.0a1.dev229)
toil-scripts (2.1.0a1.dev478)
```
Test runs with either toil-cgl or toil-bwa fail with 
```
Traceback (most recent call last):
  File "/home/ubuntu/venvs/bwa/bin/toil-rnaseq", line 9, in <module>
    load_entry_point('toil-scripts==2.1.0a1.dev478', 'console_scripts', 'toil-rnaseq')()
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil_scripts/rnaseq_cgl/rnaseq_cgl_pipeline.py", line 506, in main
    Job.Runner.startToil(Job.wrapJobFn(map_job, download_sample, samples, config), args)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/job.py", line 542, in startToil
    return toil.start(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/common.py", line 788, in _runMainLoop
    from toil.leader import mainLoop
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/leader.py", line 34, in <module>
    from toil.jobStores.aws.jobStore import AWSJobStore
  File "/home/ubuntu/venvs/bwa/local/lib/python2.7/site-packages/toil/jobStores/aws/jobStore.py", line 44, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
```
see also [this issue](https://github.com/BD2KGenomics/toil-scripts/issues/400) for the full log

**Comment by fnothaft** [comment]
Hi @Jeltje! Which release of toil are you running? IIRC, this issue was fixed in https://github.com/BD2KGenomics/toil/issues/1005, which is in Toil 3.2.1 and later.

**Comment by hannes-ucsc** [comment]
@Jeltje provided the version numbers in her OP. Is this still an issue?

**Comment by hannes-ucsc** [comment]
Closing. Please reopen if still an issue.
