### ISSUE TITLE
cgcloud register-key fails with us-east-1 and us-east-1a

### ISSUE THREAD

**Issue by golharam** [BD2KGenomics/toil#1109]
In the docs for cloud installation, the docs say to run:
```
cgcloud register-key ~/.ssh/id_rsa.pub
```
When I do this, I get the error:
```
INFO: Using zone 'us-east-1a' and namespace '/ryan.golhar/'
Traceback (most recent call last):
  File "/home/golharr/workspace/BD2KGenomics/venv/bin/cgcloud", line 11, in <module>
    sys.exit(main())
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/core/cli.py", line 49, in main
    app.run( args )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/lib/util.py", line 308, in run
    command.run( options )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/core/commands.py", line 85, in run
    return self.run_in_ctx( options, ctx )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/core/commands.py", line 637, in run_in_ctx
    force=options.force )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/lib/context.py", line 522, in register_ssh_pubkey
    self.upload_ssh_pubkey( ssh_pubkey, fingerprint )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/cgcloud/lib/context.py", line 479, in upload_ssh_pubkey
    location=self.region )
  File "/home/golharr/workspace/BD2KGenomics/venv/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidLocationConstraint</Code><Message>The specified location-constraint is not valid</Message><LocationConstraint>us-east-1</LocationConstraint><RequestId>544509A0A5640F85</RequestId><HostId>F6lVWhi7+Yy4fKuJej9xQEO8Q/q5eisgMawRebE8C1q52ckyll2AThzm7aMv3UA+DtN7Sn/+BjU=</HostId></Error>
```

My  CGCLOUD_ZONE=us-east-1a, so I'm not sure what to do.   AWS docs says I should use us-east-1, but when I set that to CGCLOUD_ZONE, Toil can't determine the region.

**Comment by hannes-ucsc** [comment]
This should be filed against CGCloud, not Toil. Anyhow, this is a duplicate o of https://github.com/BD2KGenomics/cgcloud/issues/215 which has been fixed but the fix has not been released yet. On that ticket, there is mention of a work around that could tie you over until the next release is cut. The workaround is to temporarily change `CGCLOUD_ZONE` to any other region, like us-west-2a, run `cgcloud register-key`, then change `CGCLOUD_ZONE` back and run `cgcloud register-key` again.
