### ISSUE TITLE
cwltoil non-clean job failures

### ISSUE THREAD

**Issue by chapmanb** [BD2KGenomics/toil#1122]
While debugging #1107 and responding to comments from @hannes-ucsc I realized the underlying issues with CWL restarts might be that cwltoil does not exit cleanly. Here is a small example with the test directory, forcing revtool to fail by messing up the `rev` command:

```
cd src/toil/test/cwl
sed -i 's/baseCommand: rev/baseCommand: rev-fail/' revtool.cwl
cwltoil --no-container revsort.cwl revsort-job.json
```

This fails with an assertion error during consistency checks at the end of `innerLoop` (https://github.com/BD2KGenomics/toil/blob/92f64a5d94bd16514979bc5c784f72863f2ddf5d/src/toil/leader.py#L728) which I suspect is not the right outcome. That function is pretty complex and deeply nested so it's not clear to me how to start debugging this. I hope that there's something we can include from the CWL side to create cleaner job exits here.

Can anyone offer any advice/directions?

Here is the full traceback from the run:

```
kunkel 2016-08-26 11:18:31,313 MainThread WARNING toil.leader: The jobWrapper seems to have left a log file, indicating failure: B/U/jobWBMw6I
kunkel 2016-08-26 11:18:31,313 MainThread WARNING toil.leader: Reporting file: B/U/jobWBMw6I
kunkel 2016-08-26 11:18:31,313 MainThread WARNING toil.leader: B/U/jobWBMw6I:   ---TOIL WORKER OUTPUT LOG---
kunkel 2016-08-26 11:18:31,313 MainThread WARNING toil.leader: B/U/jobWBMw6I:   INFO:rdflib:RDFLib Version: 4.2.1
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   INFO:toil.fileStore:CACHE: Read file with ID 'a/2/tmp2RYy7z.tmp' from the cache.
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   [job revtool.cwl] /tmp/user/1001/tmpZ7hLZ6$ rev-fail \
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:       /tmp/user/1001/tmppbMf7F/stg5c0b758e-c348-411b-b260-877b9491c6da/whale.txt > /tmp/user/1001/tmpZ7hLZ6/output.txt
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   INFO:cwltool:[job revtool.cwl] /tmp/user/1001/tmpZ7hLZ6$ rev-fail \
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:       /tmp/user/1001/tmppbMf7F/stg5c0b758e-c348-411b-b260-877b9491c6da/whale.txt > /tmp/user/1001/tmpZ7hLZ6/output.txt
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   'rev-fail' not found
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   ERROR:cwltool:'rev-fail' not found
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   [job revtool.cwl] completed permanentFail
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   WARNING:cwltool:[job revtool.cwl] completed permanentFail
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   Final process status is permanentFail
kunkel 2016-08-26 11:18:31,314 MainThread WARNING toil.leader: B/U/jobWBMw6I:   WARNING:cwltool:Final process status is permanentFail
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:   INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'a/2/tmp2RYy7z.tmp'.
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:   Traceback (most recent call last):
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:     File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/worker.py", line 331, in main
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:       job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:     File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/job.py", line 1085, in _runner
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:       returnValues = self._run(jobWrapper, fileStore)
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:     File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/job.py", line 1033, in _run
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:       return self.run(fileStore)
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:     File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 256, in run
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:       **opts)
kunkel 2016-08-26 11:18:31,315 MainThread WARNING toil.leader: B/U/jobWBMw6I:     File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/main.py", line 218, in single_job_executor
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:       raise WorkflowException(u"Process status is %s" % (final_status))
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:   WorkflowException: Process status is ['permanentFail']
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:   Exiting the worker because of a failed jobWrapper on host kunkel
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:   ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host kunkel
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:   WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job B/U/jobWBMw6I to 0
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: B/U/jobWBMw6I:   WARNING:toil.jobWrapper:We have increased the default memory of the failed job to 2147483648 bytes
kunkel 2016-08-26 11:18:31,316 MainThread WARNING toil.leader: Job: B/U/jobWBMw6I is completely failed
kunkel 2016-08-26 11:18:31,316 MainThread INFO toil.leader: No jobs left to run so exiting.
kunkel 2016-08-26 11:18:31,316 MainThread INFO toil.leader: Finished the main loop
kunkel 2016-08-26 11:18:31,316 MainThread INFO toil.leader: Waiting for stats and logging collator thread to finish ...
kunkel 2016-08-26 11:18:31,638 MainThread INFO toil.leader: ... finished collating stats and logs. Took 0.321724891663 seconds
kunkel 2016-08-26 11:18:31,639 MainThread INFO toil.leader: Waiting for service manager thread to finish ...
kunkel 2016-08-26 11:18:32,129 MainThread INFO toil.leader: ... finished shutting down the service manager. Took 0.490026950836 seconds
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.5.0a1', 'console_scripts', 'cwltoil')()
  File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 665, in main
    outobj = toil.start(wf1)
  File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/common.py", line 580, in start
    return self._runMainLoop(job)
  File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/common.py", line 794, in _runMainLoop
    jobCache=self._jobCache)
  File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/leader.py", line 692, in mainLoop
    innerLoop(jobStore, config, batchSystem, toilState, jobBatcher, serviceManager, statsAndLogging)
  File "/home/chapmanb/install/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/leader.py", line 970, in innerLoop
    assert toilState.successorCounts == {}
AssertionError
```

**Comment by hannes-ucsc** [comment]
@chapmanb, can you add a log statement that prints `repr(toilState.successorCounts)`?

@benedictpaten wrote the assertion, maybe he can weigh in.

**Comment by chapmanb** [comment]
Hannes -- thanks for the suggestions. I did dig into this but unfortunately it's not very useful since successorCounts is only a pointer to an internal toil directory:
```
{'t/z/jobAriLfp': 1}
```
Benedict -- if you have any tips or directions to try I'd be happy to dig into it further.

**Comment by hannes-ucsc** [comment]
@cket, would you be able to take a look at this? This is blocking Brad. I would like prioritize this highest, even before autoscaling.

**Comment by cket** [comment]
@hannes-ucsc  @benedictpaten @chapmanb I was able to reproduce this with a simpler script. 

The pipeline has a job is the child of 2 different parents. One parent finishes so the job is added to that parent's successorCount but the job can't be actually be issued until its other parent finishes. However, the other parent fails & the pipeline ends. That job is still listed as a successor of its first parent job, resulting in this failure. I propose simply modifying the consistency checks to allow this case. 

This script mimics the pattern that is causing this failure in cwltoil:
```
#!/usr/bin/env python
# 'child' is the successor of 'root'. 'Grand_child' is a successor of both 
# 'child' and 'root'. Failure in child causes toil state to fail its 
# consistency check.
import argparse
import os
from toil.common import Toil
from toil.job import Job, JobFunctionWrappingJob


def root(job):
    job2 = JobFunctionWrappingJob(child)
    job3 = JobFunctionWrappingJob(grand_child)

    job.addChild(job3)
    job.addChild(job2)
    job2.addChild(job3)

def child(job):
    raise RuntimeError('child failure')

def grand_child(job):
    pass

def main():
    parser = argparse.ArgumentParser()
    Job.Runner.addToilOptions(parser)
    options = parser.parse_args()
    i = Job.wrapJobFn(root)
    with Toil(options) as toil:
        toil.start(i)

if __name__ == '__main__':
    main()
```

**Comment by chapmanb** [comment]
Thanks so much for the diagnosis, that's exactly right. We have an initial run with a failed job due to external reasons (in this case, a missing program on the command line) and then re-run the same pipeline and want to resume where we left off, reusing the working steps and starting with a run of the failed step. Supporting this type of re-use in general would be very helpful, as we often have long running pipelines that fail due to code/configuration errors and need to get restarted like this. Thanks again.

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/toil/pull/1264/commits/86830a44f9af7d55f543fb5f9733c035200f0d9b resolves this but carries the wrong ticket reference in its title.
