### ISSUE TITLE
Toil --restart option unable to hotdeploy on Azure

### ISSUE THREAD

**Issue by cmarkello** [BD2KGenomics/toil#1207]
```
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   ---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   Next available file descriptor: 10
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:toil.worker:Next available file descriptor: 10
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:urllib3.connectionpool:Setting read timeout to 65
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:urllib3.connectionpool:"GET /acmarkellotoilvgjobstore11xxjobitems(PartitionKey='default',RowKey='fc48619f_e141_4211_8ab9_3004f95b16df')?$select= HTTP/1.1" 200 None
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   Parsed jobWrapper
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:toil.worker:Parsed jobWrapper
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   Got a command to run: _toil b5feca2d_3cbf_46a6_81cc_43d5f3a43cb6 /home/cmarkello/toilvenv/local/lib/python2.7/site-packages toil_vg.vg_evaluation_pipeline
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:toil.worker:Got a command to run: _toil b5feca2d_3cbf_46a6_81cc_43d5f3a43cb6 /home/cmarkello/toilvenv/local/lib/python2.7/site-packages toil_vg.vg_evaluation_pipeline
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:toil.job:Loading user module ModuleDescriptor(dirPath='/home/cmarkello/toilvenv/local/lib/python2.7/site-packages', name='toil_vg.vg_evaluation_pipeline').
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   WARNING:toil.resource:Can't find resource for leader path '/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil_vg'
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/cmarkello/toilvenv/local/lib/python2.7/site-packages', name='toil_vg.vg_evaluation_pipeline')
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   ERROR:toil.job:Failed to import user module ModuleDescriptor(dirPath='/home/cmarkello/toilvenv/local/lib/python2.7/site-packages', name='toil_vg.vg_evaluation_pipeline') from sys.path=['/home/cmarkello/toilvenv/bin', '/home/cmarkello/toilvenv/lib/python2.7', '/home/cmarkello/toilvenv/lib/python2.7/plat-x86_64-linux-gnu', '/home/cmarkello/toilvenv/lib/python2.7/lib-tk', '/home/cmarkello/toilvenv/lib/python2.7/lib-old', '/home/cmarkello/toilvenv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/cmarkello/toilvenv/local/lib/python2.7/site-packages', '/home/cmarkello/toil/src', '/home/cmarkello/toilvenv/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages/mesos.interface-0.22.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/mesos-0.22.0-py2.7-linux-x86_64.egg', '/home/cmarkello/toil-scripts/src', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/site-packages', '/usr/lib/python2.7/dist-packages'] 
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   Traceback (most recent call last):
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:     File "/home/cmarkello/toil/src/toil/worker.py", line 316, in main
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:       job = Job._loadJob(jobWrapper.command, jobStore)
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:     File "/home/cmarkello/toil/src/toil/job.py", line 666, in _loadJob
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:       userModule = cls._loadUserModule(userModule)
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:     File "/home/cmarkello/toil/src/toil/job.py", line 640, in _loadUserModuleWARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:       return importlib.import_module(userModule.name)
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:     File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:       __import__(name)
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   ImportError: No module named toil_vg.vg_evaluation_pipeline
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   Exiting the worker because of a failed jobWrapper on host c1agent3
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host c1agent3
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:urllib3.connectionpool:Setting read timeout to 65
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   DEBUG:urllib3.connectionpool:"GET /acmarkellotoilvgjobstore11xxjobitems(PartitionKey='default',RowKey='fc48619f_e141_4211_8ab9_3004f95b16df')?$select= HTTP/1.1" 200 None
WARNING:toil.leader:fc48619f_e141_4211_8ab9_3004f95b16df:   WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job fc48619f_e141_4211_8ab9_3004f95b16df to 0

```

**Comment by cket** [comment]
What version of toil is this?

**Comment by cmarkello** [comment]
3.5.0a1.dev241

**Comment by hannes-ucsc** [comment]
That build doesn't include the fix for #1152 of which this issue may be a duplicate of. Can you try again with .dev151 and reopen if it still occurs? BTW, *if* you are using development builds, you should try to keep up-to-date. I don't see a benefit in using a stale development build.

**Comment by cmarkello** [comment]
@hannes-ucsc @cket So when using toil version `toil[azure,mesos]==3.2.0a2.dev151`. It now is not able to find the azure jobstore. There was a hotfix for this issue in the specific version of toil I was using (`toil-3.5.0a1.dev241`) which was why I was developing under that version of toil.
Below is the output when running `--restart` with toil version 3.2.0a2.dev151. Btw, the jobstore does exist.

```
(toilvenv) cmarkello@c1master1:~$ toil-vg --batchSystem mesos --mesosMaster=10.0.0.5:5050 --realTimeLogging --logError --logDebug --edge_max 5 --kmer_size 16 --num_fastq_chunks 16 --call_chunk_size 100000 --overwrite --index_mode gcsa-mem --include_primary --index_cores 32 --alignment_cores 32 --calling_cores 32 'azure:hgvm:cmarkello-toilvg-jobstore28' '/home/cmarkello/test_vg_input/22_GRCh38_chop_100.vg' '/home/cmarkello/test_vg_input/HG00419_chr22.highcov.bam.fq' 'HG00419' '/home/cmarkello/test_vg_output' 'azure:hgvm:cmarkello-toilvg-input' 'azure:hgvm:cmarkello-toilvg-output' --path_name chr22 --path_size 50818468 --restart 2>&1 | tee -a toil_vg_testrun_chr22_log9_restart.txt
INFO:toil.lib.bioio:Logging set at level: DEBUG
DEBUG:toil.jobStores.azureJobStore:Creating job store with name prefix 'acmarkellotoilvgjobstore28'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): hgvm.table.core.windows.net
DEBUG:requests.packages.urllib3.connectionpool:"POST /Tables HTTP/1.1" 409 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /toilRegistry(PartitionKey='default',RowKey='acmarkellotoilvgjobstore28')?$select= HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/home/cmarkello/toilvenv/bin/toil-vg", line 11, in <module>
    sys.exit(main())
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil_vg/vg_evaluation_pipeline.py", line 739, in main
    with Toil(options) as toil:
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 471, in __enter__
    config=None if self.config.restart else self.config)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 589, in loadOrCreateJobStore
    return AzureJobStore(account, namePrefix, config=config)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/jobStores/azureJobStore.py", line 103, in __init__
    self._checkJobStoreCreation(config is not None, exists, accountName + ":" + self.namePrefix)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 232, in _checkJobStoreCreation
    "is nothing to restart." % jobStoreString)
toil.jobStores.abstractJobStore.JobStoreCreationException: The job store 'hgvm:acmarkellotoilvgjobstore28' does not exist, so there is nothing to restart.
```

**Comment by cket** [comment]
@cmarkello I believe @hannes-ucsc meant dev251, which has the fix, not 151, which doesn't. You can see all the dev release builds here http://jenkins.cgcloud.info/job/toil-branches/branch/master/ and they each will point you to the specific commit they are building for more info. Generally if something isn't working you can try updating your dev version to more recent versions to see if there is a fix on master.

**Comment by cmarkello** [comment]
@cket Just attempted '--restart' again but with toil version `3.5.0a1.dev251` instead. I'm getting a `'Config' object has no attribute 'preemptableCompensation'` error. I'm trying to rerun a toil script that was run with toil version `3.5.0a1.dev241`. Could that cause the issue? If so, would I need to rerun the pipeline again from scratch?

```
(toilvenv) cmarkello@c1master1:~$ toil-vg --batchSystem mesos --mesosMaster=10.0.0.5:5050 --realTimeLogging --logError --logDebug --edge_max 5 --kmer_size 16 --num_fastq_chunks 16 --call_chunk_size 100000 --overwrite --index_mode gcsa-mem --include_primary --index_cores 32 --alignment_cores 32 --calling_cores 32 'azure:hgvm:cmarkello-toilvg-jobstore33' '/home/cmarkello/test_vg_input/22_GRCh38_chop_100.vg' '/home/cmarkello/test_vg_input/HG00419_chr22.highcov.bam.fq' 'HG00419' '/home/cmarkello/test_vg_output' 'azure:hgvm:cmarkello-toilvg-input' 'azure:hgvm:cmarkello-toilvg-output' --path_name chr22 --path_size 50818468 --restart 2>&1 | tee -a toil_vg_testrun_chr22_log11_restart.txt
INFO:toil.lib.bioio:Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): hgvm.table.core.windows.net
DEBUG:requests.packages.urllib3.connectionpool:"GET /Tables('acmarkellotoilvgjobstore33xxstatsfileids') HTTP/1.1" 200 None
DEBUG:toil.jobStores.azureJobStore:Using existing job store at 'hgvm:cmarkello-toilvg-jobstore33'
DEBUG:requests.packages.urllib3.connectionpool:"GET /Tables('acmarkellotoilvgjobstore33xxjobitems') HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /Tables('acmarkellotoilvgjobstore33xxjobfileids') HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): hgvm.blob.core.windows.net
DEBUG:requests.packages.urllib3.connectionpool:"GET /acmarkellotoilvgjobstore33xxfiles?restype=container HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /acmarkellotoilvgjobstore33xxstatsfiles?restype=container HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /Tables('acmarkellotoilvgjobstore33xxstatsfileids') HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /acmarkellotoilvgjobstore33xxfiles/a77581f6_ad82_5142_acb7_5a6b01eab3fb?comp=metadata HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acmarkellotoilvgjobstore33xxfiles/a77581f6_ad82_5142_acb7_5a6b01eab3fb HTTP/1.1" 200 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /acmarkellotoilvgjobstore33xxfiles/a77581f6_ad82_5142_acb7_5a6b01eab3fb HTTP/1.1" 206 1127
Traceback (most recent call last):
  File "/home/cmarkello/toilvenv/bin/toil-vg", line 11, in <module>
    sys.exit(main())
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil_vg/vg_evaluation_pipeline.py", line 739, in main
    with Toil(options) as toil:
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 532, in __enter__
    config.setOptions(self.options)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 203, in setOptions
    require(0.0 <= self.preemptableCompensation <= 1.0,
AttributeError: 'Config' object has no attribute 'preemptableCompensation'
```

**Comment by cket** [comment]
Yes, it seems like that attribute was added recently so it wouldn't have been in the config generated by the older version you were using before. Rerunning the pipeline will fix that issue

**Comment by cmarkello** [comment]
@cket Also getting the following error. It looks like I didn't pass the correct parameters for the `__new__()` constructor for the toil job class. It's when I'm making a `toil.start(root_job)` command where `root_job = Job.wrapJobFn(run_upload, options, uploadList, cores=2, memory="5G", disk="2G")` and `run_upload` is a job function.
```

DEBUG:toil.common:... finished shutting down the batch system in 0.000468015670776 seconds.
Traceback (most recent call last):
  File "/home/cmarkello/toilvenv/bin/toil-vg", line 11, in <module>
    sys.exit(main())
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil_vg/vg_evaluation_pipeline.py", line 751, in main 
    outputFileIDList = toil.start(root_job)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 597, in start
    return self._runMainLoop(job)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/common.py", line 844, in _runMainLoop
    jobCache=self._jobCache)
  File "/home/cmarkello/toilvenv/local/lib/python2.7/site-packages/toil/leader.py", line 753, in mainLoop
    raise FailedJobsException(config.jobStore, toilState.totalFailedJobs, jobStore)
toil.leader.FailedJobsException: The job store 'azure:hgvm:cmarkello-toilvg-jobstore34' contains 1 failed jobs: 1ca41fd1_f538_4560_a67f_7ef5c67004cf
=========> Failed job 1ca41fd1_f538_4560_a67f_7ef5c67004cf
---TOIL WORKER OUTPUT LOG---
Next available file descriptor: 10
DEBUG:toil.worker:Next available file descriptor: 10
DEBUG:urllib3.connectionpool:Setting read timeout to 65
DEBUG:urllib3.connectionpool:"GET /acmarkellotoilvgjobstore34xxjobitems(PartitionKey='default',RowKey='1ca41fd1_f538_4560_a67f_7ef5c67004cf')?$select= HTTP/1.1" 200 None
Parsed jobWrapper
DEBUG:toil.worker:Parsed jobWrapper
Got a command to run: _toil f08900a7_317d_47bb_8c77_29d8ad7493a3 /home/cmarkello/toilvenv/local/lib/python2.7/site-packages toil_vg.vg_evaluation_pipeline True
DEBUG:toil.worker:Got a command to run: _toil f08900a7_317d_47bb_8c77_29d8ad7493a3 /home/cmarkello/toilvenv/local/lib/python2.7/site-packages toil_vg.vg_evaluation_pipeline True
Traceback (most recent call last):
  File "/home/cmarkello/toil/src/toil/worker.py", line 316, in main 
    job = Job._loadJob(jobWrapper.command, jobStore)
  File "/home/cmarkello/toil/src/toil/job.py", line 664, in _loadJob
    userModule = ModuleDescriptor(*(commandTokens[2:]))
TypeError: __new__() takes exactly 3 arguments (4 given)
Exiting the worker because of a failed jobWrapper on host c1agent2
ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host c1agent2
DEBUG:urllib3.connectionpool:Setting read timeout to 65
DEBUG:urllib3.connectionpool:"GET /acmarkellotoilvgjobstore34xxjobitems(PartitionKey='default',RowKey='1ca41fd1_f538_4560_a67f_7ef5c67004cf')?$select= HTTP/1.1" 200 None
WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 1ca41fd1_f538_4560_a67f_7ef5c67004cf to 0 
<=========
```

**Comment by cket** [comment]
@cmarkello something weird is going on - I checked out a local copy of the commit for dev251 (5ec9a2cd1fb081bd59a93a7aa0023d19cab6750b) and the line numbers aren't matching up with your traceback. _loadJob starts at line 741 so the line
```File "/home/cmarkello/toil/src/toil/job.py", line 664, in _loadJob```
doesn't make sense to me.

Did you upgrade toil versions on all the workers? If you didn't it would explain both the failure and line mismatch

**Comment by cmarkello** [comment]
@cket No, I didn't upgrade toil on the other workers. I'd forgotten about that. That's likely the issue, thanks.

**Comment by cmarkello** [comment]
@hannes-ucsc @cket I've now attempted to update my toil script and restart a toil run and it appears to not have hotdeployed the script to the worker nodes of my toil cluster. I am using toil version 3.5.0a1.dev251.

**Comment by hannes-ucsc** [comment]
Could you come by my office and demonstrate?

**Comment by hannes-ucsc** [comment]
This is legit. I'm a dummy. PR coming up.
