### ISSUE TITLE
Sporadic 403 when reading from job store

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1221]
I'm tempted to chalk this one up as an IAM outage. For the record:

http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/265/testReport/

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 106, in statsAndLoggingAggregator
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 576, in readStatsAndLogging
    for info in self._readStatsAndLogging(callback, self.statsFileOwnerID):
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 594, in _readStatsAndLogging
    self.filesDomain.name, str(ownerId))))
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/queryresultset.py", line 81, in __iter__
    consistent_read=self.consistent_read)
  File "/usr/local/lib/python2.7/dist-packages/boto/sdb/connection.py", line 618, in select
    raise e
SDBResponseError: SDBResponseError: 403 Forbidden
Query: select * from `toil-it-0dd545e7-f34e-4746-acb6-6017f1726f7a--files` where ownerID='bfcf5286-4bc7-41ef-a85d-9ab415b69d53'
<?xml version="1.0"?>
<Response><Errors><Error><Code>InvalidClientTokenId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message></Error></Errors><RequestID>90399e2a-0989-6fbc-8181-51150c97519b</RequestID></Response>
```

┆Issue Number: TOIL-131

**Comment by DailyDreaming** [comment]
Outdated.
