### ISSUE TITLE
toil/resource.py throws uninformative assert

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1232]
It'd be useful to know what the `dirPath` is, at least:

```
Traceback (most recent call last):
  File "/root/toil-scripts/.env/bin/toil-bwa", line 11, in <module>
    load_entry_point('toil-scripts==2.1.0a1', 'console_scripts', 'toil-bwa')()
  File "build/bdist.linux-x86_64/egg/toil_scripts/bwa_alignment/bwa_alignment.py", line 292, in main
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 390, in wrapJobFn
    return JobFunctionWrappingJob(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1246, in __init__
    self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 381, in forModule
    assert os.path.isdir(dirPath)
AssertionError
```

**Comment by hannes-ucsc** [comment]
But the assert firing is a bug in own right, correct? What triggered this?

**Comment by fnothaft** [comment]
No, I think the assert fired because I installed some `.egg-links` into a Virtualenv, which we officially don't support. That being said, I can't confirm that without fixing this first.

**Comment by hannes-ucsc** [comment]
If an unsuspecting user can mess this up, maybe this is a case for `require()`.

**Comment by fnothaft** [comment]
Yeah, it should definitely be a `require()`, and with an error message that relates the bad path.
