### ISSUE TITLE
Usage: Is there an example of using toil with slurm?

### ISSUE THREAD

**Issue by cswarth** [BD2KGenomics/toil#1234]
Sorry to file this as an issue - is there a better forum for usage questions? 

Can any one help me configure Toil for our local slurm-managed cluster?   Clearly I need something different than `file:JobStore ` that I used for the `onemachine` batch manager.

```
$ echo $TOIL_SLURM_ARGS
TOIL_SLURM_ARGS=-t 1:00:00 -p matsen_e

$ python pipeline.py  --batchSystem slurm --disableCaching file:JobStore sample_dedup.fa 
stoat 2016-10-21 16:29:23,642 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
stoat 2016-10-21 16:29:23,642 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
stoat 2016-10-21 16:29:23,650 MainThread INFO toil.jobStores.fileJobStore: Path to job store directory is '/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/cft/toil/JobStore'.
stoat 2016-10-21 16:29:23,651 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '3c19b83d-ba03-4c90-9984-1477db591409'
stoat 2016-10-21 16:29:23,667 MainThread INFO toil.common: Using the slurm batch system
Traceback (most recent call last):
  File "pipeline.py", line 186, in <module>
    main()
  File "pipeline.py", line 182, in main
    Job.wrapJobFn(start_batch, datafiles, inputs), args)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/toil/src/toil/job.py", line 640, in startToil
    return toil.start(job)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/toil/src/toil/common.py", line 578, in start
    userScript=rootJob.getUserScript())
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/toil/src/toil/common.py", line 764, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/toil/src/toil/batchSystems/slurm.py", line 265, in __init__
    self.slurmResultsFileHandle = open(self.slurmResultsFile, 'w')
IOError: [Errno 2] No such file or directory: 'file:/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/cft/toil/JobStore/results.txt'
```

**Comment by cswarth** [comment]
Got it,

```
$ python HelloWorld.py --batchSystem slurm --disableCaching --logDebug ./jobStore
```
