### ISSUE TITLE
Toil 3.3.4 not compatible with current CWL specs.

### ISSUE THREAD

**Issue by Chris7** [BD2KGenomics/toil#1322]
Thanks for updating toil to 3.3.4. I am trying to run the example job here from http://www.commonwl.org/v1.0/UserGuide.html (hello world echo) and getting the following error:

```
(toil) chris@chris-ThinkPad-T450:~$ cwltoil example.cwl example.yml
chris-ThinkPad-T450: 2016-11-17 11:34:36,936 INFO: toil.lib.bioio: Logging set at level: INFO
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/toil/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/home/chris/.virtualenvs/toil/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 550, in main
    True)
  File "/home/chris/.virtualenvs/toil/local/lib/python2.7/site-packages/cwltool/main.py", line 334, in load_tool
    workflowobj = update.update(workflowobj, document_loader, fileuri)
  File "/home/chris/.virtualenvs/toil/local/lib/python2.7/site-packages/cwltool/update.py", line 327, in update
    raise Exception(u"Unrecognized version %s" % version)
Exception: Unrecognized version v1.0
```

It looks like the pinned version (that isn't actually on the release page for cwl tool) is out of date and has the following supported CWL versions:

```
     updates = {
         "https://w3id.org/cwl/cwl#draft-2": draft2toDraft3dev1,
         "https://w3id.org/cwl/cwl#draft-3.dev1": draftDraft3dev1toDev2,
         "https://w3id.org/cwl/cwl#draft-3.dev2": draftDraft3dev2toDev3,
         "https://w3id.org/cwl/cwl#draft-3.dev3": draftDraft3dev3toDev4,
         "https://w3id.org/cwl/cwl#draft-3.dev4": draftDraft3dev4toDev5,
         "https://w3id.org/cwl/cwl#draft-3.dev5": draftDraft3dev5toFinal,
         "https://w3id.org/cwl/cwl#draft-3": None
     }
```

Is this by design that 3.3.x does not support v1?

**Comment by hannes-ucsc** [comment]
> Is this by design that 3.3.x does not support v1?

Sort of. I don't think 1.0 was out by the time 3.3.0 was released. We only do bug fixes on the 3.3.x channel. When 3.5.0 is released it will support the latest stable release of CWL.
