### ISSUE TITLE
setuptools 8.0.0 or later is now required for PEP 440 version support

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1323]
python 2.7.9
setuptools 5.5.1
```
Traceback (most recent call last):
  File "version_template.py", line 137, in <module>
    _main()
  File "version_template.py", line 133, in _main
    sys.stdout.write(expand_(*sys.argv[1:]))
  File "version_template.py", line 128, in expand_
    return resolve(name)
  File "version_template.py", line 122, in resolve
    v = v()
  File "version_template.py", line 61, in distVersion
    if build_number is not None and parse_version(baseVersion).is_prerelease:
AttributeError: 'tuple' object has no attribute 'is_prerelease'
```

**Comment by hannes-ucsc** [comment]
I don't want to drop the requirement but I'll make it more explicit. Thank you for catching this.

**Comment by mr-c** [comment]
I agree that is is a reasonable requirement. On the upside, the CWL v1.0
conformance tests are running again on https://ci.commonwl.org

**Comment by mr-c** [comment]
Thanks!
