### ISSUE TITLE
Cannot import adjustFiles with Toil 3.3.4 and cwltool 1.0 (11/28)

### ISSUE THREAD

**Issue by MatthewRalston** [BD2KGenomics/toil#1359]
Hello,
I cannot use the cwltoil tool to run cwl workflows as toil workflows. It seems to be an issue related to a name change surrounding a method 'adjustFiles' 

Fresh install of toil 3.3.4
```bash
>toil --version
3.3.4
>cwltool --version
INFO:rdflib:RDFLib Version: 4.2.1
/Users/Matthew/.pyenv/versions/matts_2.7.8/bin/cwltool 1.0.20161128202906
>cwltoil --debug hello_world.yml hello_world-job.yml
INFO:rdflib:RDFLib Version: 4.2.1
Traceback (most recent call last):
  File "/Users/Matthew/.pyenv/versions/matts_2.7.8/bin/cwltoil", line 7, in <module>
    from toil.cwl.cwltoil import main
  File "/Users/Matthew/.pyenv/versions/matts_2.7.8/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 28, in <module>
    from cwltool.process import adjustFiles, shortname, adjustFilesWithSecondary, fillInDefaults
ImportError: cannot import name adjustFiles
>ls /Users/Matthew/.pyenv/versions/matts_2.7.8/lib/python2.7/site-packages/cwltool
total 1000
-rw-r--r--  1 Matthew  staff    43B Dec  1 17:20 __init__.py
-rw-r--r--  1 Matthew  staff   241B Dec  1 17:20 __init__.pyc
-rw-r--r--  1 Matthew  staff    53B Dec  1 17:20 __main__.py
-rw-r--r--  1 Matthew  staff   290B Dec  1 17:20 __main__.pyc
-rw-r--r--  1 Matthew  staff   8.8K Dec  1 17:20 builder.py
-rw-r--r--  1 Matthew  staff   7.1K Dec  1 17:20 builder.pyc
-rwxr-xr-x  1 Matthew  staff   402B Dec  1 17:20 cwlNodeEngine.js
-rw-r--r--  1 Matthew  staff   5.2K Dec  1 17:20 cwlrdf.py
-rw-r--r--  1 Matthew  staff   5.8K Dec  1 17:20 cwlrdf.pyc
-rw-r--r--  1 Matthew  staff   4.3K Dec  1 17:20 docker.py
-rw-r--r--  1 Matthew  staff   3.5K Dec  1 17:20 docker.pyc
-rw-r--r--  1 Matthew  staff   3.7K Dec  1 17:20 docker_uid.py
-rw-r--r--  1 Matthew  staff   4.8K Dec  1 17:20 docker_uid.pyc
-rw-r--r--  1 Matthew  staff    23K Dec  1 17:20 draft2tool.py
-rw-r--r--  1 Matthew  staff    18K Dec  1 17:20 draft2tool.pyc
-rw-r--r--  1 Matthew  staff   104B Dec  1 17:20 errors.py
-rw-r--r--  1 Matthew  staff   693B Dec  1 17:20 errors.pyc
-rw-r--r--  1 Matthew  staff   5.8K Dec  1 17:20 expression.py
-rw-r--r--  1 Matthew  staff   6.2K Dec  1 17:20 expression.pyc
-rw-r--r--  1 Matthew  staff   1.2K Dec  1 17:20 factory.py
-rw-r--r--  1 Matthew  staff   2.3K Dec  1 17:20 factory.pyc
-rw-r--r--  1 Matthew  staff   601B Dec  1 17:20 flatten.py
-rw-r--r--  1 Matthew  staff   887B Dec  1 17:20 flatten.pyc
-rw-r--r--  1 Matthew  staff    16K Dec  1 17:20 job.py
-rw-r--r--  1 Matthew  staff    12K Dec  1 17:20 job.pyc
-rw-r--r--  1 Matthew  staff   8.4K Dec  1 17:20 load_tool.py
-rw-r--r--  1 Matthew  staff   6.6K Dec  1 17:20 load_tool.pyc
-rw-r--r--  1 Matthew  staff    31K Dec  1 17:20 main.py
-rw-r--r--  1 Matthew  staff    25K Dec  1 17:20 main.pyc
-rw-r--r--  1 Matthew  staff   2.7K Dec  1 17:20 pack.py
-rw-r--r--  1 Matthew  staff   3.4K Dec  1 17:20 pack.pyc
-rw-r--r--  1 Matthew  staff   8.0K Dec  1 17:20 pathmapper.py
-rw-r--r--  1 Matthew  staff   9.4K Dec  1 17:20 pathmapper.pyc
-rw-r--r--  1 Matthew  staff    27K Dec  1 17:20 process.py
-rw-r--r--  1 Matthew  staff    25K Dec  1 17:20 process.pyc
-rw-r--r--  1 Matthew  staff   937B Dec  1 17:20 resolver.py
-rw-r--r--  1 Matthew  staff   1.5K Dec  1 17:20 resolver.pyc
-rw-r--r--  1 Matthew  staff   4.8K Dec  1 17:20 sandboxjs.py
-rw-r--r--  1 Matthew  staff   5.3K Dec  1 17:20 sandboxjs.pyc
drwxr-xr-x  6 Matthew  staff   204B Dec  1 17:20 schemas
-rw-r--r--  1 Matthew  staff   1.1K Dec  1 17:20 stdfsaccess.py
-rw-r--r--  1 Matthew  staff   3.1K Dec  1 17:20 stdfsaccess.pyc
-rw-r--r--  1 Matthew  staff    19K Dec  1 17:20 update.py
-rw-r--r--  1 Matthew  staff    17K Dec  1 17:20 update.pyc
-rw-r--r--  1 Matthew  staff   484B Dec  1 17:20 utils.py
-rw-r--r--  1 Matthew  staff   935B Dec  1 17:20 utils.pyc
-rw-r--r--  1 Matthew  staff    28K Dec  1 17:20 workflow.py
-rw-r--r--  1 Matthew  staff    25K Dec  1 17:20 workflow.pyc
>grep adjustFiles /Users/Matthew/.pyenv/versions/matts_2.7.8/lib/python2.7/site-packages/cwltool/process.py
def adjustFilesWithSecondary(rec, op, primary=None):
            adjustFilesWithSecondary(rec.get("secondaryFiles", []), op,
                adjustFilesWithSecondary(rec[d], op)
            adjustFilesWithSecondary(d, op, primary)
```

**Comment by cket** [comment]
Hi @MatthewRalston 
That version of CWL isn't currently supported, there is a PR in the works to fix that here:
https://github.com/BD2KGenomics/toil/pull/1340
Once that is merged you'll probably have better luck
