### ISSUE TITLE
aggressive AWS autoscaler polling causes 503 response and pipeline failure

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1445]
The autoscaler seems to be polling EC2 too often and causing API limits to be exceeded:

```
BotoServerError: 503 Service Unavailable
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>RequestLimitExceeded</Code><Message>Request limit exceeded.</Message></Error></Errors><RequestID>8648be89-3344-4b3c-af07-74c1cd014a81</RequestID></Response>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 248, in check
    scalerThread.join(timeout=0)
  File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 51, in run
    self.tryRun( )
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 406, in tryRun
    preemptable=self.preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/abstractProvisioner.py", line 156, in setNodeCount
    workerInstances = self._getWorkersInCluster(preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 555, in _getWorkersInCluster
    entireCluster = self._getNodesInCluster(both=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 552, in _getNodesInCluster
    return self.__getNodesInCluster(self.ctx, self.clusterName, both=both)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 537, in __getNodesInCluster
    'instance-state-name': 'pending'})
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 622, in get_only_instances
    next_token=next_token)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 681, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1170, in get_list
    response = self.make_request(action, params, path, verb)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1028, in _mexe
    raise BotoServerError(response.status, response.reason, body)
BotoServerError: BotoServerError: 503 Service Unavailable
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>RequestLimitExceeded</Code><Message>Request limit exceeded.</Message></Error></Errors><RequestID>8648be89-3344-4b3c-af07-74c1cd014a81</RequestID></Response>
```

Retrying this request might be a bit redundant since boto is probably retrying automatically. The autoscaler thread dies on this error, causing total failure of the pipeline--instead I think it should always catch the exception, back off for a minute or two, then retry the current autoscaler loop. (OK, this behaves almost identically to a retry, but the pipeline should never fail just because the autoscaler is getting throttled.)

Frustratingly, AWS documentation doesn't say *what* exactly the limits are. But maybe increasing the polling interval a bit would help.

----
edit: oops, I see now that the scaler interval is configurable with a commandline option. Still, I think the default should be increased, and the exception should be caught, but it might be tricky to figure out how to catch it (without doing a simple retry) without putting AWS-specific code in the generic clusterScaler.py.

**Comment by cket** [comment]
I suspect that the limits vary depending on the actual EC2 instance that is doing the requests. Do you know that information, or the size of the cluster when this error occurred?

**Comment by joelarmstrong** [comment]
The [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate) claim the limits are account-wide, unfortunately. So I guess it isn't necessarily that the autoscaler triggers these limits all by itself, but that getting throttled causes the thread to die.

The cluster was only 4 (m3.xlarge) worker nodes plus 1 (t2.medium) leader node at that point. The pipeline had been running for about 15 minutes.

**Comment by cket** [comment]
I didn't see your last comment before I opened the PR; if the limits are account wide then it's even stranger that we haven't seen this before on much larger clusters. I'll probably have to do some investigating before attempting to make a workaround for this. Hopefully we just don't see this again.

**Comment by cket** [comment]
I've started seeing this in the integration tests, probably because they now all use the AWS provisioner and run in parallel.
