### ISSUE TITLE
AWS runs: Identifying clusterName in VPC with multiple security groups

### ISSUE THREAD

**Issue by chapmanb** [BD2KGenomics/toil#1508]
CJ and all;
I've made progress in setting up AWS Toil CWL runs and am currently running into an issue when the AWSProvisioner class bootstraps. The origin of the problem is here:

https://github.com/BD2KGenomics/toil/blob/master/src/toil/provisioners/aws/awsProvisioner.py#L51

where it tries to infer the cluster name from security groups in the VPC. If you have any other security groups present in the VPC (default, plus any specialized ones for other applications) you get this error:
```
ip-10-0-0-210.ec2.internal 2017-02-13 19:09:09,739 MainThread INFO toil.common: Using AWS provisioner.
I0213 19:09:09.777951   152 sched.cpp:1987] Asked to stop the driver
I0213 19:09:09.778194   222 sched.cpp:1187] Stopping framework '90df95d0-8968-43ea-8994-d125f78ce8a1-0001'
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 727, in main
    outobj = toil.start(wf1)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 675, in start
    self._setProvisioner()
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 712, in _setProvisioner
    self._provisioner = AWSProvisioner(self.config, self._batchSystem)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 52, in __init__
    self.ctx = self._buildContext(clusterName=self.clusterName)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 97, in _buildContext
    return Context(availability_zone=zone, namespace=cls._toNameSpace(clusterName))
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 221, in _toNameSpace
    assert isinstance(clusterName, str), repr(clusterName)
AssertionError: ['toil-bcbio', 'default', 'bcbio_cluster_sg']
```
Are there approaches we can use to input the clusterName, or otherwise query for it, so we avoid the need to infer this from security_groups? Thanks for any suggestions/directions on how best to approach this.

**Comment by cket** [comment]
@chapmanb this is related to compatibility with older AWS accounts, right? I think the easiest work around is for the Toil leader to look at its own tags and look for the 'Name' tag. That's similar to what CGCloud did for leader discovery.

**Comment by cket** [comment]
Quick clarification - the 'Name' tag corresponds to the cluster name, which is why it will be useful here.
