### ISSUE TITLE
DependenciesTest is failing

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#156]
Error
Traceback (most recent call last):
  File "/Users/cj/jobTree/src/jobTree/test/dependencies/dependenciesTest.py", line 80, in testDependencies
    fn("comb", 10, 100, 100, 1, 10)
  File "/Users/cj/jobTree/src/jobTree/test/dependencies/dependenciesTest.py", line 74, in fn
    checkLog(logName, maxCpus, maxThreads, cpusPerJob, sleepTime)
  File "/Users/cj/jobTree/src/jobTree/test/dependencies/dependenciesTest.py", line 279, in checkLog
    (i, delta, epsilon))
RuntimeError: jobs out of sync: i=4 delta=9.384647 threshold=5.000000

**Comment by cket** [comment]
This test is disabled via
9942f87ff5b0469b25286fde17aea216c52d9fe4

**Comment by hannes-ucsc** [comment]
Works for me on the resume-clean-flags branch. Let's see if it still works after merging.

**Comment by hannes-ucsc** [comment]
Still works after merge. Closing.
