### ISSUE TITLE
Resource download isn't retried

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1565]
I just got a burst of failed jobs with:

```
673c500c-95a9-42cd-a381-413901fb7d82    Traceback (most recent call last):
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 325, in main
673c500c-95a9-42cd-a381-413901fb7d82        job = Job._loadJob(jobGraph.command, jobStore)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 865, in _loadJob
673c500c-95a9-42cd-a381-413901fb7d82        userModule = cls._loadUserModule(userModule)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 842, in _loadUserModule
673c500c-95a9-42cd-a381-413901fb7d82        return userModule.load()
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 568, in load
673c500c-95a9-42cd-a381-413901fb7d82        module = self.makeLoadable()
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 562, in makeLoadable
673c500c-95a9-42cd-a381-413901fb7d82        module = self if self.belongsToToil else self.localize()
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 478, in localize
673c500c-95a9-42cd-a381-413901fb7d82        resource.download(callback=stash)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 164, in download
673c500c-95a9-42cd-a381-413901fb7d82        self._save(tempDirPath)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 283, in _save
673c500c-95a9-42cd-a381-413901fb7d82        self._download(bytesIO)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 236, in _download
673c500c-95a9-42cd-a381-413901fb7d82        with closing(urlopen(self.url)) as content:
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
673c500c-95a9-42cd-a381-413901fb7d82        return _opener.open(url, data, timeout)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 410, in open
673c500c-95a9-42cd-a381-413901fb7d82        response = meth(req, response)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
673c500c-95a9-42cd-a381-413901fb7d82        'http', request, response, code, msg, hdrs)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 448, in error
673c500c-95a9-42cd-a381-413901fb7d82        return self._call_chain(*args)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
673c500c-95a9-42cd-a381-413901fb7d82        result = func(*args)
673c500c-95a9-42cd-a381-413901fb7d82      File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
673c500c-95a9-42cd-a381-413901fb7d82        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
673c500c-95a9-42cd-a381-413901fb7d82    HTTPError: HTTP Error 400: Bad Request
```

I'm not sure why a 400 was raised here, but the request should probably be retried with exponential backoff. If I had to guess, this might happen in rare cases when the user script resource is being refreshed at the exact same time--although that would be more likely to raise a 404 than a 400 I would think.

**Comment by cket** [comment]
I think retry is a good idea, I wish we had a more specific error than just `Bad Request` though.
