### ISSUE TITLE
Toil crashes when trying to add a child job function defined in an imported module

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1633]
I'm trying to use @cmarkello's `toil-vg`, which defines a library of Toil jobs that I can use.

However, when I e.g. `import toil_vg.vg_index` and try to `job.addChildJobFn(toil_vg.vg_index.run_xg_indexing, ...)` inside one of the jobs in my module, Toil explodes:

```
=========> Failed job 'xg_index_job' h/q/jobUOl1eA 
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('xg_index_job' h/q/jobUOl1eA) with ID (a39818eb68ba67ec5d5006144061d0113d878ba9).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
Traceback (most recent call last):
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1271, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1218, in _run
    return self.run(fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1384, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/toilvgfacade.py", line 155, in xg_index_job
    disk=options.xg_index_disk).rv()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 431, in addChildJobFn
    return self.addChild(JobFunctionWrappingJob(fn, *args, **kwargs))
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1346, in __init__
    self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/resource.py", line 397, in forModule
    assert os.path.isdir(dirPath)
AssertionError
ERROR:toil.worker:Exiting the worker because of a failed job on host kolossus
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'xg_index_job' h/q/jobUOl1eA with ID h/q/jobUOl1eA to 0
<=========
```

The job that's adding this child is defined in `toilvgfacade.py` in my module, while my module's `build.py` is the main Toil user script, and is called through the module entry points mechanism.

If, instead of passing the function I want to run to `addChildJobFn`, I pass a wrapper function defined in my module, the child job gets added successfully.

I am using Toil 3.6.0. The toil-vg module is installed in `/cluster/home/anovak/python/lib/python2.7/site-packages/toil_vg-1.1.0a1-py2.7.egg/toil_vg` and is thus available to my `python` without doing anything special.

**Comment by adamnovak** [comment]
OK, this is now blocking me. My workaround of wrapping the job with a function in my module works if I call a single job, but if I call a job in `toil-vg` that internally calls more jobs, I get the same error again:

```
=========> Failed job 'run_gcsa_prep_wrapper' d/l/jobmNylxQ 
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('gcsa_index_job' d/l/jobmNylxQ) with ID (f5dc1ea54ecd42be27f73688880f57089ee7793c).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False).
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('run_gcsa_prep_wrapper' d/l/jobmNylxQ) with ID (68c1e57a578c75551c5228fbc53f999701568bcd).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('run_gcsa_prep_wrapper' d/l/jobmNylxQ) with ID (68c1e57a578c75551c5228fbc53f999701568bcd).
WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.toilvgfacade', fromVirtualEnv=False)
INFO:toil-rt:Starting gcsa preprocessing...
Traceback (most recent call last):
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1271, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1218, in _run
    return self.run(fileStore)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1384, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/toilvgfacade.py", line 221, in run_gcsa_prep_wrapper
    return toil_vg.vg_index.run_gcsa_prep(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/toil_vg/vg_index.py", line 176, in run_gcsa_prep
    disk=options.prune_disk).rv()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 431, in addChildJobFn
    return self.addChild(JobFunctionWrappingJob(fn, *args, **kwargs))
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1346, in __init__
    self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/resource.py", line 397, in forModule
    assert os.path.isdir(dirPath)
AssertionError
ERROR:toil.worker:Exiting the worker because of a failed job on host kolossus
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'run_gcsa_prep_wrapper' d/l/jobmNylxQ with ID d/l/jobmNylxQ to 0
<=========
```

**Comment by cket** [comment]
It looks like you are trying to use eggs, right? I think that is the problem. Hot deployment does not support deployment of eggs

**Comment by adamnovak** [comment]
Yeah, the module I was using was installed as an egg. Installing it with `setup.py develop` lets it import its own files, and eliminates the need for wrapper functions.
