### ISSUE TITLE
'create-cluster' fails without hand-specifying coreos and toil appliance images

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil#1697]
Running the example command from the docs fails (error at bottom)

`toil launch-cluster cluster-name --nodeType=t2.micro -z us-west-2a --keyPairName=glenn.hickey@gmail.com`

@joelarmstrong suggested this fix, which seems to help:
prefix with `TOIL_AWS_AMI=ami-f4d4b694` (from https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_hvm_us-west-2.txt) as apparently wherever toil's getting coreos images from isn't always up to date. 

This causes the command above to loop forever.  This can be fixed by specifying a quay url that exists (more thanks to joel): 

`TOIL_APPLIANCE_SELF="quay.io/ucsc_cgl/toil:3.8.0a1.dev392-14bc15847c2c187431beae2ecb77649ff124b124" TOIL_AWS_AMI=ami-f4d4b694 toil launch-cluster cluster-name6 --nodeType=t2.micro -z us-west-2a --keyPairName=glenn.hickey@gmail.com`

pip install toil
toil --version
3.7.0

boreale 2017-05-31 09:49:58,732 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
boreale 2017-05-31 09:49:58,732 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
boreale 2017-05-31 09:49:58,732 MainThread INFO toil.utils.toilLaunchCluster: Using aws provisioner.
boreale 2017-05-31 09:50:01,416 MainThread INFO toil: Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
boreale 2017-05-31 09:50:01,416 MainThread INFO toil: Using default docker name of toil as TOIL_DOCKER_NAME is not set.
boreale 2017-05-31 09:50:01,417 MainThread INFO toil: Using default docker appliance of quay.io/ucsc_cgl/toil:3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b as TOIL_APPLIANCE_SELF is not set.
boreale 2017-05-31 09:50:01,417 MainThread INFO toil.provisioners.aws.awsProvisioner: Launching non-preemptable leader
Traceback (most recent call last):
  File "/home/hickey/dev/work/autoscale/venv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 33, in main
    module.main()
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 77, in main
    vpcSubnet=config.vpcSubnet)
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 397, in launchCluster
    create_ondemand_instances(ctx.ec2, image_id=cls._discoverAMI(ctx),
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/bd2k/util/__init__.py", line 45, in new_f
    r = f( *args )
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 149, in _discoverAMI
    coreOSAMI = [ami for ami in ctx.ec2.get_all_images(owners=['679593333241']) if
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 189, in get_all_images
    [('item', Image)], verb='POST')
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1171, in get_list
    body = response.read()
  File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 646, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)

**Comment by ejacox** [comment]
More info:
glennhickey [9:45 AM] 
I switched to a new AWS account, and cgcloud create-cluster doesnt work anymore.

[9:45] 
cgcloud create-cluster toil -s 2 --instance-type r3.8xlarge  --leader-instance-type r3.2xlarge --cluster-name toil-map-cluster --spot-bid 2
INFO: Using zone 'us-west-2a' and namespace '/glenn.hickey/'
INFO: === Creating leader ===
ERROR: No image with ordinal -1 for role toil-leader

[9:45] 
making one instance with cgcloud create seems okay.  any ideas @cket?

cket [8:30 PM] 
I'm not sure, I haven't used cgcloud in a while. I would try creating an AMI for the Toil role though


----- Today May 31st, 2017 -----
benedictpaten [6:30 AM] 
Have you tried using the new statically provisoned clusters feature? The intention is to get rid of direct cg cloud support. As @cket is leaving, @ejacox should work with you on this

glennhickey [6:53 AM] 
I can't find any documentation on statically provisioned clusters in toil.  Even running the example command that is there to make a leader doesn't work anymore on the new account (ucsc-vg-dev).

[6:53] 
toil launch-cluster cluster-name --nodeType=t2.micro -z us-west-2a --keyPairName=glenn.hickey@gmail.com
boreale 2017-05-31 09:49:58,732 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
boreale 2017-05-31 09:49:58,732 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
boreale 2017-05-31 09:49:58,732 MainThread INFO toil.utils.toilLaunchCluster: Using aws provisioner.
boreale 2017-05-31 09:50:01,416 MainThread INFO toil: Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
boreale 2017-05-31 09:50:01,416 MainThread INFO toil: Using default docker name of toil as TOIL_DOCKER_NAME is not set.
boreale 2017-05-31 09:50:01,417 MainThread INFO toil: Using default docker appliance of quay.io/ucsc_cgl/toil:3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b as TOIL_APPLIANCE_SELF is not set.
boreale 2017-05-31 09:50:01,417 MainThread INFO toil.provisioners.aws.awsProvisioner: Launching non-preemptable leader
Traceback (most recent call last):
 File "/home/hickey/dev/work/autoscale/venv/bin/toil", line 11, in <module>
   sys.exit(main())
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 33, in main
   module.main()
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 77, in main
   vpcSubnet=config.vpcSubnet)
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 397, in launchCluster
   create_ondemand_instances(ctx.ec2, image_id=cls._discoverAMI(ctx),
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/bd2k/util/__init__.py", line 45, in new_f
   r = f( *args )
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 149, in _discoverAMI
   coreOSAMI = [ami for ami in ctx.ec2.get_all_images(owners=['679593333241']) if
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 189, in get_all_images
   [('item', Image)], verb='POST')
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1171, in get_list
   body = response.read()
 File "/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/connection.py", line 410, in read
   self._cached_response = http_client.HTTPResponse.read(self)
 File "/usr/lib/python2.7/httplib.py", line 588, in read
   return self._read_chunked(amt)
 File "/usr/lib/python2.7/httplib.py", line 646, in _read_chunked
   value.append(self._safe_read(chunk_left))
 File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
   chunk = self.fp.read(min(amt, MAXAMOUNT))
 File "/usr/lib/python2.7/socket.py", line 384, in read
   data = self._sock.recv(left)
 File "/usr/lib/python2.7/ssl.py", line 756, in recv
   return self.read(buflen)
 File "/usr/lib/python2.7/ssl.py", line 643, in read
   v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)

joel [8:52 AM] 
they may have deleted the coreos ami, which seems to happen pretty often. I think we should be parsing it straight from https://stable.release.core-os.net/amd64-usr/current/ rather than from AWS like now, which seems a little flaky.

[8:52] 
it may work if you prefix with TOIL_AWS_AMI=ami-b5d4b6d5 which is the latest CoreOS AMI

glennhickey [9:40 AM] 
Thanks joel.  Get a different error doing that though.  File “/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py”, line 398, in launchCluster
   spec=kwargs, num_instances=1)
 File “/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/cgcloud/lib/ec2.py”, line 414, in create_ondemand_instances
   **spec ).instances
 File “/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/ec2/connection.py”, line 973, in run_instances
   verb=‘POST’)
 File “/home/hickey/dev/work/autoscale/venv/local/lib/python2.7/site-packages/boto/connection.py”, line 1208, in get_object
   raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version=“1.0” encoding=“UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>Virtualization type ‘hvm’ is required for instances of type ‘t2.micro’. Ensure that you are using an AMI with virtualization type ‘hvm’. For more information, see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html</Message></Error></Errors><RequestID>12c0f63b-84bc-4c11-91af-2a10890dcb9c</RequestID></Response>

joel [9:40 AM] 
whoops, my bad, I chose the PV AMI. Try ami-f4d4b694 (from https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_hvm_us-west-2.txt)

glennhickey [9:47 AM] 
Works better, but now seem to be in loop of

[9:47] 
boreale 2017-05-31 12:46:49,517 MainThread DEBUG toil.provisioners.aws.awsProvisioner: Node ec2-34-208-110-41.us-west-2.compute.amazonaws.com: /usr/bin/docker ps
boreale 2017-05-31 12:46:49,517 MainThread DEBUG toil.provisioners.aws.awsProvisioner: Full command ssh -o StrictHostKeyChecking=no -t core@ec2-34-208-110-41.us-west-2.compute.amazonaws.com /usr/bin/docker ps
Connection to ec2-34-208-110-41.us-west-2.compute.amazonaws.com closed.
boreale 2017-05-31 12:46:50,871 MainThread INFO toil.provisioners.aws.awsProvisioner: ...Still waiting, trying again in 10sec...

joel [9:50 AM] 
it *may* be downloading the toil docker image still--or just totally stuck. hard to tell. I think the server itself is online, logging into it may show what's going on

joel [9:58 AM] 
ah, I think it's because the toil appliance image quay.io/ucsc_cgl/toil:3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b doesn't exist. toil should really be checking that *before* launching a VM. you can set TOIL_APPLIANCE_SELF to something that does exist to fix that.

glennhickey [10:05 AM] 
OK, that worked, thanks!

**Comment by joelarmstrong** [comment]
related to #1688

**Comment by jessebrennan** [comment]
The missing documentation on static provisioning is in #1659. Note that CGCloud is still needed for some things however.
