### ISSUE TITLE
ReadTheDocs "Running in the Cloud" example failing.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1708]
From:
http://toil.readthedocs.io/en/releases-3.7.x/running/cloud.html?highlight=HelloWorld

This example fails:
```python
python HelloWorld.py \
       --batchSystem=mesos \
       --mesosMaster=master-private-ip:5050 \
       aws:us-west-2:my-aws-jobstore
```

This works:
```python
python HelloWorld.py  aws:us-west-2:my-jobstore
```

There is something strange going on with the bucket name.

The --batchSystem=mesos option is also failing:

eduroam-169-233-248-47.ucsc.edu 2017-06-08 18:04:04,934 MainThread DEBUG toil.jobStores.aws.jobStore: Binding to job store domain 'toil-registry'.
Traceback (most recent call last):
  File "HelloWorld.py", line 11, in <module>
    print Job.Runner.startToil(j, options) #Prints Hello, world!, ...
  File "/Users/ejacox/git/toil/src/toil/job.py", line 742, in startToil
    return toil.start(job)
  File "/Users/ejacox/git/toil/src/toil/common.py", line 661, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/Users/ejacox/git/toil/src/toil/common.py", line 808, in createBatchSystem
    from toil.batchSystems.mesos.batchSystem import MesosBatchSystem
  File "/Users/ejacox/git/toil/src/toil/batchSystems/mesos/batchSystem.py", line 35, in <module>
    import mesos.native
ImportError: No module named native

**Comment by ejacox** [comment]
My mistake. The script must be copied to the leader node.
