### ISSUE TITLE
Sporadic integration test failure due to KeyError: '/dev/xvda'

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#1742]
The test to fail is AWSStaticAutoscaleTest.testAutoScale.

Example of the trace
```
Traceback (most recent call last):
  File "/mnt/ephemeral/workspace/toil-pull-request-integration-tests/src/toil/test/provisioners/aws/awsProvisionerTest.py", line 249, in testAutoScale
    self._test(spotInstances=False)
  File "/mnt/ephemeral/workspace/toil-pull-request-integration-tests/src/toil/test/provisioners/aws/awsProvisionerTest.py", line 128, in _test
    self.launchCluster()
  File "/mnt/ephemeral/workspace/toil-pull-request-integration-tests/src/toil/test/provisioners/aws/awsProvisionerTest.py", line 278, in launchCluster
    rootBlockDevice = workers[0].block_device_mapping["/dev/xvda"]
KeyError: '/dev/xvda'
```

This is happening across multiple branches. This was most likely introduced in #1572 by not waiting for the worker to be running before checking if the volume is mounted.

**Comment by jessebrennan** [comment]
@joelarmstrong [reports still getting this error](https://github.com/BD2KGenomics/toil/pull/1743#issuecomment-314181619) and suggests a fix. I will call worker.update() up renew the block_device_mapping.
