### ISSUE TITLE
Job fails when submitting CWL to SGE cluster 

### ISSUE THREAD

**Issue by arnikz** [BD2KGenomics/toil#1756]
Hello,

I've installed toil (v3.9) and create toy example files `echo-job.cwl` and `echo-job.yml`:

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
stdout: output.txt
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs:
  output:
    type: stdout
```

`message: Hello world!`

submitted this CWL workflow to a SGE cluster using

`cwltoil --batchSystem gridEngine --maxCores 2 --maxMemory 1G --disableCaching echo-job.cwl echo-job.yml`

however, no `output.txt` file was created (the `singleMachine` mode works fine) because of job failure

```
hostname.xxx 2017-07-13 16:42:36,657 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Resolved 'echo-job.cwl' to 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl'
hostname.xxx 2017-07-13 16:42:36,659 MainThread INFO cwltool: Resolved 'echo-job.cwl' to 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl'
hostname.xxx 2017-07-13 16:42:37,401 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
hostname.xxx 2017-07-13 16:42:37,408 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '00923be1-2e34-4fd8-8489-5102fb2d094e'
hostname.xxx 2017-07-13 16:42:37,417 MainThread INFO toil.common: Using the grid engine batch system
hostname.xxx 2017-07-13 16:42:37,445 MainThread INFO toil.common: User script ModuleDescriptor(dirPath='/home/cog/akuzniar/miniconda3/envs/toil/lib/python2.7/site-packages', name='toil.cwl.cwltoil', fromVirtualEnv=False) belongs to Toil. No need to hot-deploy it.
hostname.xxx 2017-07-13 16:42:37,446 MainThread INFO toil.common: No user script to hot-deploy.
hostname.xxx 2017-07-13 16:42:37,446 MainThread INFO toil.common: Written the environment for the jobs to the environment file
hostname.xxx 2017-07-13 16:42:37,446 MainThread INFO toil.common: Caching all jobs in job store
hostname.xxx 2017-07-13 16:42:37,446 MainThread INFO toil.common: 0 jobs downloaded.
hostname.xxx 2017-07-13 16:42:37,459 MainThread INFO toil: Running Toil version 3.9.0a1.
hostname.xxx 2017-07-13 16:42:37,459 MainThread INFO toil.realtimeLogger: Real-time logging disabled
hostname.xxx 2017-07-13 16:42:37,473 MainThread INFO toil.toilState: (Re)building internal scheduler state
hostname.xxx 2017-07-13 16:42:37,473 MainThread INFO toil.leader: Found 1 jobs to start and 0 jobs with successors to run
hostname.xxx 2017-07-13 16:42:37,473 MainThread INFO toil.leader: Checked batch system has no running jobs and no updated jobs
hostname.xxx 2017-07-13 16:42:37,474 MainThread INFO toil.leader: Starting the main loop
hostname.xxx 2017-07-13 16:42:37,474 MainThread INFO toil.leader: Issued job 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 1.0 G
hostname.xxx 2017-07-13 16:43:15,499 MainThread WARNING toil.leader: Job failed with exit value 1: 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN
hostname.xxx 2017-07-13 16:43:15,502 MainThread WARNING toil.leader: No log file is present, despite job failing: 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN
hostname.xxx 2017-07-13 16:43:15,503 MainThread WARNING toil.jobGraph: Due to failure we are reducing the remaining retry count of job 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN with ID T/p/job2NaGsN to 0
hostname.xxx 2017-07-13 16:43:15,503 MainThread WARNING toil.jobGraph: We have increased the default memory of the failed job 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN to 2147483648 bytes
hostname.xxx 2017-07-13 16:43:15,534 MainThread WARNING toil.leader: Job 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN with ID T/p/job2NaGsN is completely failed
hostname.xxx 2017-07-13 16:43:17,535 MainThread INFO toil.leader: No jobs left to run so exiting.
hostname.xxx 2017-07-13 16:43:17,535 MainThread INFO toil.leader: Finished the main loop
hostname.xxx 2017-07-13 16:43:17,535 MainThread INFO toil.serviceManager: Waiting for service manager thread to finish ...
hostname.xxx 2017-07-13 16:43:18,483 MainThread INFO toil.serviceManager: ... finished shutting down the service manager. Took 0.948141098022 seconds
hostname.xxx 2017-07-13 16:43:18,484 MainThread INFO toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
hostname.xxx 2017-07-13 16:43:18,533 MainThread INFO toil.statsAndLogging: ... finished collating stats and logs. Took 0.0493679046631 seconds
hostname.xxx 2017-07-13 16:43:18,534 MainThread INFO toil.leader: Finished toil run with 1 failed jobs
hostname.xxx 2017-07-13 16:43:18,534 MainThread INFO toil.leader: Failed jobs at end of the run: 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN
keyerror
...

Traceback (most recent call last):
  File "/home/cog/akuzniar/miniconda3/envs/toil/bin/cwltoil", line 11, in <module>
    load_entry_point('toil==3.9.0a1', 'console_scripts', 'cwltoil')()
  File "/home/cog/akuzniar/miniconda3/envs/toil/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 763, in main
    outobj = toil.start(wf1)
  File "/home/cog/akuzniar/miniconda3/envs/toil/lib/python2.7/site-packages/toil/common.py", line 745, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/cog/akuzniar/miniconda3/envs/toil/lib/python2.7/site-packages/toil/common.py", line 1028, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/cog/akuzniar/miniconda3/envs/toil/lib/python2.7/site-packages/toil/leader.py", line 201, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/tmp/tmpVmAulo' contains 1 failed jobs: 'file:///home/cog/akuzniar/scripts/toil/echo-job.cwl' echo T/p/job2NaGsN
```

Could you please help?

**Comment by mr-c** [comment]
Hello @arnikz 
My guess is that `/tmp` was not present on all nodes of your cluster.

Here's how we run Toil @ EBI: https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/workflows/run-toil-v4.sh

Note the use of `--jobStore ` to specify a path known to present on all nodes

The error message should be updated to give this hint.

**Comment by arnikz** [comment]
Thanks @mr-c for suggestions! It worked out by setting the `workDir` to `/tmp` and adding the `--jobStore` path.

**Comment by adamnovak** [comment]
@kinow says this affects his project to run CWL with Toil on various HPC systems.
