### ISSUE TITLE
for subPath in os.listdir(path): out of memory

### ISSUE THREAD

**Issue by brainstorm** [BD2KGenomics/toil#1772]
The following job was running on a 4GB RAM node when running on cwltoil+PBSPro and https://github.com/bcbio/bcbio_validation_workflows (GiAB dataset with the all chromosomes, not only chr20):

```
r3682 2017-07-22 22:33:06,816 MainThread DEBUG toil.batchSystems.torque: getRunningJobIDs sleeping for 180 seconds
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/statsAndLogging.py", line 134, in statsAndLoggingAggregator
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 331, in readStatsAndLogging
    for tempDir in self._tempDirectories():
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 420, in _tempDirectories
    for tempDir in _dirs(self.tempFilesDir, self.levels):
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 416, in _dirs
    for i in _dirs(os.path.join(path, subPath), levels-1):
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 415, in _dirs
    for subPath in os.listdir(path):
OSError: [Errno 12] Cannot allocate memory: '/g/data3/gx8/projects/bcbio_validation_workflows/NA12878-chr20/cwltoil_work/cwltoil_jobstore/tmp/g'
```

**Comment by brainstorm** [comment]
A subsequent re-run yielded a different error on the same codepath:

```
r3682 2017-07-23 22:48:03,828 Thread-1 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Checking on jobs, sleeping for 180s
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/statsAndLogging.py", line 134, in statsAndLoggingAggregator
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 331, in readStatsAndLogging
    for tempDir in self._tempDirectories():
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 420, in _tempDirectories
    for tempDir in _dirs(self.tempFilesDir, self.levels):
  File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 415, in _dirs
    for subPath in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/g/data3/gx8/projects/bcbio_validation_workflows/NA12878-chr20/cwltoil_work/cwltoil_jobstore/tmp'
```

**Comment by brainstorm** [comment]
And more, perhaps filesystem related errors that did not happen in previous runs (collecting them here for future reference, reporting to our support engineers and perhaps better future error handling):

```
Y/3/jobLNGOdJ    DEBUG:toil.fileStore:LOG-TO-MASTER: Job Y/3/jobLNGOdJ/g/tmpaQhyiE.tmp used 151.86% (3.0 GB [3261077504B] used, 2.0 GB [2147483648B] requested) at the end of its run.
Y/3/jobLNGOdJ    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job Y/3/jobLNGOdJ/g/tmpaQhyiE.tmp used 151.86% (3.0 GB [3261077504B] used, 2.0 GB [2147483648B] requested) at the end of its run.
Y/3/jobLNGOdJ    Traceback (most recent call last):
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/worker.py", line 340, in main
Y/3/jobLNGOdJ        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/job.py", line 1289, in _runner
Y/3/jobLNGOdJ        returnValues = self._run(jobGraph, fileStore)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/job.py", line 1234, in _run
Y/3/jobLNGOdJ        return self.run(fileStore)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 292, in run
Y/3/jobLNGOdJ        existing=existing))
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/process.py", line 179, in adjustFilesWithSecondary
Y/3/jobLNGOdJ        adjustFilesWithSecondary(rec[d], op)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/process.py", line 179, in adjustFilesWithSecondary
Y/3/jobLNGOdJ        adjustFilesWithSecondary(rec[d], op)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/process.py", line 176, in adjustFilesWithSecondary
Y/3/jobLNGOdJ        primary if primary else rec["path"])
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/process.py", line 182, in adjustFilesWithSecondary
Y/3/jobLNGOdJ        adjustFilesWithSecondary(d, op, primary)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/cwltool/process.py", line 174, in adjustFilesWithSecondary
Y/3/jobLNGOdJ        rec["path"] = op(rec["path"], primary=primary)
Y/3/jobLNGOdJ      File "/g/data/gx8/local/bcbio-vm/anaconda/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 166, in getFile
Y/3/jobLNGOdJ        raise Exception("Conflicting filesStoreID %s and %s both trying to link to %s" % (index.get(dstPath, None), fileStoreID, dstPath))
Y/3/jobLNGOdJ    Exception: Conflicting filesStoreID L/H/tmpvPD7R9.tmp and m/Q/tmpcG5xfm.tmp both trying to link to /g/data3/gx8/projects/bcbio_validation_workflows/NA12878-chr20/cwltoil_work/toil-c0a09ea0-36d7-49e5-8c51-c9622cec9710-762b87a0e4a99615f815df3d0000005a/tmpG_tc7Y/7afcddc6-c5cc-49c5-9754-293d91a33f62/t5dXsnf/inp/tmpcifJzl/hg38.fa.fai
Y/3/jobLNGOdJ    ERROR:toil.worker:Exiting the worker because of a failed job on host r3682
Y/3/jobLNGOdJ    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///g/data3/gx8/projects/bcbio_validation_workflows/NA12878-chr20/NA12878-platinum-wgs-workflow/steps/prep_samples.cwl' bcbio_nextgen.py runfn prep_samples cwl Y/3/jobLNGOdJ with ID Y/3/jobLNGOdJ to 0
Added job: 'file:///g/data3/gx8/projects/bcbio_validation_workflows/NA12878-chr20/NA12878-platinum-wgs-workflow/steps/prep_samples.cwl' bcbio_nextgen.py runfn prep_samples cwl Y/3/jobLNGOdJ to active jobs
```

**Comment by brainstorm** [comment]
No filesystem issues confirmed by HPC admins. Currently investigating on whether [my PR on sleep/polling](https://github.com/BD2KGenomics/toil/pull/1769) might be causing race conditions... Last error is consistent now at 60s per `sleepSeconds()`.

**Comment by brainstorm** [comment]
Please @ejacox, do let me know if you manage to reproduce the issue (with sleepBatch patch applied), I want to rule out it's not a confounding effect of our HPC environment.

**Comment by ejacox** [comment]
@joelarmstrong thinks he has seen this before. The first two errors occurred in the same function. We can start by trying to force a failure there with a simple workflow.

**Comment by brainstorm** [comment]
@joelarmstrong @ejacox I am using [test_bcbio_cwl](https://github.com/bcbio/test_bcbio_cwl) as a reference, it executes in less than 5min, so easy to test.

**Comment by brainstorm** [comment]
The conflicting FileStoreID issue was solved by @chapmanb.

**Comment by ejacox** [comment]
That's great! We had trouble addressing this issue. We are not well set up to run toil on the various batch systems. We are working to change this.
