### ISSUE TITLE
Autoscaling documentation doesn't specify a batch system

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1832]
The single machine batch system doesn't work with the AWS provisioner, but the autoscaling examples do not show a different batch system being specified.

The [docs](http://toil.readthedocs.io/en/3.9.1/running/cloud.html#running-a-workflow-with-autoscaling) say to run:

```
$ python my-toi-script.py --provisioner=aws --nodeType=m3.large
```

But when I run my workflow like that (after adding a job store specifier) it explodes:

```
root@ip-172-31-26-85:~# python test_workflow.py aws:us-west-2:tree1 --provisioner=aws --nodeType=t2.micro
Master ip-172-31-26-85.us-west-2.compute.internal running on Toil 3.9.1-367ba6d4fdb76362128a81d8975a93cf24644049 from /usr/local/lib/python2.7/dist-packages/toil/__init__.pyc
Log level: None
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:04,700 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Traceback (most recent call last):
  File "test_workflow.py", line 118, in <module>
    entrypoint()
  File "test_workflow.py", line 115, in entrypoint
    sys.exit(main(sys.argv))
  File "test_workflow.py", line 91, in main
    with Toil(options) as toil_instance:
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 643, in __enter__
    jobStore.initialize(config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 119, in initialize
    raise JobStoreExistsException(self.locator)
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store 'us-west-2:tree1' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch
root@ip-172-31-26-85:~# toil clean aws:us-west-2:tree1
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:23,330 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:23,330 MainThread INFO toil.utils.toilClean: Attempting to delete the job store
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:26,234 MainThread INFO toil.utils.toilClean: Successfully deleted the job store
root@ip-172-31-26-85:~# python test_workflow.py aws:us-west-2:amntree1 --provisioner=aws --nodeType=t2.micro
Master ip-172-31-26-85.us-west-2.compute.internal running on Toil 3.9.1-367ba6d4fdb76362128a81d8975a93cf24644049 from /usr/local/lib/python2.7/dist-packages/toil/__init__.pyc
Log level: None
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:53,916 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,384 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '71c940e2-f5da-408f-a03a-57709f7fd9d7'
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,761 MainThread INFO toil.common: Using the single machine batch system
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,762 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (1).
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,762 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (1043447808).
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,763 MainThread INFO toil.common: Created the workflow directory at /var/lib/toil/toil-71c940e2-f5da-408f-a03a-57709f7fd9d7-3a999f28-8e8b-4bee-9eec-17d5f4fde443
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,763 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (46027411456).
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,765 MainThread INFO toil.common: No user script to hot-deploy.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,804 MainThread INFO toil.common: Written the environment for the jobs to the environment file
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:57,804 MainThread INFO toil.common: Caching all jobs in job store
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,091 MainThread INFO toil.common: 0 jobs downloaded.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,306 MainThread INFO toil.common: Using AWS provisioner.
Generating public/private rsa key pair.
Your identification has been saved in /root/.ssh/id_rsa.
Your public key has been saved in /root/.ssh/id_rsa.pub.
The key fingerprint is:
28:cc:02:26:03:39:ea:38:f2:d5:26:49:f3:34:10:ab root@ip-172-31-26-85.us-west-2.compute.internal
The key's randomart image is:
+--[ RSA 2048]----+
|..  ..           |
|+   ..           |
|=o  ..           |
|+o +o o.         |
|o E.+*..S        |
|+. .+.+          |
|.o . o           |
|  .              |
|                 |
+-----------------+
Agent pid 101
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,715 MainThread INFO toil: Running Toil version 3.9.1-367ba6d4fdb76362128a81d8975a93cf24644049.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,716 MainThread INFO toil.realtimeLogger: Real-time logging disabled
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,718 MainThread INFO toil.toilState: (Re)building internal scheduler state
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,718 MainThread INFO toil.leader: Found 1 jobs to start and 0 jobs with successors to run
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,718 MainThread INFO toil.leader: Checked batch system has no running jobs and no updated jobs
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,719 MainThread INFO toil.provisioners.clusterScaler: Starting with 0 non-preemptable nodes(s) in the cluster.
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,720 MainThread INFO toil.leader: Starting the main loop
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,720 MainThread INFO toil.leader: Waiting for workers to shutdown
Exception in thread scaler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 51, in run
    self.tryRun( )
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 444, in tryRun
    self.shutDown(preemptable=self.preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 633, in shutDown
    totalNodes = self.setNodeCount(numNodes=0, preemptable=preemptable, force=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 470, in setNodeCount
    workerInstances = self.getNodes(preemptable=preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 605, in getNodes
    allMesosNodes = self.scaler.leader.batchSystem.getNodes(preemptable, timeout=None)
AttributeError: 'SingleMachineBatchSystem' object has no attribute 'getNodes'

ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:58,727 MainThread INFO toil.serviceManager: Waiting for service manager thread to finish ...
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:59,720 MainThread INFO toil.serviceManager: ... finished shutting down the service manager. Took 0.992579936981 seconds
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:59,721 MainThread INFO toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
ip-172-31-26-85.us-west-2.compute.internal 2017-08-15 20:59:59,781 MainThread INFO toil.statsAndLogging: ... finished collating stats and logs. Took 0.0600109100342 seconds
Traceback (most recent call last):
  File "test_workflow.py", line 118, in <module>
    entrypoint()
  File "test_workflow.py", line 115, in entrypoint
    sys.exit(main(sys.argv))
  File "test_workflow.py", line 104, in main
    toil_instance.start(root_job)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 711, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 969, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 180, in run
    self.clusterScaler.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 267, in shutdown
    scaler.join()
  File "/usr/local/lib/python2.7/dist-packages/bd2k/util/threading.py", line 51, in run
    self.tryRun( )
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 444, in tryRun
    self.shutDown(preemptable=self.preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 633, in shutDown
    totalNodes = self.setNodeCount(numNodes=0, preemptable=preemptable, force=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 470, in setNodeCount
    workerInstances = self.getNodes(preemptable=preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 605, in getNodes
    allMesosNodes = self.scaler.leader.batchSystem.getNodes(preemptable, timeout=None)
AttributeError: 'SingleMachineBatchSystem' object has no attribute 'getNodes'
```

I think I need a batch system. Other examples for AWS say to use the Mesos batch system.

**Comment by jessebrennan** [comment]
This should be fixed in #1752.
