### ISSUE TITLE
All toil commands and workflows crash when a non-resolvable hostname is set

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1858]
When you have a macOS computer with a hostname set, and the hostname (crucially) is *not* resolved by the local DNS, anything importing toil.common will crash with the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/joel/toil-fresh/venv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/utils/toilMain.py", line 11, in main
    modules = loadModules()
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/utils/toilMain.py", line 38, in loadModules
    from toil.utils import toilKill, toilStats, toilStatus, toilClean, toilLaunchCluster, toilDestroyCluster, toilSSHCluster, toilRsyncCluster
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/utils/toilKill.py", line 22, in <module>
    from toil.common import Toil, jobStoreLocatorHelp, Config
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/common.py", line 533, in <module>
    def addOptions(parser, config=Config()):
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/common.py", line 75, in __init__
    setDefaultBatchOptions(self)
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/batchSystems/options.py", line 99, in setDefaultOptions
    config.mesosMasterAddress = '%s:5050' % getLocalIP()
  File "/Users/joel/toil-fresh/venv/lib/python2.7/site-packages/toil/batchSystems/options.py", line 23, in getLocalIP
    return socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

This happens because macOS doesn't automatically resolve its hostname to the local IP, and the DNS server won't know about your hostname unless it integrates with DHCP.

A band-aid fix is to manually add a line like
127.0.0.1 my-hostname

in /etc/hosts. But I think we should look into making the getPublicIP() method a bit better, by finding the actual IP that would be used for a default route. (The following SO answer has the right idea: https://stackoverflow.com/a/28950776) I think we should be able to find a reserved IP that can be used for this.

**Comment by joelarmstrong** [comment]
Solved in #1878
