### ISSUE TITLE
rsync-cluster does not work inside a docker container.

### ISSUE THREAD

**Issue by bjea** [BD2KGenomics/toil#1866]
Hi there,

If an AWS cluster is launched by using the following command (or the like):
```docker run --rm -v `pwd`:/root --workdir=/root -p 5050:5050 toil_cwl_aws:latest toil launch-cluster my-cluster --nodeType t2.micro --keyPairName MyKeyPair --zone us-west-2c```

then when trying to run:
```docker run --rm -v `pwd`:/root --workdir=/root -p 5050:5050 -e "TOIL_AWS_ZONE=us-west-2c" toil_cwl_aws:latest toil rsync-cluster my-cluster sort.py :/tmp```

the error message shows that:
```
21705c517546 2017-09-09 22:56:25,341 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Traceback (most recent call last):
  File "/usr/local/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 33, in main
    module.main()
  File "/usr/local/lib/python2.7/site-packages/toil/utils/toilRsyncCluster.py", line 41, in main
    cluster.rsyncCluster(args=config.args, strict=not config.insecure)
  File "/usr/local/lib/python2.7/site-packages/toil/provisioners/__init__.py", line 77, in rsyncCluster
    self.provisioner.rsyncLeader(self.clusterName, args, self.zone, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 232, in rsyncLeader
    cls._rsyncNode(leader.public_dns_name, args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 491, in _rsyncNode
    return subprocess.check_call(command + parsedArgs)
  File "/usr/local/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

even though `sort.py` is listed as one of the files by ```docker run --rm -v `pwd`:/root --workdir=/root -p 5050:5050 -e "TOIL_AWS_ZONE=us-west-2c" toil_cwl_aws:latest ls```.

Alternatively, i tried to use the commands below:
```docker run --rm -it -v `pwd`:/root --workdir=/root -p 5050:5050 toil_cwl_aws:latest bash```

```root@123:~#  toil launch-cluster my-cluster --keyPairName MyKeyPair --nodeType t2.micro --zone us-west-2c```

```root@123:~#  export TOIL_AWS_ZONE=us-west-2c```

```root@123:~#  toil rsync-cluster my-cluster sort.py :/tmp```

it would show the same error message:
`OSError: [Errno 2] No such file or directory`

even though the file is actually there and `scp` would work fine.

BTW, if `export TOIL_AWS_ZONE=us-west-2c` is not run, it would show that:
```
File "/usr/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 506, in _getLeader
    ctx = cls._buildContext(clusterName=clusterName, zone=zone)
  File "/usr/local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 366, in _buildContext
    'Could not determine availability zone. Insure that one of the following '
RuntimeError: Could not determine availability zone. Insure that one of the following is true: the --zone flag is set, 
the TOIL_AWS_ZONE environment variable is set, ec2_region_name is set in the .boto file, or that you are running on EC2.
```

**Comment by bjea** [comment]
The error was because my local docker image lacked `rsync` package.
