### ISSUE TITLE
realtimeLogger won't start up on my mac in single machine mode

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1877]
The real time logger is upset that my FQDN is in the `in-addr.arpa` domain, and that it can't turn around and resolve it back to an IP.

```
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py:540: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Vyoma 2017-09-14 10:27:56,718 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Vyoma 2017-09-14 10:27:56,731 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '5ea1f538-be65-44d2-a615-4ba0d2cd52ee'
Vyoma 2017-09-14 10:27:58,959 MainThread INFO toil_vg.vg_index: Imported input files into Toil in 2.22710990906 seconds
Vyoma 2017-09-14 10:27:58,982 MainThread INFO toil.common: Using the single machine batch system
Vyoma 2017-09-14 10:27:58,983 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (4).
Vyoma 2017-09-14 10:27:58,983 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (8589934592).
Vyoma 2017-09-14 10:27:58,993 MainThread INFO toil.common: Created the workflow directory at /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/toil-5ea1f538-be65-44d2-a615-4ba0d2cd52ee-106618767760070
Vyoma 2017-09-14 10:27:58,993 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (16062173184).
Vyoma 2017-09-14 10:27:59,000 MainThread INFO toil.common: No user script to hot-deploy.
Vyoma 2017-09-14 10:27:59,001 MainThread INFO toil.common: Written the environment for the jobs to the environment file
Vyoma 2017-09-14 10:27:59,001 MainThread INFO toil.common: Caching all jobs in job store
Vyoma 2017-09-14 10:27:59,001 MainThread INFO toil.common: 0 jobs downloaded.
Vyoma 2017-09-14 10:27:59,009 MainThread INFO toil: Running Toil version 3.10.1-6fc52a6cce9103cfb38d150ce0fce73c610bc461.
Vyoma 2017-09-14 10:27:59,009 MainThread INFO toil.realtimeLogger: Starting real-time logging.
Traceback (most recent call last):
  File "/Users/anovak/Documents/Workspace/vg/.env/bin/toil-vg", line 9, in <module>
    load_entry_point('toil-vg==1.2.1a1', 'console_scripts', 'toil-vg')()
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil_vg/vg_toil.py", line 326, in main
    index_main(context, args)
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil_vg/vg_index.py", line 469, in index_main
    index_key_and_id = toil.start(init_job)
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil/common.py", line 716, in start
    return self._runMainLoop(rootJobGraph)
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil/common.py", line 978, in _runMainLoop
    level=self.options.logLevel if self.options.realTimeLogging else None):
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil/realtimeLogger.py", line 242, in __enter__
    RealtimeLogger._startLeader(self.__batchSystem, level=self.__level)
  File "/Users/anovak/Documents/Workspace/vg/.env/lib/python2.7/site-packages/toil/realtimeLogger.py", line 148, in _startLeader
    ip = socket.gethostbyname(fqdn)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
=========================== 1 failed in 8.11 seconds ===========================
Running locally
Uploaded HTML as file://report-html/index.html
Markdown to post:
Jenkins vg tests complete.  View the [full report here](file://report-html/index.html).

0 tests passed, 1 tests failed and 0 tests skipped in 8 seconds

Failed tests:

* test_sim_brca1_snp1kg (6 seconds)
Vyoma:vg anovak$ python -i
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.fqdn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'fqdn'
>>> socket.getfqdn()
'1.0.0.127.in-addr.arpa'
>>> socket.gethostbyname(socket.getfqdn())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>> 
```

Toil may need special-case code to detect this vaguely fake FQDN and/or work around not being able to resolve it.

**Comment by joelarmstrong** [comment]
Everyone's been getting this for about a week now, tracked in #1858. Are you on macOS?

Given how many people are using master branch, we should really just revert or commit a band-aid fix.

**Comment by adamnovak** [comment]
Yeah, this is on OS X. I fixed it by adding an entry to hosts for that
nonsense DNS name.

What's weird is that it used to work, with my actual (non-fqdn) hostname in
/etc/hosts. Maybe I just didn't have the offending commit yet.

**Comment by ejacox** [comment]
@joelarmstrong revert which PR?

**Comment by joelarmstrong** [comment]
#1731, but actually I think I can get a proper fix in during the upcoming meeting. It's probably better to fix it properly than revert.

**Comment by joelarmstrong** [comment]
Actually, just noticed this has a slightly different stacktrace than #1858, though it has exactly the same cause, so reverting that PR wouldn't fix it anyway.
