### ISSUE TITLE
Error running the sort.py example with autoscaling on AWS.

### ISSUE THREAD

**Issue by bjea** [BD2KGenomics/toil#1913]
Hi there,

When i tried to run the `sort.py` example with autoscaling on AWS by following the steps in the Documentation, after i ran `python /tmp/sort.py aws:us-west-2:autoscaling-sort-jobstore --provisioner aws --nodeTypes c3.large --batchSystem mesos --mesosMaster <private-IP>:5050 --logLevel DEBUG`, the error message was as following:
```
Traceback (most recent call last):
  File "/tmp/sort.py", line 219, in <module>
    main()
  File "/tmp/sort.py", line 214, in main
    memory=sortMemory))
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 727, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 997, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 147, in __init__
    self.clusterScaler = None if self.provisioner is None else ClusterScaler(self.provisioner, self, self.config)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 254, in __init__
    require(sum(config.maxNodes) > 0, 'Not configured to create nodes of any type.')
  File "/usr/local/lib/python2.7/dist-packages/bd2k/util/exceptions.py", line 81, in require
    raise RequirementError( message)
bd2k.util.exceptions.RequirementError: Not configured to create nodes of any type.

```

BTW, the new `--nodeType` flag has been changed to `--nodeTypes`, but no matter i used `--nodeTypes c3.large` or `--nodeType c3.large`, the same error was raised. 

Thank you,

bettie

**Comment by bjea** [comment]
Hi again,

BTW, even if i removed `--nodeTypes` this flag, the same error was raised.
```
ip-172-31-8-166.us-west-2.compute.internal 2017-10-04 23:35:37,435 MainThread DEBUG toil.batchSystems.mesos.batchSystem: Joined Mesos driver
2017-10-04 23:35:37,435 - toil.batchSystems.mesos.batchSystem - DEBUG - Joined Mesos driver
ip-172-31-8-166.us-west-2.compute.internal 2017-10-04 23:35:37,436 MainThread DEBUG toil.common: ... finished shutting down the batch system in 0.00110697746277 seconds.
2017-10-04 23:35:37,436 - toil.common - DEBUG - ... finished shutting down the batch system in 0.00110697746277 seconds.
Traceback (most recent call last):
  File "/tmp/sort.py", line 219, in <module>
    main()
  File "/tmp/sort.py", line 214, in main
    memory=sortMemory))
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 727, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 997, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 147, in __init__
    self.clusterScaler = None if self.provisioner is None else ClusterScaler(self.provisioner, self, self.config)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 254, in __init__
    require(sum(config.maxNodes) > 0, 'Not configured to create nodes of any type.')
  File "/usr/local/lib/python2.7/dist-packages/bd2k/util/exceptions.py", line 81, in require
    raise RequirementError( message)
bd2k.util.exceptions.RequirementError: Not configured to create nodes of any type.
```

Thank you,

bettie

**Comment by ejacox** [comment]
This works for me. Try localhost:5050 for --mesosMaster

**Comment by adderan** [comment]
You need the --maxNodes flag as well, otherwise it defaults to zero nodes of each type. We could change the default to 1, maybe.

**Comment by bjea** [comment]
Yes, the `--maxNodes` flag is needed as well; otherwise, the same error would be raised.  Thank you very much, @adderan !!  The `--nodeTypes` flag is also needed; otherwise, AssertionError would be raised.

Hi @ejacox , for me, `--mesosMaster localhost:5050` did not work somehow; it would continue running endlessly without yielding a result.  However, `<private IP>:5050` worked.  Therefore, the command, which worked, i used was:
`python /tmp/sort.py  aws:us-west-2:autoscaling-sort-jobstore --provisioner aws --batchSystem mesos --mesosMaster <Private IP>:5050 --logLevel DEBUG --nodeTypes c3.large --maxNodes 8`

BTW, if i used `localhost:5050`, the DEBUG logs looked like below (the same messages appeared repetitively):
```
2017-10-09 21:49:24,442 scaler INFO toil.provisioners.clusterScaler: There are 0 nodes being ignored by the batch system, checking if they can be terminated
2017-10-09 21:49:24,442 - toil.provisioners.clusterScaler - INFO - There are 0 nodes being ignored by the batch system, checking if they can be terminated
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:53,668 scaler INFO toil.provisioners.clusterScaler: Detected 1 queued jobs.
2017-10-09 21:49:53,668 - toil.provisioners.clusterScaler - INFO - Detected 1 queued jobs.
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:53,669 scaler DEBUG toil.provisioners.clusterScaler: Running bin packing for node shapes [_Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)] and 10 job(s).
2017-10-09 21:49:53,669 - toil.provisioners.clusterScaler - DEBUG - Running bin packing for node shapes [_Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)] and 10 job(s).
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:53,669 scaler DEBUG toil.provisioners.clusterScaler: Running bin packing for node shapes [_Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)] and 1 job(s).
2017-10-09 21:49:53,669 - toil.provisioners.clusterScaler - DEBUG - Running bin packing for node shapes [_Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)] and 1 job(s).
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,780 scaler DEBUG toil.provisioners.aws.awsProvisioner: All nodes in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,780 - toil.provisioners.aws.awsProvisioner - DEBUG - All nodes in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler DEBUG toil.provisioners.aws.awsProvisioner: All workers found in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,781 - toil.provisioners.aws.awsProvisioner - DEBUG - All workers found in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler DEBUG toil.provisioners.aws.awsProvisioner: non-preemptable workers found in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,781 - toil.provisioners.aws.awsProvisioner - DEBUG - non-preemptable workers found in cluster: [Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0167864a6b39f0cdc, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-04b29b704ffeee6b7, Instance:i-07b45c00caa2afc6f, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler INFO toil.provisioners.clusterScaler: Nodes of type c3.large to run recent jobs: 10
2017-10-09 21:49:54,781 - toil.provisioners.clusterScaler - INFO - Nodes of type c3.large to run recent jobs: 10
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler INFO toil.provisioners.clusterScaler: Nodes of type c3.large to run queued jobs = 1
2017-10-09 21:49:54,781 - toil.provisioners.clusterScaler - INFO - Nodes of type c3.large to run queued jobs = 1
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler INFO toil.provisioners.clusterScaler: Estimating 8 nodes of shape _Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)
2017-10-09 21:49:54,781 - toil.provisioners.clusterScaler - INFO - Estimating 8 nodes of shape _Shape(wallTime=3600, memory=3919157657.6, cores=2, disk=34359738368, preemptable=False)
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler INFO toil.provisioners.clusterScaler: Currently 8 nodes of type c3.large in cluster
2017-10-09 21:49:54,781 - toil.provisioners.clusterScaler - INFO - Currently 8 nodes of type c3.large in cluster
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,781 scaler DEBUG toil.provisioners.clusterScaler: Difference in new (8) and previous estimates in number of c3.large (8) required is within beta (1.2), making no change.
2017-10-09 21:49:54,781 - toil.provisioners.clusterScaler - DEBUG - Difference in new (8) and previous estimates in number of c3.large (8) required is within beta (1.2), making no change.
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,869 scaler DEBUG toil.provisioners.aws.awsProvisioner: All nodes in cluster: [Instance:i-0fc73e86d67e91759, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,869 - toil.provisioners.aws.awsProvisioner - DEBUG - All nodes in cluster: [Instance:i-0fc73e86d67e91759, Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,869 scaler DEBUG toil.provisioners.aws.awsProvisioner: All workers found in cluster: [Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,869 - toil.provisioners.aws.awsProvisioner - DEBUG - All workers found in cluster: [Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,869 scaler DEBUG toil.provisioners.aws.awsProvisioner: non-preemptable workers found in cluster: [Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
2017-10-09 21:49:54,869 - toil.provisioners.aws.awsProvisioner - DEBUG - non-preemptable workers found in cluster: [Instance:i-0819603ef85e782ed, Instance:i-0fffbe08e2314bb06, Instance:i-07b45c00caa2afc6f, Instance:i-0167864a6b39f0cdc, Instance:i-04b29b704ffeee6b7, Instance:i-0bec4e7a55497aebf, Instance:i-09136f580ef1d14e9, Instance:i-0843ae5c3b3a99ff6]
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,870 scaler DEBUG toil.provisioners.clusterScaler: Consolidating state between mesos and provisioner
2017-10-09 21:49:54,870 - toil.provisioners.clusterScaler - DEBUG - Consolidating state between mesos and provisioner
ip-172-31-14-242.us-west-2.compute.internal 2017-10-09 21:49:54,870 scaler DEBUG toil.provisioners.clusterScaler: Worker node at 172.31.13.111 is not reporting executor information
```
