### ISSUE TITLE
ValueError on slurm batch system

### ISSUE THREAD

**Issue by ifiddes** [BD2KGenomics/toil#1929]
A user of my pipeline with a Slurm cluster reported this traceback after upgrading his toil to 3.11.0:

```
10-19 09:39:58 luigi-interface ERROR [pid 40083] Worker Worker(salt=945881764, workers=16, host=holyhoekstra01.rc.fas.harvard.edu, username=lassance, pid=36709) failed    ToilTask: GenerateHints for rheMac3 using batchSystem Slurm
Traceback (most recent call last):
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/n/home01/lassance/Comparative-Annotation-Toolkit/cat/__init__.py", line 1023, in run
    hints_db(self.hints_args, toil_options)
  File "/n/home01/lassance/Comparative-Annotation-Toolkit/cat/hints_db.py", line 81, in hints_db
    combined_hints = t.start(job)
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/common.py", line 727, in start
    return self._runMainLoop(rootJobGraph)
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/common.py", line 997, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/leader.py", line 183, in run
    self.innerLoop()
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/leader.py", line 487, in innerLoop
    self.checkForDeadlocks()
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/leader.py", line 504, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 379, in getRunningBatchJobIDs
    batchIds = self.worker.getRunningJobIDs()
  File "/n/home01/lassance/.conda/envs/ENV_PROGRESSIVECACTUS/lib/python2.7/site-packages/toil/batchSystems/slurm.py", line 53, in getRunningJobIDs
    slurm_jobid, state, elapsed_time = values
ValueError: too many values to unpack
```

https://github.com/ComparativeGenomicsToolkit/Comparative-Annotation-Toolkit/issues/77#issuecomment-337684302

**Comment by lassancejm** [comment]
more on the context of this error: I was still running toil 3.6.0 before updating to 3.11.0. 
I ran some tests on various releases (3.11.0, 3.10, 3.9.0, 3.8.0, 3.7.0), which all gave me the same error. 
Went back to 3.6.0, and it seems to be working fine.

**Comment by lassancejm** [comment]
Trying to revisit this error. I realize that some problems are caused by the fact that our local deployment of Slurm relies on a modified version of the squeue command. Basically, some options are to be misinterpreted. 
I made the following changes at line 48: 
original:
```
lines = subprocess.check_output(['squeue', '-h', '--format', '%i %t %M']).split('\n')
```
corrected:
```
lines = subprocess.check_output(['squeue', '--noheader', '--format="%i %t %M"']).split('\n')
```
Can someone double-check this?

**Comment by ejacox** [comment]
Thank you for tracking this down @lassancejm. The = sign after format looks like the correct option. Using '--noheader' instead of 'h' doesn't change anything. Can you submit a PR?
