### ISSUE TITLE
Remove read-only files in localTempDir

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#196]

**Comment by jvivian** [comment]
If there are files owned by root in a directory in localTempDir, jobTree fails to delete the folder:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jobTree/worker.py", line 430, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/jobTree/worker.py", line 421, in main
    shutil.rmtree(localWorkerTempDir)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/home/ubuntu/fake_mnt/tmpjA2Po2/localTempDir/logs/mapsplice_original.log'
ERROR:jobTree.batchSystems.singleMachine:Got exit code 1 (indicating failure) from command '/usr/bin/python -E /usr/local/lib/python2.7/dist-packages/jobTree/worker.py /home/ubuntu/
jobTree N/w/jobX4tbl4'.
```

**Comment by hannes-ucsc** [comment]
John, didn't we resolve this yesterday? Assigning to you for the final call.

**Comment by jvivian** [comment]
Resolved by utilizing a wrapper in the container to change ownership of output files in the mounted drive to the host.  Tested and confirmed that it worked yesterday.
