### ISSUE TITLE
CWL conformance test may time out

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#2016]
The exact test is: 
```
src.toil.test.cwl.cwlTest.CWLTest.test_run_conformance
```
I experiences this here:

http://jenkins.cgcloud.info/job/toil-pull-requests/3546/testReport/junit/src.toil.test.cwl.cwlTest/CWLTest/test_run_conformance/

Since the test has been expanded, the timeout should be increased (short term solution), or maybe the test should be broken up (eh...).

**Comment by mr-c** [comment]
@jessebrennan If you think the Jenkins server can handle it, then you can run 2 or more tests at a time by passing `-j2` or similar to `run_test.sh`: https://github.com/BD2KGenomics/toil/blob/master/src/toil/test/cwl/cwlTest.py#L134

**Comment by jessebrennan** [comment]
@mr-c I tried this and tried to run it locally (both with and without the `-j2` option) but get the following error..

```
=================================== FAILURES ===================================
_________________________ CWLTest.test_run_conformance _________________________
Traceback (most recent call last):
  File "/Users/jesse/Documents/genomics/toil/src/toil/test/cwl/cwlTest.py", line 152, in test_run_conformance
    raise e
CalledProcessError: Command '['bash', 'run_test.sh', '-j2', 'RUNNER=toil-cwl-runner', 'DRAFT=v1.0']' returned non-zero exit status 1
----------------------------- Captured stdout call -----------------------------
run_test.sh: line 82: greadlink: command not found
--- Running conformance test v1.0 on  ---
run_test.sh: line 68: : command not found
Test [1/87] 

...

Test [87/87] 

Traceback (most recent call last):
  File "/Users/jesse/Documents/genomics/toil/venv/bin/cwltest", line 11, in <module>
    sys.exit(main())
  File "/Users/jesse/Documents/genomics/toil/venv/lib/python2.7/site-packages/cwltest/__init__.py", line 328, in main
    test_result = job.result()
  File "/Users/jesse/Documents/genomics/toil/venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/jesse/Documents/genomics/toil/venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jesse/Documents/genomics/toil/venv/lib/python2.7/site-packages/cwltest/__init__.py", line 208, in run_test
    process = subprocess.Popen(test_command, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

1 tool tests failed

----------------------------- Captured stderr call -----------------------------
INFO:toil.test:Setting up toil.test.cwl.cwlTest.CWLTest.test_run_conformance ...
INFO:toil.test:Tore down toil.test.cwl.cwlTest.CWLTest.test_run_conformance
=========================== 1 failed in 1.60 seconds ===========================
Process finished with exit code 0
```

Maybe I should make a separate issue for this. Are you able to run this test locally?

**Comment by mr-c** [comment]
@jessebrennan https://github.com/common-workflow-language/common-workflow-language/blob/master/CONFORMANCE_TESTS.md#notes

**Comment by mr-c** [comment]
@jessebrennan Sorry for the unhelpful error, I've made an issue about it: https://github.com/common-workflow-language/common-workflow-language/issues/595

**Comment by jessebrennan** [comment]
@mr-c thanks now I can run the test.
