### ISSUE TITLE
TypeError: unhashable type: 'CommentedSeq'

### ISSUE THREAD

**Issue by KerstenBreuer** [BD2KGenomics/toil#2022]
I get following error when running one of my CWL workflow with toil 3.13.0:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 316, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1323, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1268, in _run
    return self.run(fileStore)
    shortname(inp["source"]), promises[inp["source"]].rv())
  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 170, in shortname
    d = urllib.parse.urlparse(inputid)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'CommentedSeq'
```

For older versions of toil I get:
```
 Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 876, in main
    job = cwltool.main.load_job_order(options, t, sys.stdin)
TypeError: load_job_order() takes exactly 5 arguments (3 given)
```

With the cwltool it works, though.

Has someone an idea what went wrong?

**Comment by KerstenBreuer** [comment]
OK I found the error.
You are only allowed to specify the input source as list if you use the `linkMerge `method.

What's wrong:
```
steps:
  validate_data:
    in:
      feat_in:
        source: 
          - feat_in
      label_in:
        source: 
          - label_in
      metadata_in:
        source: 
          - metadata_in
    out:
      - validated_feat
      - validated_label
      - validated_metadata
    run: ../tools/01_validate_data.cwl
```

What's right:
```
steps:
  validate_data:
    in:
      feat_in:
        source: feat_in
      label_in:
        source: label_in
      metadata_in:
        source: metadata_in
    out:
      - validated_feat
      - validated_label
      - validated_metadata
    run: ../tools/01_validate_data.cwl
```

This would be correct syntax, too:
```
steps:
  validate_data:
    in:
      feat_in:
        source: feat_in
      label_in:
        source: label_in
      metadata_in:
        source: 
          - metadata1_in
          - metadata1_in
        linkMerge: merge_flattened
    out:
      - validated_feat
      - validated_label
      - validated_metadata
    run: ../tools/01_validate_data.cwl
```

Of course, this totally makes sense. So it's no fault of toil. I created this workflow with the rabix composer and I will advice them to change this. What's strange, however, is that it works with cwltool and the rabix bunny obviously tolerates it, too.

Either way, if you see this error, you know what to do.

**Comment by mr-c** [comment]
We recently fixed cwltool to accept this, so toil needs to update its cwltool dependency to gain the fix.

**Comment by screx** [comment]
It appears this is also the case if you use array notation on outputSource.

e.g. This would fail and give the  `unhashable type: 'CommentedSeq' ` error.
```
outputs:
  ofile:
    type: File
    outputSource: [example/results]
```
and this would work
```
ofile:
  type: File
  outputSource: example/results
```

I assume that since it works for cwltool this would also be fixed when the dependency is updated?

**Comment by mr-c** [comment]
@screx correct!
