### ISSUE TITLE
Race condition leading to `RuntimeError: Set changed size during iteration` in abstractGridEngineBatchSystem

### ISSUE THREAD

**Issue by ifiddes-10x** [BD2KGenomics/toil#2030]
I am using a modified gridEngine system that relies on an unmodified `abstractGridEngineBatchSystem`. When the number of jobs climbs into the hundreds, this error happens within a few minutes:

```
Traceback (most recent call last):
  File "/mnt/home/ian/anaconda2/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus', 'console_scripts', 'cactus')()
  File "/mnt/home/ian/cactus/src/cactus/progressive/cactus_progressive.py", line 449, in main
    halID = toil.restart()
  File "/mnt/home/ian/toil/src/toil/common.py", line 773, in restart
    return self._runMainLoop(rootJobGraph)
  File "/mnt/home/ian/toil/src/toil/common.py", line 1018, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/mnt/home/ian/toil/src/toil/leader.py", line 197, in run
    self.innerLoop()
  File "/mnt/home/ian/toil/src/toil/leader.py", line 501, in innerLoop
    self.checkForDeadlocks()
  File "/mnt/home/ian/toil/src/toil/leader.py", line 518, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/mnt/home/ian/toil/src/toil/batchSystems/abstractGridEngineBatchSystem.py", line 379, in getRunningBatchJobIDs
    batchIds = self.worker.getRunningJobIDs()
  File "/mnt/home/ian/toil/src/toil/batchSystems/hydra.py", line 37, in getRunningJobIDs
    currentjobs = dict((str(self.batchJobIDs[x][0]), x) for x in self.runningJobs)
  File "/mnt/home/ian/toil/src/toil/batchSystems/hydra.py", line 37, in <genexpr>
    currentjobs = dict((str(self.batchJobIDs[x][0]), x) for x in self.runningJobs)
RuntimeError: Set changed size during iteration
```

Restarting the pipeline enough times eventually leads to the jobs finishing. Any ideas on what to look at? I don't understand the toil model well enough to understand why runningJobs is changing during this process.

**Comment by joelarmstrong** [comment]
Hey Ian,

This is caused by the leader thread trying to get the running jobs (code path starting with `getRunningBatchJobIDs()`) while the batch system thread is taking a job in from `newJobsQueue` (code path starting with `run`). That exact issue can be prevented by acquiring a mutex around this line:

https://github.com/BD2KGenomics/toil/blob/377b62e81737605f22c611847ef603a2e912508d/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L129

as well as this line (actually, its equivalent in your custom batch system):

https://github.com/BD2KGenomics/toil/blob/377b62e81737605f22c611847ef603a2e912508d/src/toil/batchSystems/gridengine.py#L46

But there are probably other races lurking around. I can try to take a look to see if I can find any more obvious ones.
