### ISSUE TITLE
Test S3AM (SSEC) with URLs from public S3 Buckets

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#214]

**Comment by jvivian** [comment]
Local file worked, URL from public S3 bucket did not.  Stack trace below:

```
2015-08-07 19:46:42,361 upload(20585) Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3am/upload.py", line 263, in _stream_part
    self._upload_part( upload_id, part_num, buf )
  File "/usr/local/lib/python2.7/dist-packages/s3am/upload.py", line 316, in _upload_part
    headers=headers )
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer
```

**Comment by hannes-ucsc** [comment]
John, if you still have it, could you attach the command line you used to produce this?
