### ISSUE TITLE
Toil can't start because it tries to import azure things when the azure extra is not installed

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2193]
I installed Toil with the aws and mesos extras, but now it is trying to import Azure things and failing.

Toil needs to not crash when Azure stuff is unavailable, or actually depend on those modules that it needs so it can start correctly.

```
[anovak@kolossus population-mapping-paper]$ pip install toil-vg toil[aws,mesos]
...
Successfully installed awscli-1.15.9 boto3-1.7.9 botocore-1.10.9 toil-3.15.0 toil-vg-1.2.0
[anovak@kolossus population-mapping-paper]$ toil
Traceback (most recent call last):
  File "/cluster/home/anovak/python/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilMain.py", line 12, in main
    modules = loadModules()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilMain.py", line 38, in loadModules
    from toil.utils import (toilKill,
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 20, in <module>
    from toil.jobStores.azureJobStore import credential_file_path
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/jobStores/azureJobStore.py", line 45, in <module>
    from azure.cosmosdb.table import TableService, EntityProperty, Entity
ImportError: No module named table
```

**Comment by adamnovak** [comment]
After uninstalling every module with "azure" in it, on the theory that I maybe had enough of Azure to trick Toil into using it but not enough for it to work, I now get a different import error on startup:

```
[anovak@kolossus population-mapping-paper]$ toil
Traceback (most recent call last):
  File "/cluster/home/anovak/python/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilMain.py", line 12, in main
    modules = loadModules()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilMain.py", line 38, in loadModules
    from toil.utils import (toilKill,
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/utils/toilLaunchCluster.py", line 20, in <module>
    from toil.jobStores.azureJobStore import credential_file_path
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/jobStores/azureJobStore.py", line 42, in <module>
    from azure.common import AzureMissingResourceHttpError, AzureException
ImportError: No module named azure.common
```

**Comment by adamnovak** [comment]
This actually looks like a dupe of #2173. I will try the patch which fixes that.

**Comment by adamnovak** [comment]
Yep. Looks like I can get a working setup with:

```
pip install toil-vg git+https://github.com/BD2KGenomics/toil.git@92e6f743a62ef12424c1f06fcd4121f13ef51d0e#egg=toil[aws,mesos]
```
