### ISSUE TITLE
Provisioner can't fit jobs it could fit before, and can't explain itself.

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2237]
I woke up to an 802 megabyte Toil log this morning. It seems that the provisioner can't fit jobs that used to work with node types of "i3.8xlarge,i3.8xlarge:0.90" into any of "i3.8xlarge,r4.8xlarge:0.60".

The log looks like this.

```
DEBUG:toil.provisioners.clusterScaler:Running bin packing for node shapes [<toil.provisioners.abstractProvisioner.Shape object at 0x7fa0441a3dd0>, <toil.provisioners.abstractProvisioner.Shape object at 0x7fa0441a3f50>] and 35 job(s).
2018-06-06 23:22:07,570 - toil.provisioners.clusterScaler - DEBUG - Running bin packing for node shapes [<toil.provisioners.abstractProvisioner.Shape object at 0x7fa0441a3dd0>, <toil.provisioners.abstractProvisioner.Shape object at 0x7fa0441a3f50>] and 35 job(s).
WARNING:toil.provisioners.clusterScaler:Couldn't fit job with requirements <toil.provisioners.abstractProvisioner.Shape object at 0x7fa044094fd0> into any nodes in the nodeTypes list.
2018-06-06 23:22:07,571 - toil.provisioners.clusterScaler - WARNING - Couldn't fit job with requirements <toil.provisioners.abstractProvisioner.Shape object at 0x7fa044094fd0> into any nodes in the nodeTypes list.
ERROR:toil.provisioners.clusterScaler:Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things may go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 857, in tryRun
    currentNodeCounts)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 460, in getEstimatedNodeCounts
    goalTime=self.targetTime)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 288, in binPacking
    bpf.binPack(jobShapes)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 85, in binPack
    self.addJobShape(jS)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 104, in addJobShape
    nodeReservations = self.nodeReservations[chosenNodeShape]
KeyError: None
```

It then continued throwing the same KeyError several times a second for many hours, but not shutting down the workflow or the cluster.

I think there are 3 bugs here:
- [x] There are constant and absurdly frequent KeyErrors instead of a graceful shutdown
- [x] Job requirements and node sizes are reported as `<toil.provisioners.abstractProvisioner.Shape object at 0x7fa0441a3dd0>` or similar instead of actual numbers, which prevents me from knowing how big the problem job is and how bit a node I need to provide.
- [ ] The jobs aren't getting scheduled onto the i3.8xlarge instances, where they ought to fit.

┆Issue Number: TOIL-24

**Comment by DailyDreaming** [comment]
Thanks for logging this.  Shape objects should print as a string however (in Toil 3.16.0):
https://github.com/BD2KGenomics/toil/blob/master/src/toil/provisioners/abstractProvisioner.py#L80

What version of Toil is this?

**Comment by joelarmstrong** [comment]
@DailyDreaming: I think if you use `__str__` on a list it uses `__repr__` on the elements inside rather than `__str__`. (Who knows why...) But that's easy to fix just by adding in a repr.

This is probably on me. I recently messed with the bin packing--it looks like it will end up seizing up if you have a job larger than every single one of your nodes. Well, oops. That's a unit test to add.

Yeah, the thousands of KeyErrors a second is probably not ideal. I can add a throttling bit in there, though I want to push back on the graceful shutdown idea: I have personally had thousands of dollars of wasted compute because the scaler shut down multiple times on stupid transient AWS errors, so I am super jaded about toil's eagerness to shutdown. Toil has played the game of "try to retry only on these certain exceptions we've seen thrown by boto" and lost every time, because there are about a hundred different exceptions boto can choose to throw. Better IMO to just keep the scaler thread spinning, since scaling is sort of a non-essential "bonus" feature. That way, your cluster can keep chugging along finishing jobs until the scaler recovers (if ever).

**Comment by DailyDreaming** [comment]
@joelarmstrong My mistake, forgot about `__repr__` when that was written.

Maybe we could add the caveat that only if there are no currently active jobs waiting to finish, it should attempt to gracefully shutdown?  That way nothing's cancelled and the user can still specify new instances to fulfill the needs of whatever jobs are holding it up.

**Comment by glennhickey** [comment]
About the third point: Toil has some history of underestimating disk space on i3  (https://github.com/BD2KGenomics/toil/issues/2057).  Is it possible the fix for this somehow got reverted in 3.16.0?

**Comment by adamnovak** [comment]
This is definitely 3.16.0.

Maybe shutting down the whole workflow is too dramatic a response? But if the scaler thread is itself having internal errors, and no jobs are running, I'm not sure it makes sense to keep it up, because it's not making progress. On the other hand, we don't want to shut down just because the scaler got a bad reply from Amazon.

**Comment by DailyDreaming** [comment]
@joelarmstrong just made a fix #2239 that's been merged if you want to try it.

**Comment by adamnovak** [comment]
@DailyDreaming How do I turn this into a Docker that I can use as TOIL_APPLIANCE_SELF for testing? It looks like the Quay.io repo doesn't have a build with Joel's changes yet.

**Comment by adamnovak** [comment]
It looks like I have to do https://toil.readthedocs.io/en/latest/contributing/contributing.html#making-your-own-toil-docker-image

**Comment by adamnovak** [comment]
OK, I have managed to get it to run with my built version of the Toil Docker, from my Quay repo, but it persists in trying to fetch the dashboard stuff from the UCSC repo:

```
2018-06-12 22:29:41,204 - toil.provisioners.clusterScaler - INFO - Starting with the following nodes in the cluster: defaultdict(<type 
'int'>, {Shape(wallTime=3600, memory=2.61885630874e+11, cores=32, disk=53687091200, preemptable=True): 0, Shape(wallTime=3600, memory=2
.61885630874e+11, cores=32, disk=8160437862.4, preemptable=False): 0})
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
2018-06-12 22:29:41,205 - toil - INFO - Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
Error: No such object: toil_prometheus
Error response from daemon: No such container: toil_prometheus
Unable to find image 'quay.io/ucsc_cgl/toil-prometheus:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty' locally
docker: Error response from daemon: manifest for quay.io/ucsc_cgl/toil-prometheus:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty not found.
See 'docker run --help'.
WARNING:toil.common:Could not start prometheus/grafana dashboard.
2018-06-12 22:29:42,392 - toil.common - WARNING - Could not start prometheus/grafana dashboard.
Error response from daemon: No such container: toil_mtail
INFO:toil.leader:Starting the main loop
```

Then it throws a bunch of errors in the scaler thread:

```
INFO:toil.provisioners.clusterScaler:Currently 1 nodes of type r4.8xlarge in cluster
2018-06-12 22:31:01,316 - toil.provisioners.clusterScaler - INFO - Currently 1 nodes of type r4.8xlarge in cluster
ERROR:toil.provisioners.clusterScaler:Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things may go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 856, in tryRun
    currentNodeCounts)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 496, in getEstimatedNodeCounts
    desiredSize=estimatedNodeCount)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 1212, in logClusterSize
    self.log("current_size '%s' %i" % (nodeType, currentSize))
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 1203, in log
    self.mtailProc.stdin.write(message + "\n")
IOError: [Errno 32] Broken pipe
2018-06-12 22:31:01,316 - toil.provisioners.clusterScaler - ERROR - Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things may go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 856, in tryRun
    currentNodeCounts)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 496, in getEstimatedNodeCounts
    desiredSize=estimatedNodeCount)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 1212, in logClusterSize
    self.log("current_size '%s' %i" % (nodeType, currentSize))
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 1203, in log
    self.mtailProc.stdin.write(message + "\n")
IOError: [Errno 32] Broken pipe
DEBUG:toil.provisioners.clusterScaler:Running bin packing for node shapes [Shape(wallTime=3600, memory=2.61885630874e+11, cores=32, disk=53687091200, preemptable=True), Shape(wallTime=3600, memory=2.61885630874e+11, cores=32, disk=8160437862.4, preemptable=False)] and 1 job(s).
```

It looks like running on an AWS cluster with the dashboard and a custom TOIL_APPLIANCE_SELF might just not work. I will try again without the dashboard.

**Comment by adamnovak** [comment]
OK, even without metrics it doesn't appear to work. I get the master appliance to come up with the right Toil version, but then it tries to retrieve the images for the workers from a different place and fails:

```
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
2018-06-12 23:48:29,245 - toil - INFO - Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
2018-06-12 23:48:29,246 - toil - INFO - Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/ucsc_cgl/toil:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty with quay.io/ucsc_cgl/toil:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty from TOIL_APPLIANCE_SELF.
2018-06-12 23:48:29,246 - toil - INFO - Overriding docker appliance of quay.io/ucsc_cgl/toil:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty with quay.io/ucsc_cgl/toil:3.17.0a1-e606f0b818377abd990b43e509de861484643614-dirty from TOIL_APPLIANCE_SELF.
INFO:toil.provisioners.aws.awsProvisioner:Launching 1 preemptable nodes
2018-06-12 23:48:29,573 - toil.provisioners.aws.awsProvisioner - INFO - Launching 1 preemptable nodes
```

Do I also need to set environment variables for the individual workflows, in addition to the TOIL_APPLIANCE_SELF used to start up the cluster? This isn't really explained in https://toil.readthedocs.io/en/latest/contributing/contributing.html#making-your-own-toil-docker-image which seems to imply that just starting up the master with the right image will be sufficient.

**Comment by adamnovak** [comment]
It looks like an official Docker with this fix in it has been released. I am able to run it, and it stops throwing errors, but it still can't place my jobs that it used to be able to place:

```
2018-06-14 21:04:45,801 - toil.provisioners.clusterScaler - WARNING - Couldn't fit job with requirements Shape(wallTime=2.45261137372, 
memory=53687091200, cores=4, disk=107374182400, preemptable=False) into any nodes in the nodeTypes list.
WARNING:toil.provisioners.clusterScaler:Couldn't fit job with requirements Shape(wallTime=2.45261137372, memory=53687091200, cores=4, d
isk=107374182400, preemptable=False) into any nodes in the nodeTypes list.
2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - WARNING - Couldn't fit job with requirements Shape(wallTime=2.45261137372, 
memory=53687091200, cores=4, disk=107374182400, preemptable=False) into any nodes in the nodeTypes list.
WARNING:toil.provisioners.clusterScaler:Couldn't fit job with requirements Shape(wallTime=2.45261137372, memory=53687091200, cores=4, d
isk=107374182400, preemptable=False) into any nodes in the nodeTypes list.
2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - WARNING - Couldn't fit job with requirements Shape(wallTime=2.45261137372, 
memory=53687091200, cores=4, disk=107374182400, preemptable=False) into any nodes in the nodeTypes list.
INFO:toil.provisioners.clusterScaler:Nodes of type r4.8xlarge to run queued jobs = 0
2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - INFO - Nodes of type r4.8xlarge to run queued jobs = 0
INFO:toil.provisioners.clusterScaler:Estimating 0 nodes of shape 
Shape wallTime: 3600
Shape memory: 2.61885630874e+11
Shape cores: 32
Shape disk: 53687091200
Shape preemptable: True


2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - INFO - Estimating 0 nodes of shape 
Shape wallTime: 3600
Shape memory: 2.61885630874e+11
Shape cores: 32
Shape disk: 53687091200
Shape preemptable: True


INFO:toil.provisioners.clusterScaler:Currently 0 nodes of type r4.8xlarge in cluster
2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - INFO - Currently 0 nodes of type r4.8xlarge in cluster
INFO:toil.provisioners.clusterScaler:Nodes of type i3.8xlarge to run queued jobs = 0
2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - INFO - Nodes of type i3.8xlarge to run queued jobs = 0
INFO:toil.provisioners.clusterScaler:Estimating 0 nodes of shape 
Shape wallTime: 3600
Shape memory: 2.61885630874e+11
Shape cores: 32
Shape disk: 8160437862.4
Shape preemptable: False


2018-06-14 21:04:45,802 - toil.provisioners.clusterScaler - INFO - Estimating 0 nodes of shape 
Shape wallTime: 3600
Shape memory: 2.61885630874e+11
Shape cores: 32
Shape disk: 8160437862.4
Shape preemptable: False
```

It looks like Toil thinks the non-preemptible node type (which is an i3.8xlarge) has only 8 GB of disk, when really it has 4 x 1900 NVMe SSDs, according to Amazon, for 7.6 TB of disk.

So where is Toil getting its ideas of node sizes?
