### ISSUE TITLE
Toil doesn't recognize my virtualenv

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2244]
I am trying to use the Toil Makefile, in a virtualenv, but it complains that I am not in a virtualenv. I definitely am in a virtualenv.

```
[anovak@courtyard toil]$ virtualenv --version
16.0.0
[anovak@courtyard toil]$ virtualenv .venv
New python executable in /public/home/anovak/build/toil/.venv/bin/python
Installing setuptools, pip, wheel...done.
[anovak@courtyard toil]$ . .venv/bin/activate
(.venv) [anovak@courtyard toil]$ make docker
A virtualenv must be active.
make: *** [check_venv] Error 1
(.venv) [anovak@courtyard toil]$ which python
~/build/toil/.venv/bin/python
```

┆Issue Number: TOIL-282

**Comment by adamnovak** [comment]
It looks like Toil is following the advice from https://stackoverflow.com/a/1883251 to try and use `sys.real_prefix` or `sys.base_prefix` to detect a virtualenv. But for me they are not being set.

This is what I see:
```
(.venv) [anovak@courtyard toil]$ python -i
Python 2.7.15 (default, Jun  1 2018, 10:23:34) 
[GCC 8.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.real_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'real_prefix'
>>> sys.base_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'base_prefix'
>>> sys.prefix
'/public/home/anovak/build/toil/.venv'
>>> 

(.venv) [anovak@courtyard toil]$ echo $VIRTUAL_ENV
/public/home/anovak/build/toil/.venv

```

**Comment by DailyDreaming** [comment]
Yes, I had the same problem when running a normal venv with python 3.6 (`virtualenv -p python3.6 venv`) and so I have a fix in the python2/3 PR, but hadn't added it yet.
