### ISSUE TITLE
Autoscaler can try to launch zero nodes

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2256]
I caught the autoscaler trying to launch 0 nodes, getting rebuked by Amazon, and then having an error in the scaler thread.

```
2018-06-21 20:51:08,554 - toil.provisioners.clusterScaler - DEBUG - Nodes considered to terminate: i-05f6149a065ead637 at 34.219.47.64
INFO:toil.provisioners.clusterScaler:Terminating 1 instance(s).
2018-06-21 20:51:08,555 - toil.provisioners.clusterScaler - INFO - Terminating 1 instance(s).
INFO:toil.provisioners.aws.awsProvisioner:Terminating instance(s): [u'i-05f6149a065ead637']
2018-06-21 20:51:08,555 - toil.provisioners.aws.awsProvisioner - INFO - Terminating instance(s): [u'i-05f6149a065ead637']
INFO:toil.provisioners.aws.awsProvisioner:Instance(s) terminated.
2018-06-21 20:51:08,688 - toil.provisioners.aws.awsProvisioner - INFO - Instance(s) terminated.
INFO:toil.provisioners.clusterScaler:Cluster contains 1 instances
2018-06-21 20:51:08,758 - toil.provisioners.clusterScaler - INFO - Cluster contains 1 instances
INFO:toil.provisioners.clusterScaler:Cluster contains 1 instances of type i3.8xlarge (1 ignored and draining jobs until they can be saf
ely terminated)
2018-06-21 20:51:08,758 - toil.provisioners.clusterScaler - INFO - Cluster contains 1 instances of type i3.8xlarge (1 ignored and drain
ing jobs until they can be safely terminated)
INFO:toil.provisioners.clusterScaler:Unignoring 1 nodes because we want to scale back up again.
2018-06-21 20:51:08,758 - toil.provisioners.clusterScaler - INFO - Unignoring 1 nodes because we want to scale back up again.
INFO:toil.provisioners.clusterScaler:Adding 0 non-preemptable nodes to get to desired cluster size of 1.
2018-06-21 20:51:08,758 - toil.provisioners.clusterScaler - INFO - Adding 0 non-preemptable nodes to get to desired cluster size of 1.
INFO:toil:Overriding docker registry of quay.io/ucsc_cgl with quay.io/adamnovak from TOIL_DOCKER_REGISTRY.
2018-06-21 20:51:09,438 - toil - INFO - Overriding docker registry of quay.io/ucsc_cgl with quay.io/adamnovak from TOIL_DOCKER_REGISTRY
.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
2018-06-21 20:51:09,438 - toil - INFO - Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/adamnovak/toil:3.17.0a1-79c241c0eb273a3af6952202e38bd8d0c4bfe05c with quay.io/adamnova
k/toil:3.17.0a1-79c241c0eb273a3af6952202e38bd8d0c4bfe05c from TOIL_APPLIANCE_SELF.
2018-06-21 20:51:09,438 - toil - INFO - Overriding docker appliance of quay.io/adamnovak/toil:3.17.0a1-79c241c0eb273a3af6952202e38bd8d0
c4bfe05c with quay.io/adamnovak/toil:3.17.0a1-79c241c0eb273a3af6952202e38bd8d0c4bfe05c from TOIL_APPLIANCE_SELF.
INFO:toil.provisioners.aws.awsProvisioner:Launching 0 non-preemptable nodes
2018-06-21 20:51:09,693 - toil.provisioners.aws.awsProvisioner - INFO - Launching 0 non-preemptable nodes
INFO:toil.lib.ec2:Creating i3.8xlarge instance(s) ... 
2018-06-21 20:51:09,693 - toil.lib.ec2 - INFO - Creating i3.8xlarge instance(s) ... 
ERROR:toil.provisioners.clusterScaler:Exception encountered in scaler thread. Making a best-effort attempt to keep going, but things ma
y go wrong from now on.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 857, in tryRun
    self.scaler.updateClusterSize(estimatedNodeCounts)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 526, in updateClusterSize
    newNodeCount = self.setNodeCount(nodeType=nodeType, numNodes=estimatedNodeCount, preemptable=nodeShape.preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 596, in setNodeCount
    preemptable=preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 612, in _addNodes
    return self.provisioner.addNodes(nodeType=nodeType, numNodes=numNodes, preemptable=preemptable)
  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 274, in addNodes
    spec=kwargs, num_instances=numNodes)
  File "/usr/local/lib/python2.7/dist-packages/toil/lib/ec2.py", line 365, in create_ondemand_instances
    **spec).instances
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Minimum instance count must be greater than zero</Message></Error></Errors><RequestID>77a28cd2-eb9d-492c-b36c-6934abe89a0d</RequestID></Response>
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-285)
┆Issue Number: TOIL-285

**Comment by joelarmstrong** [comment]
Hahaha, whoops. Hopefully non-fatal?

It should be an easy fix. This is probably my bad so self-assigning.
