### ISSUE TITLE
GridEngine's testIssueJob sometimes randomly fails

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#382]
Has anyone else noticed this? It seems to fail about a fifth of the time. I think it may be because the test job issued lasts at most 1 second. It might be nice to up it to 5 or 10 seconds to give gridEngine a more comfortable margin to find and report the job.

**Comment by adderan** [comment]
I think the test would hang if the job finished executing too quickly.
wait_for_jobs would cycle forever waiting for the job ID to be issued.

**Comment by jvivian** [comment]
To add to this :while testing a separate issue (#342),  I was consistently stalling during **testGetRuningJobIDs**.

**Comment by joelarmstrong** [comment]
Oops, yes, you're right Alden, I think it would hang. So maybe executing too quickly isn't the problem, but something else is wrong instead.

The log says:
```
self = <toil.test.batchSystems.batchSystemTest.GridEngineTest testMethod=testIssueJob>

    def testIssueJob(self):
        test_path = os.path.join(self.tempDir, 'test.txt')
        # sleep 1 coupled to command as 'touch' was too fast for wait_for_jobs to catch
        jobCommand = 'touch {}; sleep 1'.format(test_path)
        self.batchSystem.issueBatchJob(jobCommand, memory=10, cores=1, disk=1000)
        self.wait_for_jobs(wait_for_completion=True)
>       self.assertTrue(os.path.exists(test_path))
E       AssertionError: False is not true

src/toil/test/batchSystems/batchSystemTest.py:87: AssertionError
```

Standard error:
```
INFO:toil.test:Setting up toil.test.batchSystems.batchSystemTest.GridEngineTest.testIssueJob ...
DEBUG:toil.batchSystems.gridengine:List of runningJobs: set([])
DEBUG:toil.batchSystems.gridengine:Issued the job command: touch /tmp/toil-test-toil.test.batchSystems.batchSystemTest.GridEngineTest.testIssueJob-testFiles-_CRoQz/test.txt; sleep 1 with job id: 0 
DEBUG:toil.batchSystems.gridengine:**qsub -b y -terse -j y -cwd -o /dev/null -e /dev/null -N Toil-Job_0 -hard -l vf=0K,h_vmem=0K touch /tmp/toil-test-toil.test.batchSystems.batchSystemTest.GridEngineTest.testIssueJob-testFiles-_CRoQz/test.txt; sleep 1
DEBUG:toil.batchSystems.gridengine:List of runningJobs: set([0])
DEBUG:toil.batchSystems.gridengine:List of runningJobs: set([0])
DEBUG:toil.batchSystems.gridengine:Received queue sentinel.
INFO:toil.test:Tore down toil.test.batchSystems.batchSystemTest.GridEngineTest.testIssueJob
```

This is on jenkins.

**Comment by jvivian** [comment]
The verbose logs I got for getRunningJobs was:

```
src/toil/test/batchSystems/batchSystemTest.py::GridEngineTest::testGetRunningJobIDs INFO:toil.test:Setting up toil.test.batchSystems.batchSystemTest.GridEngineTest.testGetRunningJobIDs ...
DEBUG:toil.batchSystems.gridengine:List of runningJobs: set([])
DEBUG:toil.batchSystems.gridengine:Issued the job command: sleep 100 with job id: 0 
DEBUG:toil.batchSystems.gridengine:Issued the job command: sleep 100 with job id: 1 
DEBUG:toil.batchSystems.gridengine:**qsub -b y -terse -j y -cwd -o /dev/null -e /dev/null -N Toil-Job_0 -hard -l vf=97656.25K,h_vmem=97656.25K sleep 100
Unable to run job: warning: ubuntu your job is not allowed to run in any queue
Your job 8 ("Toil-Job_0") has been submitted.
Exiting.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/toil/src/toil/batchSystems/gridengine.py", line 208, in run
    self.createJobs(new_job)
  File "/home/ubuntu/toil/src/toil/batchSystems/gridengine.py", line 186, in createJobs
    sgeJobID = qsub(qsubline)
  File "/home/ubuntu/toil/src/toil/batchSystems/gridengine.py", line 84, in qsub
    result = int(process.stdout.readline().strip().split('.')[0])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by hannes-ucsc** [comment]
Alden, since you're already working in this area, do you mind taking this? 

Remember that you can always spin up your own toil-jenkins-slave which has GridEngine on it.

**Comment by DailyDreaming** [comment]
This seems to be fixed.
