### ISSUE TITLE
Toil can't unpickle classes defined in user scripts

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#423]
I have a class, `AzureIOStore`, defined in my user script. It overrides `__getstate__` and `__setstate__` for custom pickling behavior.

Toil can't seem to unpickle it on my Mesos workers:

```
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	Next available file descriptor: 5
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	DEBUG:__main__:Next available file descriptor: 5
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	Parsed job
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	DEBUG:__main__:Parsed job
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	Traceback (most recent call last):
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 238, in main
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	    jobStore)._execute( jobWrapper=job,
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 555, in _loadJob
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	    return cls._unpickle(userModule, fileHandle)
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 576, in _unpickle
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	    return unpickler.load()
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 571, in filter_main
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	    return getattr(userModule, class_name)
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	AttributeError: 'module' object has no attribute 'AzureIOStore'
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	Exiting the worker because of a failed job on host hgvmclusteragent1
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	ERROR:__main__:Exiting the worker because of a failed job on host hgvmclusteragent1
WARNING:toil.leader:732fd38e_d585_4405_8d6b_c37a982f1ba5:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 732fd38e_d585_4405_8d6b_c37a982f1ba5 to 0
```

**Comment by hannes-ucsc** [comment]
This is the code that handles the references to the "__main__" module in the pickled data. When you run the user script on the leader __main__ is the user script. On a worker, __main__ is worker.py. I don't know why this is failing though. I would like to know that userModule is at the time this exception is raised. It might be worth trying to remove custom pickling methods and see if that changes anything.

**Comment by adamnovak** [comment]
I've tested it without the custom pickling code. Even if I make my class pickle and unpickle normally, I can't unpickle it on the worker.

**Comment by adamnovak** [comment]
In my old jobTree scripts I would sometimes need to re-import things:

```
# Make sure we've given everything an absolute module name.
# Don't try to import * because that's illegal.
if __name__ == "__main__":
    from compareSchemes import SchemeAssessmentTarget, BedSplitTarget, \
        MafGeneCheckerTarget
```
I tried that here, but Toil seems to be trying to prevent it:

```
Traceback (most recent call last):
  File "./parallelMappingEvaluation.py", line 975, in <module>
    sys.exit(main(sys.argv))
  File "./parallelMappingEvaluation.py", line 962, in main
    cores=16, memory="100G", disk="50G")
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 183, in wrapJobFn
    return JobFunctionWrappingJob(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 995, in __init__
    super(JobFunctionWrappingJob, self).__init__(userFunction, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 964, in __init__
    self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 343, in forModule
    cls._check_conflict(dirPath, name)
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 371, in _check_conflict
    name, colliding_module.__name__, colliding_module.__file__))
RuntimeError: The user module 'parallelMappingEvaluation' collides with module 'parallelMappingEvaluation from '/home/anovak/hgvm/parallelMappingEvaluation.py'.
```

**Comment by hannes-ucsc** [comment]
That's the code that makes sure a user module can only be loaded from one entry on the sys.path. We did this to ensure that someone naming their user script in a way that collides with a module already installed, `test` was a prominent example.

**Comment by hannes-ucsc** [comment]
@adamnovak could you provide the user script?

**Comment by hannes-ucsc** [comment]
I think this is it:

https://github.com/adamnovak/hgvm/blob/a0e9be6f544984cff3b6d8622783de8700ab42f2/parallelMappingEvaluation.py

@adamnovak, let me know if that is wrong. The commit above is the one before the one where you switched from sticking  the IOStore instance in the options instance in the root job.

**Comment by hannes-ucsc** [comment]
I can reproduce this.
