### ISSUE TITLE
Encapsulate does not support return Values

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#444]
Type Error (TypeError: 'NoneType' object has no attribute '__getitem__') when attempting to use the return value from an encapsulated job.

**Comment by hannes-ucsc** [comment]
@benedictpaten will probably want the full stack trace if you still have it.

**Comment by arkal** [comment]
Where do I post it? It's an easily reproducible error.

On Wed, Sep 30, 2015 at 6:59 PM, Hannes Schmidt <notifications@github.com>
wrote:

> @benedictpaten <https://github.com/benedictpaten> will probably want the
> full stack trace if you still have it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/toil/issues/444#issuecomment-144593654>.
>



-- 
Arjun Arkal Rao

PhD Student,
Haussler Lab,
UC Santa Cruz,
USA

aarao@ucsc.edu

**Comment by hannes-ucsc** [comment]
Here in the GH issue. Use triple backticks. 

https://guides.github.com/features/mastering-markdown/#examples

**Comment by arkal** [comment]
Adding the full error trace

```
eduroam-169-233-202-80:Desktop arjun$ python untitled.py /tmp/temp
No handlers could be found for logger "toil.resource"
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.common:Using the single machine batch system
INFO:toil.jobStores.fileJobStore:Jobstore directory is: /tmp/temp
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 40 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 4.
INFO:toil.common:Written the environment for the jobs to the environment file
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/Library/Python/2.7/site-packages', name='toil.job', extension='.pyc').
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/Library/Python/2.7/site-packages', name='toil.job', extension='.pyc').
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/Library/Python/2.7/site-packages', name='toil.job', extension='.pyc').
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/Library/Python/2.7/site-packages', name='toil.job', extension='.pyc').
INFO:toil.leader:Checked batch system has no running jobs and no updated jobs
INFO:toil.leader:Found 1 jobs to start and 0 jobs with successors to run
INFO:toil.leader:Starting the main loop
INFO:toil.batchSystems.singleMachine:Executing command: '/usr/bin/python -E /Library/Python/2.7/site-packages/toil/worker.py /tmp/temp L/g/jobmxyp84'.
WARNING:toil.leader:The job seems to have left a log file, indicating failure: L/g/jobmxyp84
WARNING:toil.leader:Reporting file: L/g/jobmxyp84
WARNING:toil.leader:L/g/jobmxyp84:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:L/g/jobmxyp84:	WARNING:toil.resource:Can't find resource for leader path '/Users/arjun/Desktop/untitled.py'
WARNING:toil.leader:L/g/jobmxyp84:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/arjun/Desktop', name='untitled', extension='.py')
WARNING:toil.leader:L/g/jobmxyp84:	Traceback (most recent call last):
WARNING:toil.leader:L/g/jobmxyp84:	  File "/Library/Python/2.7/site-packages/toil/worker.py", line 241, in main
WARNING:toil.leader:L/g/jobmxyp84:	    jobStore=jobStore)
WARNING:toil.leader:L/g/jobmxyp84:	  File "/Library/Python/2.7/site-packages/toil/job.py", line 892, in _execute
WARNING:toil.leader:L/g/jobmxyp84:	    self._serialiseJobGraph(jobWrapper, jobStore, returnValues, False)
WARNING:toil.leader:L/g/jobmxyp84:	  File "/Library/Python/2.7/site-packages/toil/job.py", line 847, in _serialiseJobGraph
WARNING:toil.leader:L/g/jobmxyp84:	    self._setReturnValuesForPromises(returnValues, jobStore)
WARNING:toil.leader:L/g/jobmxyp84:	  File "/Library/Python/2.7/site-packages/toil/job.py", line 595, in _setReturnValuesForPromises
WARNING:toil.leader:L/g/jobmxyp84:	    argToStore = returnValues[i]
WARNING:toil.leader:L/g/jobmxyp84:	TypeError: 'NoneType' object has no attribute '__getitem__'
WARNING:toil.leader:L/g/jobmxyp84:	Exiting the worker because of a failed job on host Arjuns-MacBook-Pro.local
WARNING:toil.leader:L/g/jobmxyp84:	ERROR:__main__:Exiting the worker because of a failed job on host Arjuns-MacBook-Pro.local
WARNING:toil.leader:L/g/jobmxyp84:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job L/g/jobmxyp84 to 0
WARNING:toil.leader:Job: L/g/jobmxyp84 is completely failed
INFO:toil.leader:Only failed jobs and their dependents (1 total) are remaining, so exiting.
INFO:toil.leader:Finished the main loop
INFO:toil.leader:Waiting for stats and logging collator process to finish
INFO:toil.leader:Stats/logging finished collating in 0.336077928543 seconds
Traceback (most recent call last):
  File "untitled.py", line 94, in <module>
    test_2() # TypeError: 'NoneType' object has no attribute '__getitem__'
  File "untitled.py", line 89, in test_2
    Job.Runner.startToil(F, params)
  File "/Library/Python/2.7/site-packages/toil/job.py", line 361, in startToil
    return mainLoop(config, batchSystem, jobStore, rootJob)
  File "/Library/Python/2.7/site-packages/toil/leader.py", line 505, in mainLoop
    raise FailedJobsException( config.jobStore, totalFailedJobs )
toil.leader.FailedJobsException: The job store '/tmp/temp' contains 1 failed jobs
```
