### ISSUE TITLE
Job.asyncUpdate assigns int to jobWrapper.filesToDelete

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#483]
jobWrapper.filesToDelete should be a list. https://github.com/BD2KGenomics/toil/blob/master/src/toil/job.py#L602
```
#Indicate any files that should be deleted once the update of 
#the job wrapper is completed.
self.jobWrapper.filesToDelete = len(self.filesToDelete)
```
I believe this caused the testAzureSingle crash in this build: http://jenkins.cgcloud.info/job/toil-pull-requests/525/console

**Comment by hannes-ucsc** [comment]
@adderan it looks like that field can be either a list or an int. A little further down below the line you link to it's actually compared as an int and then converted to a list. 

@benedictpaten The console output Alden links to actually has the EOF during unpickle trace that @arkal and I mentioned this morning:

```
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	Traceback (most recent call last):
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/worker.py", line 280, in main
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	    jobStore)._execute( jobWrapper=jobWrapper,
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/job.py", line 758, in _loadJob
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	    return cls._unpickle(userModule, fileHandle)
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/job.py", line 779, in _unpickle
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	    return unpickler.load()
WARNING:toil.leader:268df65c_e77f_4c44_a2bf_5c09e795102a:	EOFError
```

**Comment by adderan** [comment]
Okay, maybe I'm missing something. It seems like this will always leave self.jobWrapper.filesToDelete as an int if len(self.filesToDelete) is zero. And that's what happened here:
```
def clean(self, rootJobWrapper):
        """
            Function to cleanup the state of a jobStore after a restart.
            Fixes jobs that might have been partially updated.
            Resets the try counts.
            Removes jobs that are not successors of the rootJobWrapper.
            """
        #Iterate from the root jobWrapper and collate all jobs that are reachable from it
        #All other jobs returned by self.jobs() are orphaned and can be removed
        reachableFromRoot = set()
        def getConnectedJobs(jobWrapper):
            if jobWrapper.jobStoreID in reachableFromRoot:
                return
            reachableFromRoot.add(jobWrapper.jobStoreID)
            for jobs in jobWrapper.stack:
                for successorJobStoreID in map(lambda x : x[0], jobs):
                    if successorJobStoreID not in reachableFromRoot and self.exists(successorJobStoreID):
                        getConnectedJobs(self.load(successorJobStoreID))
        getConnectedJobs(rootJobWrapper)
    
        #Cleanup the state of each jobWrapper
        for jobWrapper in self.jobs():
            changed = False #Flag to indicate if we need to update the jobWrapper
            #on disk
    
>           if len(jobWrapper.filesToDelete) != 0:
E           TypeError: object of type 'int' has no len()
```
I'm not sure why there's an if statement checking whether len(self.filesToDelete) is greater than zero if that's always required to be true.

**Comment by benedictpaten** [comment]
Alden is correct, this is a bug. I'm assigning to me and putting into my latest fix. I'll close Alden's PR.
