### ISSUE TITLE
Running toil without __main__ check causes it to crash and burn!

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#522]
This example causes Toil to fail:

```
from toil.job import Job

class HelloWorld(Job):
    def __init__(self, message):
        Job.__init__(self,  memory="2G", cores=2, disk="3G")
        self.message = message

    def run(self, fileStore):
        fileStore.logToMaster("Hello, world!, I have a message: %s" % self.message)

options = Job.Runner.getDefaultOptions("./toilWorkflowRun")
options.logLevel = "INFO"
Job.Runner.startToil(HelloWorld("woot"), options)
```

**Comment by hannes-ucsc** [comment]
I think I know why this happens. The worker imports the user script first, then unpickles the job at which time the HelloWorld instance will be deserialized and the HelloWord class will be referenced from the imported script. Without the `__main__` check, you will end up attempting to start another Toil instance in the worker context as soon as you import the user script. Clearly not what you want.

The __main__ check is an essential Python pattern. Everyone™ knows about it and uses it and we shouldn't try to accommodate a sloppy coding style.

Closing.

**Comment by benedictpaten** [comment]
Fair enough, is it possible to print a warning about this case? Currently it's totally inscrutable.

**Comment by hannes-ucsc** [comment]
I think so. Every user-facing Toil API (or at least the job factories and startToil()) would have to check whether it is being invoked during module import. The only way to do this is to set a global variable before the import and unset it after the import. The job factories and startToil() would then check that global variable and raise an exception. We'd have to consider thread-safety, too.

**Comment by DailyDreaming** [comment]
This bug is still alive and confusing:

```
	INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
	INFO:toil:Running Toil version 4.1.0a1-d4c7862832ba1faa2ef89336e8ed251919cefc2b.
	WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/quokka/toil', name='example', fromVirtualEnv=False).
	Traceback (most recent call last):
	  File "/home/quokka/toil/src/toil/jobStores/fileJobStore.py", line 104, in initialize
	    os.mkdir(self.jobStoreDir)
	FileExistsError: [Errno 17] File exists: '/home/quokka/toil/toilWorkflowRun'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/home/quokka/toil/src/toil/worker.py", line 350, in workerScript
	    job = Job._loadJob(jobGraph.command, jobStore)
	  File "/home/quokka/toil/src/toil/job.py", line 914, in _loadJob
	    userModule = cls._loadUserModule(userModule)
	  File "/home/quokka/toil/src/toil/job.py", line 891, in _loadUserModule
	    return userModule.load()
	  File "/home/quokka/toil/src/toil/resource.py", line 611, in load
	    return importlib.import_module(module.name)
	  File "/home/quokka/toil/v3nv/lib/python3.6/importlib/__init__.py", line 126, in import_module
	    return _bootstrap._gcd_import(name[level:], package, level)
	  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
	  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
	  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
	  File "/home/quokka/toil/example.py", line 13, in <module>
	    Job.Runner.startToil(HelloWorld("woot"), options)
	  File "/home/quokka/toil/src/toil/job.py", line 789, in startToil
	    with Toil(options) as toil:
	  File "/home/quokka/toil/src/toil/common.py", line 740, in __enter__
	    jobStore.initialize(config)
	  File "/home/quokka/toil/src/toil/jobStores/fileJobStore.py", line 107, in initialize
	    raise JobStoreExistsException(self.jobStoreDir)
	toil.jobStores.abstractJobStore.JobStoreExistsException: The job store '/home/quokka/toil/toilWorkflowRun' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
	ERROR:toil.worker:Exiting the worker because of a failed job on host qcore
	WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'HelloWorld' kind-HelloWorld/instance-8tnqpt_g with ID kind-HelloWorld/instance-8tnqpt_g to 0
```
