### ISSUE TITLE
Job constructor doesn't seem to accept cache as keyword argument

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#528]
As mentioned in the title, passing cache as a keyword argument to Job.wrapJobFn() does not work.
TOY CODE
```
#!/usr/bin/env python2.7
'''
Author : Arjun Arkal Rao
Affiliation : UCSC BME, UCSC Genomics Institute
File : toy_code_for_keyword_cache.py
'''
from __future__ import print_function
from toil.job import Job

import argparse
import time
import os


def f(job, test_val):
    '''
    This is a completely useless function.  It's only task is to be a called as
    a job by the test
    '''
    return None


def test_pass_disk_lt_cache():
    '''
    Try to run a job by not passing cache, but passing disk < 2GB (default value
    of cache).  This shows that the code has implemented the cache logic and the
    only problem is with the initializaton of the job.
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('--dummy', dest='dummy', default=None, required=False)
    Job.Runner.addToilOptions(parser)
    params = parser.parse_args()
    F = Job.wrapJobFn(f, memory='15G', cores=5, disk='1G')
    Job.Runner.startToil(F, params)


def test_pass_cache_val():
    '''
    Try to run a job by passing cache as a named keyword argument in the
    constructor.  This fails and shows that the constructor does not accept
    the keyword argument.
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('--dummy', dest='dummy', default=None, required=False)
    Job.Runner.addToilOptions(parser)
    params = parser.parse_args()
    F = Job.wrapJobFn(f, memory='15G', cores=5, disk='10G', cache='2G')
    Job.Runner.startToil(F, params)

if __name__ == '__main__':
    test_pass_disk_lt_cache()  # This will FAIL
    test_pass_cache_val()  # This will PASS
```
STACK TRACE FOR ```test_pass_disk_lt_cache()```
```
[centos@arjun-fake-podk ~]$ python /data/test_docker/toil_tests/toy_code_for_keyword_cache.py /data1/temp_dir/temp
No handlers could be found for logger "toil.resource"
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.common:Using the single machine batch system
INFO:toil.jobStores.fileJobStore:Jobstore directory is: /data1/temp_dir/temp
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (8).
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 80 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 8.
INFO:toil.common:Written the environment for the jobs to the environment file
Traceback (most recent call last):
  File "/data/test_docker/toil_tests/toy_code_for_keyword_cache.py", line 51, in <module>
    test_pass_disk_lt_cache()  # This will FAIL
  File "/data/test_docker/toil_tests/toy_code_for_keyword_cache.py", line 34, in test_pass_disk_lt_cache
    Job.Runner.startToil(F, params)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 371, in startToil
    rootJob = job._serialiseFirstJob(jobStore)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1139, in _serialiseFirstJob
    predecessorNumber=0)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 998, in _createEmptyJobForJob
    " than the disk requirement for the job! (disk: %s)" % (cache, disk))
RuntimeError: Trying to allocate a cache (cache: 2147483648.0) larger than the disk requirement for the job! (disk: 1073741824)
```
Which is as expected since disk < cache. However, you cannot provide a different value for cache as shown in ```test_pass_cache_val()```
```
[centos@arjun-fake-podk ~]$ python /data/test_docker/toil_tests/toy_code_for_keyword_cache.py /data1/temp_dir/temp
No handlers could be found for logger "toil.resource"
INFO:toil.lib.bioio:Logging set at level: INFO
INFO:toil.common:Using the single machine batch system
INFO:toil.jobStores.fileJobStore:Jobstore directory is: /data1/temp_dir/temp
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (8).
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 80 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 8.
INFO:toil.common:Written the environment for the jobs to the environment file
WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/data/test_docker/toil_tests', name='toy_code_for_keyword_cache', extension='.py').
INFO:toil.leader:Checked batch system has no running jobs and no updated jobs
INFO:toil.leader:Found 1 jobs to start and 0 jobs with successors to run
INFO:toil.leader:Starting the main loop
INFO:toil.batchSystems.singleMachine:Executing command: '/usr/local/bin/python -E /usr/local/lib/python2.7/site-packages/toil/worker.py /data1/temp_dir/temp h/P/jobDI_hwW'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 414, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 414, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting

Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method FileStore.__del__ of <toil.job.FileStore object at 0x7f3dbebefa50>> ignored
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: h/P/jobDI_hwW
WARNING:toil.leader:Reporting file: h/P/jobDI_hwW
WARNING:toil.leader:h/P/jobDI_hwW:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:h/P/jobDI_hwW:	WARNING:toil.resource:Can't find resource for leader path '/data/test_docker/toil_tests/toy_code_for_keyword_cache.py'
WARNING:toil.leader:h/P/jobDI_hwW:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/data/test_docker/toil_tests', name='toy_code_for_keyword_cache', extension='.py')
WARNING:toil.leader:h/P/jobDI_hwW:	WARNING:toil.resource:Can't find resource for leader path '/data/test_docker/toil_tests/toy_code_for_keyword_cache.py'
WARNING:toil.leader:h/P/jobDI_hwW:	WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/data/test_docker/toil_tests', name='toy_code_for_keyword_cache', extension='.py')
WARNING:toil.leader:h/P/jobDI_hwW:	Traceback (most recent call last):
WARNING:toil.leader:h/P/jobDI_hwW:	  File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 288, in main
WARNING:toil.leader:h/P/jobDI_hwW:	    fileStore=fileStore)
WARNING:toil.leader:h/P/jobDI_hwW:	  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1164, in _execute
WARNING:toil.leader:h/P/jobDI_hwW:	    returnValues = self.run(fileStore)
WARNING:toil.leader:h/P/jobDI_hwW:	  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1249, in run
WARNING:toil.leader:h/P/jobDI_hwW:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:h/P/jobDI_hwW:	TypeError: f() got an unexpected keyword argument 'cache'
WARNING:toil.leader:h/P/jobDI_hwW:	Exiting the worker because of a failed jobWrapper on host arjun-fake-podk.novalocal
WARNING:toil.leader:h/P/jobDI_hwW:	ERROR:__main__:Exiting the worker because of a failed jobWrapper on host arjun-fake-podk.novalocal
WARNING:toil.leader:h/P/jobDI_hwW:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job h/P/jobDI_hwW to 0
WARNING:toil.leader:Job: h/P/jobDI_hwW is completely failed
INFO:toil.leader:Only failed jobs and their dependents (1 total) are remaining, so exiting.
INFO:toil.leader:Finished the main loop
INFO:toil.leader:Waiting for stats and logging collator process to finish
INFO:toil.leader:Stats/logging finished collating in 0.268598079681 seconds
Traceback (most recent call last):
  File "/data/test_docker/toil_tests/toy_code_for_keyword_cache.py", line 52, in <module>
    test_pass_cache_val()  # This will PASS
  File "/data/test_docker/toil_tests/toy_code_for_keyword_cache.py", line 48, in test_pass_cache_val
    Job.Runner.startToil(F, params)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 372, in startToil
    return mainLoop(config, batchSystem, jobStore, rootJob)
  File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 505, in mainLoop
    raise FailedJobsException( config.jobStore, totalFailedJobs )
toil.leader.FailedJobsException: The job store '/data1/temp_dir/temp' contains 1 failed jobs
```

**Comment by arkal** [comment]
Cool. Thanks!

**Comment by hannes-ucsc** [comment]
This is a little confusing since no value for `f()`'s `test_val` argument is being provided. IOW, both scenarios are always going to fail, just for different reasons. It would have been helpful if the test script passed when running against a version of Toil that fixes the problem. However, given the fact that Benedict says that the issue is fixed and that I cannot get the `TypeError: f() got an unexpected keyword argument 'cache'` exception anymore when running either of the scenarios, I am assuming this is indeed fixed.
