### ISSUE TITLE
Can't specify disk requirement without specifying cache also

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#551]
Running the following user script

```
import sys
from toil.job import Job

def hello( name ):
    return "Hello, %s!" % name

if __name__ == '__main__':
    options = Job.Runner.getDefaultArgumentParser().parse_args()
    job = Job.wrapFn( hello, "world", cores=1, memory=1e6, disk=1e6 )
    result = Job.Runner.startToil( job, options )
    assert result == 'Hello, world!'
```

using this command line

```
python2.7 hello_world.py ./foo
```

Produces the following exception.

```
Traceback (most recent call last):
  File "hello_world.py", line 10, in <module>
    result = Job.Runner.startToil( job, options )
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 436, in startToil
    rootJob = job._serialiseFirstJob(jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1246, in _serialiseFirstJob
    predecessorNumber=0)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1104, in _createEmptyJobForJob
    " than the disk requirement for the job! (disk: %s)" % (cache, disk))
RuntimeError: Trying to allocate a cache (cache: 2147483648.0) larger than the disk requirement for the job! (disk: 1000000)
```

The user shouldn't need to specify cache. It should have a sensible default derived from the disk requirement.

**Comment by hannes-ucsc** [comment]
Adding `cache=1e6` prevents the exception.

**Comment by arkal** [comment]
Maybe modifying [these two lines in job.py](https://github.com/BD2KGenomics/toil/blob/master/src/toil/job.py#L1099-L1100) to
```
cache=(self.cache if self.cache is not None
              else min(float(jobStore.config.defaultCache), disk))
```
will help?

I.e. if cache isn't provided, use the lower of disk, and default cache.
