### ISSUE TITLE
Imported files in the same directory as the user script not available on Mesos nodes

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#565]
I have a particular user script that imports my own library code I have written for running on Toil, called `toillib.py`, which I keep in the same directory as the user script. I import it thusly:

```
from toillib import *
```

On the master, my script can import `toillib.py` just fine, but when running on Mesos on Azure, when there is no shared filesystem and Mesos has to take care of copying the user script out to the nodes, `toillib.py` appears to be missing when the workers start up:

```
INFO:toil.batchSystems.mesos.batchSystem:Preparing to launch Mesos task 0 using offer 20151120-222317-83886090-5050-35148-O5...
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 0
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: 46c1efec_0849_4ce3_b74d_c74f1f0602a4
WARNING:toil.leader:Reporting file: 46c1efec_0849_4ce3_b74d_c74f1f0602a4
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       ---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       Traceback (most recent call last):
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 
266, in main
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:           job = Job._loadJob(jobWrapper.command, jobStore)
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 936, in _loadJob
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:           userModule = cls._loadUserModule(userModule)
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 914, in _loadUserModule
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:           return importlib.import_module(userModule.name)
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:         File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:           __import__(name)
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:         File "/tmp/tmpflu3Jl/5b3f3d5ba2a95124e308998df2ab7bb2/parallelMappingEvaluation.py", line 16, in <module>
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:           from toillib import *
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       ImportError: No module named toillib
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       Exiting the worker because of a failed jobWrapper on host c4agent1
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host c4agent1
WARNING:toil.leader:46c1efec_0849_4ce3_b74d_c74f1f0602a4:       WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 46c1efec_0849_4ce3_b74d_c74f1f0602a4 to 0
WARNING:toil.leader:Job: 46c1efec_0849_4ce3_b74d_c74f1f0602a4 is completely failed
```

Imported files in the same directory are supposed to be brought along by the resource system and be accessible on the workers, right?

**Comment by hannes-ucsc** [comment]
Yes. But we may have to help Toil a little bit. I needs to recognize that the user script and the imported module are part of a package hierarchy and it needs to be able to identify the hierarchy. Can you send an `ls -lR` of your working directory on the leader? I will work on replicating this issue.

**Comment by hannes-ucsc** [comment]
s/identify the hierarchy/identify the root of the hierarchy/

**Comment by adamnovak** [comment]
This is what it looks like:

```
anovak@c4master1:~/hgvm-graph-bakeoff-evalutations$ ls -lr
total 112
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:32 vg_graphs
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:52 scripts
-rw-rw-r-- 1 anovak anovak    15 Nov 20 22:32 requirements.txt
-rw-rw-r-- 1 anovak anovak  7205 Nov 20 22:32 README.md
-rw-rw-r-- 1 anovak anovak 51746 Nov 20 23:10 log.txt
-rw-rw-r-- 1 anovak anovak  1106 Nov 20 22:32 LICENSE
-rw-rw-r-- 1 anovak anovak     0 Nov 20 22:32 __init__.py
-rw-rw-r-- 1 anovak anovak  8817 Nov 20 22:32 graph_servers.tsv
-rw-rw-r-- 1 anovak anovak  8823 Nov 20 22:32 graph_servers_high_coverage.tsv
-rw-rw-r-- 1 anovak anovak  7050 Nov 20 22:34 graph_servers_azure.tsv
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:32 data
anovak@c4master1:~/hgvm-graph-bakeoff-evalutations$ ls -lR
.:
total 112
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:32 data
-rw-rw-r-- 1 anovak anovak  7050 Nov 20 22:34 graph_servers_azure.tsv
-rw-rw-r-- 1 anovak anovak  8823 Nov 20 22:32 graph_servers_high_coverage.tsv
-rw-rw-r-- 1 anovak anovak  8817 Nov 20 22:32 graph_servers.tsv
-rw-rw-r-- 1 anovak anovak     0 Nov 20 22:32 __init__.py
-rw-rw-r-- 1 anovak anovak  1106 Nov 20 22:32 LICENSE
-rw-rw-r-- 1 anovak anovak 51746 Nov 20 23:10 log.txt
-rw-rw-r-- 1 anovak anovak  7205 Nov 20 22:32 README.md
-rw-rw-r-- 1 anovak anovak    15 Nov 20 22:32 requirements.txt
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:52 scripts
drwxrwxr-x 2 anovak anovak  4096 Nov 20 22:32 vg_graphs

./data:
total 15484
-rw-rw-r-- 1 anovak anovak 15803376 Nov 20 22:32 alignments.tar.gz
-rw-rw-r-- 1 anovak anovak    46913 Nov 20 22:32 genes.tar.gz

./scripts:
total 372
-rwxrwxr-x 1 anovak anovak  9930 Nov 20 22:32 barchart.py
-rwxrwxr-x 1 anovak anovak 19631 Nov 20 22:32 boxplot.py
-rwxrwxr-x 1 anovak anovak   403 Nov 20 22:32 call_snps.sh
-rwxrwxr-x 1 anovak anovak 13592 Nov 20 22:32 callVariants.py
-rwxrwxr-x 1 anovak anovak 12824 Nov 20 22:32 clusterGraphs.py
-rwxrwxr-x 1 anovak anovak  9026 Nov 20 22:32 collateStatistics.py
-rwxrwxr-x 1 anovak anovak 19840 Nov 20 22:32 compareCalls.py
-rwxrwxr-x 1 anovak anovak   465 Nov 20 22:32 compare_graphs.sh
-rwxrwxr-x 1 anovak anovak  2671 Nov 20 22:32 compare_snps.sh
-rwxrwxr-x 1 anovak anovak 32025 Nov 20 22:32 getAltReads.py
-rwxrwxr-x 1 anovak anovak 27144 Nov 20 22:32 graphEval.py
-rw-rw-r-- 1 anovak anovak 10164 Nov 20 22:32 heatmap.py
-rwxrwxr-x 1 anovak anovak 18029 Nov 20 22:32 histogram.py
-rw-rw-r-- 1 anovak anovak     0 Nov 20 22:32 __init__.py
-rwxrwxr-x 1 anovak anovak  5890 Nov 20 22:32 parallelAzureDownloader.py
-rwxrwxr-x 1 anovak anovak 46598 Nov 20 22:52 parallelMappingEvaluation.py
-rwxrwxr-x 1 anovak anovak  5232 Nov 20 22:32 plotMappingEvaluation.sh
-rwxrwxr-x 1 anovak anovak  5254 Nov 20 22:32 presplots.sh
-rwxrwxr-x 1 anovak anovak  3322 Nov 20 22:32 redoStats.py
-rwxrwxr-x 1 anovak anovak 13278 Nov 20 22:32 scatter.py
-rwxrwxr-x 1 anovak anovak 14199 Nov 20 22:32 smartSam2Fastq.py
-rwxrwxr-x 1 anovak anovak   959 Nov 20 22:32 toilAzureCleanup.sh
-rw-rw-r-- 1 anovak anovak 25245 Nov 20 22:32 toillib.py
-rw-rw-r-- 1 anovak anovak 21136 Nov 20 22:39 toillib.pyc
-rwxrwxr-x 1 anovak anovak   159 Nov 20 22:32 vcfCountSnps.sh
-rwxrwxr-x 1 anovak anovak   243 Nov 20 22:32 vgHasPath.sh

./vg_graphs:
total 4
-rwxrwxr-x 1 anovak anovak 767 Nov 20 22:32 make_graphs.sh
```

It may be relevant that I'm running my script as `scripts/parallelMappingEvaluation.py`, and it's importing `toillib.py` next to the executing file, but not directly from the working directory.

**Comment by hannes-ucsc** [comment]
Try running the script as `PYTHONPATH=. python -m scripts.parallelMappingEvaluation` and changing the import to `from scripts.toillib import *`

**Comment by hannes-ucsc** [comment]
I can reproduce this. The above workaround doesn't seem to work. Stay tuned.

**Comment by hannes-ucsc** [comment]
@adamnovak, once this lands on master you will need to remove the `__init__.py` from the scripts directory. After that it should work.
