### ISSUE TITLE
Occasional KeyError during testJobFileStoreWithSmallCache

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#582]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/77/testReport/junit/src.toil.test.src.jobFileStoreTest/JobFileStoreTest/testJobFileStoreWithSmallCache/

```
Exception in thread Thread-13:
WARNING:toil.leader:t/V/job0sJG0Z:	Traceback (most recent call last):
WARNING:toil.leader:t/V/job0sJG0Z:	  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
WARNING:toil.leader:t/V/job0sJG0Z:	    self.run()
WARNING:toil.leader:t/V/job0sJG0Z:	  File "/usr/lib/python2.7/threading.py", line 763, in run
WARNING:toil.leader:t/V/job0sJG0Z:	    self.__target(*self.__args, **self.__kwargs)
WARNING:toil.leader:t/V/job0sJG0Z:	  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/job.py", line 506, in asyncWrite
WARNING:toil.leader:t/V/job0sJG0Z:	    self._lockFiles.remove(jobStoreFileID)
WARNING:toil.leader:t/V/job0sJG0Z:	KeyError: 'I/O/tmpOiPrLG.tmp'
```

**Comment by hannes-ucsc** [comment]
Duplicated by #596.
