### ISSUE TITLE
Caching test fails sporadically

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#596]
http://jenkins.cgcloud.info/job/toil-pull-requests/696/testReport/junit/src.toil.test.src.jobFileStoreTest/JobFileStoreTest/testJobFileStoreWithOverLargeCache/

```
WARNING:toil.leader:f/7/jobgTdQ0l:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:f/7/jobgTdQ0l:	Exception in thread Thread-1:
WARNING:toil.leader:f/7/jobgTdQ0l:	Traceback (most recent call last):
WARNING:toil.leader:f/7/jobgTdQ0l:	  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
WARNING:toil.leader:f/7/jobgTdQ0l:	    self.run()
WARNING:toil.leader:f/7/jobgTdQ0l:	  File "/usr/lib/python2.7/threading.py", line 763, in run
WARNING:toil.leader:f/7/jobgTdQ0l:	    self.__target(*self.__args, **self.__kwargs)
WARNING:toil.leader:f/7/jobgTdQ0l:	  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/job.py", line 505, in asyncWrite
WARNING:toil.leader:f/7/jobgTdQ0l:	    self._lockFiles.remove(jobStoreFileID)
WARNING:toil.leader:f/7/jobgTdQ0l:	KeyError: 'w/I/tmp82Zvk4.tmp'
```

**Comment by hannes-ucsc** [comment]
Duplicates #582.
