### ISSUE TITLE
Toil script as a program generates assertion

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#631]
Take and example Toil program from the documentation, turn it into a python program `tryIt', with 
 
    #!/usr/bin/env python

as the first line.
  
     ./tryIt   
    Traceback (most recent call last):  
      File "./tryIt", line 10, in <module>  
        j1 = Job.wrapJobFn(helloWorld, "first")  
      File "/cluster/home/markd/opt/centos6.0/x86_64/lib/python2.7/site-packages/toil/job.py", line 238, in wrapJobFn  
        return JobFunctionWrappingJob(fn, *args, **kwargs)  
      File "/cluster/home/markd/opt/centos6.0/x86_64/lib/python2.7/site-packages/toil/job.py", line 1350, in __init__  
        self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()  
      File "/cluster/home/markd/opt/centos6.0/x86_64/lib/python2.7/site-packages/toil/resource.py", line 331, in forModule  
        assert extension in ('.py', '.pyc')  
    AssertionError

**Comment by hannes-ucsc** [comment]
Close was erratic. 

We need to change the assertion into a RuntimeException indicating a user error.

**Comment by hannes-ucsc** [comment]
Would be obsoleted by #858.
