### ISSUE TITLE
No log file is present, despite jobWrapper failing

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil#657]
I get this error, but not consistently.
Specifically, I'm trying to figure out why my docker container doesn't change ownership of its output files. Last time I ran [my launch script](http://hgwdev.cse.ucsc.edu/~jeltje/toil/launch_zygosity_hg19_mesos.sh) calling [my python wrapper] (http://hgwdev.cse.ucsc.edu/~jeltje/toil/toil_adtex_zygosity.py), it died with a 'cannot remove file' complaint:
```
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       [1] "Plotting results..."
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       Sat Jan 23 03:25:10 UTC 2016
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       Estimating base ploidy...
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       Predicting Zygosity states
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       Traceback (most recent call last):
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 269, in main
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           cleanCacheFn(job.effectiveRequirements(jobStore.config).cache)
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 814, in _cleanLocalTempDir
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           clean(self.localTempDir, False)
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 806, in clean
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           canRemove = canRemove and clean(os.path.join(dirOrFile, f))
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 806, in clean
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           canRemove = canRemove and clean(os.path.join(dirOrFile, f))
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 806, in clean
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           canRemove = canRemove and clean(os.path.join(dirOrFile, f))
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 812, in clean
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:           os.remove(dirOrFile)
WARNING:toil.leader:9d7c7463-5b1b-4b83-9b78-7f526778e7f0:       OSError: [Errno 13] Permission denied: '/var/lib/toil/tmpEHlJg3/localTempDir/tQVWW0D/DTB_005_BL_T.adtex_out/chrchr9.png'
```
What's weird here is that I'm not getting the final STDOUT message from the container, which is a timestamp (after `Predicting Zygosity states`). The docker container is removing files after use (using rm), but I don't expect any errors there to be passed to the toil system.

I shut the cluster down for the weekend and retried today. Instead of getting the same error about not being able to remove a file, I now get [this log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log2):

```
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 5
WARNING:toil.batchSystems.mesos.batchSystem:Task 5 failed with exit status 1
WARNING:toil.leader:Batch system is reporting that the jobWrapper with batch system ID: 5 and jobWrapper store ID: d24e87f9-a4b4-470b-8bb8-ee4d82d90bed failed with exit value 1
WARNING:toil.leader:No log file is present, despite jobWrapper failing: d24e87f9-a4b4-470b-8bb8-ee4d82d90bed
WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job d24e87f9-a4b4-470b-8bb8-ee4d82d90bed to 0
WARNING:toil.leader:Job: d24e87f9-a4b4-470b-8bb8-ee4d82d90bed is completely failed
INFO:toil.leader:Only failed jobs and their dependents (1 total) are remaining, so exiting.
```
Very unhelpful!
Also, some of the input files have been deleted, despite my --clean=never flag. So I can't rerun on the worker to see what's wrong.

```
 pip list
apt-xapian-index (0.45)
bd2k-python-lib (1.10.dev6)
boto (2.38.0)
cffi (1.3.1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
google-common (0.0.1)
html5lib (0.999)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
mesos (0.25.0)
mesos.interface (0.25.0)
oauth (1.0.1)
PAM (0.4.2)
pip (7.1.2)
prettytable (0.7.2)
protobuf (2.6.1)
psutil (3.0.1)
pycparser (2.14)
pycurl (7.19.3)
PyNaCl (0.3.0)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
s3am (1.0b1.dev30)
setuptools (18.7.1)
six (1.5.2)
ssh-import-id (3.21)
toil (3.1.0b1.dev82)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
zope.interface (4.0.5)
You are using pip version 7.1.2, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by hannes-ucsc** [comment]
Regarding the `leader:No log file is present, despite jobWrapper failing` error. Search /tmp on the worker for files named `stderr` or `stdout`. They'll be at paths like `/tmp/mesos/slaves/3eb31dbe-e865-42e8-b4a6-21dcc21d78fb-S0/frameworks/3eb31dbe-e865-42e8-b4a6-21dcc21d78fb-0002/executors/toil-25020/runs/latest` and will contain worker.py output made before worker.py had a chance to setup the log redirection that would cause output to be printed on the leader, as part of the user script output.

**Comment by Jeltje** [comment]
That is helpful info. The worker's /tmp files must have been deleted when I stopped the cluster, because I couldn't find them after restart. I'll be looking for them next time.

Yes, I do have a problem with my wrapper.sh script, which I was trying to figure out. Not getting the full output from the docker container made it look like the container itself crashed. So knowing to look for files on the worker helps with that.

Why is the clean=never flag not working in this case?

**Comment by hannes-ucsc** [comment]
See #662 for preventing the cleanup of the Toil work directory.
