### ISSUE TITLE
Nonetype object has no attribute "terminate"

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#661]
An exception generated on interpreter shutdown while running SortTest. Seems benign but the exception should still be either avoided, caught, or documented. See http://stackoverflow.com/questions/1745232/solving-thread-cleanup-on-paramiko for more on this exception

**Comment by hannes-ucsc** [comment]
@cket, can you provide more info? I can only vaguely remember what this one was about.

**Comment by cket** [comment]
Updated the description with more details

**Comment by cket** [comment]
Better explanation found here: http://stackoverflow.com/questions/20596918/python-exception-in-thread-thread-1-most-likely-raised-during-interpreter-shutd

This is caused by our badWorker daemon thread. Seemingly dependent on what stage of shutdown the interpreter is in, we will get either get a traceback for this error or just a printed statement informing us there was an error.

Traceback:
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
  File "/Users/cj/toil/src/toil/worker.py", line 102, in badWorker
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'kill'
```
Unhelpful printed message:
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
```

Changing badWorker to a non daemon thread appears to fix the problem
