### ISSUE TITLE
CWL toil workflow input file name collision

### ISSUE THREAD

**Issue by kellrott** [BD2KGenomics/toil#728]
If two inputs to a cwl workflow step have the same name there will be a collision, for example:
```
2016-03-30 23:49:00,930 WARNING:toil.leader: f/z/jobmQtiTU:	---TOIL WORKER OUTPUT LOG---
2016-03-30 23:49:00,930 WARNING:toil.leader: f/z/jobmQtiTU:	INFO:rdflib:RDFLib Version: 4.2.1
2016-03-30 23:49:00,930 WARNING:toil.leader: f/z/jobmQtiTU:	INFO:toil.jobStores.fileJobStore:Jobstore directory is: /Users/ellrott/workspaces/mc3_cwl/test_workflow/test_store
2016-03-30 23:49:00,930 WARNING:toil.leader: f/z/jobmQtiTU:	Traceback (most recent call last):
2016-03-30 23:49:00,930 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/worker.py", line 283, in main
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    fileStore=fileStore)
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/job.py", line 1298, in _execute
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    returnValues = self.run(fileStore)
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/cwl/cwltoil.py", line 213, in run
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    adjustFiles(cwljob, lambda x: getFile(fileStore, inpdir, *x, index=index))
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/cwltool/process.py", line 139, in adjustFiles
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    adjustFiles(rec[d], op)
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/cwltool/process.py", line 137, in adjustFiles
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    rec["path"] = op(rec["path"])
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/cwl/cwltoil.py", line 213, in <lambda>
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    adjustFiles(cwljob, lambda x: getFile(fileStore, inpdir, *x, index=index))
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	  File "/Users/ellrott/workspaces/mc3_cwl/venv/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/cwl/cwltoil.py", line 123, in getFile
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	    raise Exception("Conflicting filesStoreID %s and %s both trying to link to %s" % (index.get(dstPath, None), fileStoreID, dstPath))
2016-03-30 23:49:00,931 WARNING:toil.leader: f/z/jobmQtiTU:	Exception: Conflicting filesStoreID n/1/tmpxw47b3.tmp and L/C/tmpCnIrNm.tmp both trying to link to /Users/ellrott/workspaces/mc3_cwl/test_workflow/tmpzJ7dNP/localTempDir/tn7MTGE/inp/out.txt
```

Example Workflow (works in cwltool, fails in cwltoil):
```
- class: CommandLineTool
  id: "#echo"
  inputs:
    - id: text
      type: string
      inputBinding: {}

  outputs:
    - id: "fileout"
      type: File
      outputBinding:
        glob: out.txt

  baseCommand: echo
  stdout: out.txt

- class: CommandLineTool
  id: "#cat"
  inputs:
    - id: file1
      type: File
      inputBinding:
        position: 1
    - id: file2
      type: File
      inputBinding:
        position: 2

  outputs:
    - id: "fileout"
      type: File
      outputBinding:
        glob: out.txt

  baseCommand: cat
  stdout: out.txt

- class: Workflow
  id: "#collision"

  inputs:
    - id: "#input_1"
      type: string
      
    - id: "#input_2"
      type: string
  
  outputs:
    - id: "#fileout"
      type: File
      source: "#cat_step.fileout"

  steps:
    - id: "#echo_1"
      run: "#echo"
      inputs:
        - id: "#echo_1.text"
          source: "#input_1"
      outputs:
        - id: "#echo_1.fileout"
    
    - id: "#echo_2"
      run: 
        import: "#echo"
      inputs:
        - id: "#collision.echo_2.text"
          source: "#input_2"
      outputs:
        - id: "#echo_2.fileout"
    
    - id: "#cat_step"
      run: 
        import: "#cat"
      inputs:
        - id: file1
          source: "#echo_1.fileout"
        - id: file2
          source: "#echo_2.fileout"
      outputs:
        - id: "#cat_step.fileout"
```

Sample input:
```
{
  "input_1" : "Hello World",
  "input_2" : "How are you?"
}
```

**Comment by tetron** [comment]
Hi @kellrott, thanks I'll take a look at it.  It should probably stage each input file to separate directory to avoid name conflicts like that.
