### ISSUE TITLE
ImportError: No module named mesos.interface

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#773]
Trying to run cwltoil with --batchSystem=mesos

```
(blurb) mesosbox@ip-172-31-27-16:~/common-workflow-language/draft-3/examples$ cwltoil --batchSystem=mesos example-1st.cwl example-echo-job.json 
INFO:toil.lib.bioio:Logging set at level: INFO
Traceback (most recent call last):
  File "/home/mesosbox/blurb/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/home/mesosbox/blurb/local/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 459, in main
    Job.Runner.startToil(staging, options)
  File "/home/mesosbox/blurb/local/lib/python2.7/site-packages/toil/job.py", line 422, in startToil
    with setupToil(options, userScript=job.getUserScript()) as (config, batchSystem, jobStore):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mesosbox/blurb/local/lib/python2.7/site-packages/toil/common.py", line 450, in setupToil
    batchSystemClass, kwargs = loadBatchSystemClass(config)
  File "/home/mesosbox/blurb/local/lib/python2.7/site-packages/toil/common.py", line 375, in loadBatchSystemClass
    from toil.batchSystems.mesos.batchSystem import MesosBatchSystem
  File "/home/mesosbox/blurb/local/lib/python2.7/site-packages/toil/batchSystems/mesos/batchSystem.py", line 25, in <module>
    import mesos.interface
ImportError: No module named mesos.interface
```

**Comment by tetron** [comment]
I think extras_require needs to include the `mesos.interface` package under the `mesos` option.

**Comment by tetron** [comment]
On further research, I see that the mesos packages can't be installed from PyPi, are are present on the cgcloud toil box.  So not a bug, although better error handling (catch ImportError and print something out telling you what to do) would be nice.

**Comment by arkal** [comment]
Did you setup the env blurb with --system-site-packages?

**Comment by hannes-ucsc** [comment]
This section covers this more or less:

http://toil.readthedocs.org/en/releases-3.1.x/essentials.html#running-mesos-tests

Should it be reworded? I also like the idea of catching the import error and printing something useful.
