### ISSUE TITLE
Not running mesos tasks on cluster created with cgcloud

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#775]
I created a cluster with a single worker node using cgcloud:

```
$ cgcloud create-cluster toil -z us-west-2a -s 1 -t t2.medium
```

I logged in, cloned the common-workflow-language and cwltool repositories.  Running `cwltoil` with the `singleMachine` batch system works fine.  Running the same CWL with `--batchSystem=mesos` seems to queue the next but it never runs:

```
ubuntu@ip-172-31-27-173:~/common-workflow-language/draft-3/examples$ cwltoil --batchSystem=mesos --logDebug example-1st.cwl example-echo-job.json 
2016-04-10 18:41:52,522 INFO:toil.lib.bioio: Logging set at level: DEBUG
2016-04-10 18:41:52,523 INFO:toil.jobStores.fileJobStore: Jobstore directory is: /tmp/tmpwARd4F
2016-04-10 18:41:52,524 INFO:toil.jobStores.abstractJobStore: The workflow ID is: 'cbff3da1-ddaa-4876-91b5-84e70495632c'
2016-04-10 18:41:52,596 INFO:toil.common: Using the mesos batch system
I0410 18:41:52.600785  3446 sched.cpp:164] Version: 0.25.0
2016-04-10 18:41:52,600 INFO:toil.realtimeLogger: Real-time logging disabled
2016-04-10 18:41:52,601 INFO:toil.common: Written the environment for the jobs to the environment file
2016-04-10 18:41:52,601 INFO:toil.common: Caching all jobs in job store
2016-04-10 18:41:52,601 INFO:toil.common: 0 jobs downloaded.
I0410 18:41:52.602980  3451 sched.cpp:262] New master detected at master@127.0.0.1:5050
I0410 18:41:52.603107  3451 sched.cpp:272] No credentials provided. Attempting to register without authentication
E0410 18:41:52.603288  3457 socket.hpp:174] Shutdown failed on fd=8: Transport endpoint is not connected [107]
2016-04-10 18:41:52,622 INFO:toil.leader: (Re)building internal scheduler state
2016-04-10 18:41:52,622 DEBUG:toil.leader: Found job to run: 9/h/jobdJ0HfU, with command: True, with checkpoint: False,  with services: False, with stack: False
2016-04-10 18:41:52,623 INFO:toil.leader: Checked batch system has no running jobs and no updated jobs
2016-04-10 18:41:52,623 INFO:toil.leader: Found 1 jobs to start and 0 jobs with successors to run
2016-04-10 18:41:52,625 INFO:toil.leader: Starting the main loop
2016-04-10 18:41:52,625 DEBUG:toil.leader: Built the jobs list, currently have 1 jobs to update and 0 jobs issued
2016-04-10 18:41:52,625 DEBUG:toil.leader: Updating status of job: 9/h/jobdJ0HfU with result status: 0
2016-04-10 18:41:52,625 DEBUG:toil.batchSystems.mesos.batchSystem: Queueing the job command: _toil_worker /tmp/tmpwARd4F 9/h/jobdJ0HfU with job id: 0 ...
2016-04-10 18:41:52,625 DEBUG:toil.batchSystems.mesos.batchSystem: ... queued
2016-04-10 18:41:52,625 DEBUG:toil.leader: Issued job with job store ID: 9/h/jobdJ0HfU and job batch system ID: 0 and cores: 1, disk: 2147483648, and memory: 2147483648
E0410 18:41:54.153369  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:41:55.328963  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:41:56.247306  3456 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:42:10.097009  3454 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:42:33.190450  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:42:36.142798  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:43:03.099294  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:44:02.342994  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:44:44.859886  3449 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:44:57.523871  3453 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:45:25.977593  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:46:17.942131  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:46:23.583142  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:46:29.562573  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
E0410 18:46:52.545300  3457 socket.hpp:174] Shutdown failed on fd=6: Transport endpoint is not connected [107]
```

**Comment by tetron** [comment]
```
ubuntu@ip-172-31-27-173:/var/log/mesosbox/mesos$ cat mesos-master.INFO 
Log file created at: 2016/04/10 18:20:17
Running on machine: ip-172-31-27-173
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0410 18:20:17.596525  1414 logging.cpp:172] INFO level logging started!
I0410 18:20:17.596705  1414 main.cpp:229] Build: 2015-10-12 20:57:28 by root
I0410 18:20:17.596717  1414 main.cpp:231] Version: 0.25.0
I0410 18:20:17.596722  1414 main.cpp:234] Git tag: 0.25.0
I0410 18:20:17.596727  1414 main.cpp:238] Git SHA: 2dd7f7ee115fe00b8e098b0a10762a4fa8f4600f
I0410 18:20:17.596768  1414 main.cpp:252] Using 'HierarchicalDRF' allocator
I0410 18:20:17.600476  1414 main.cpp:465] Starting Mesos master
I0410 18:20:17.603474  1414 master.cpp:376] Master 51ee9789-bc63-42fb-8151-ee783e413ca4 (mesos-master) started on 172.31.27.173:5050
I0410 18:20:17.603518  1414 master.cpp:378] Flags at startup: --allocation_interval="1secs" --allocator="HierarchicalDRF" --authenticate="false" --authenticate_slaves="false" --authenticators="crammd5" --authorizers="local" --framework_sorter="drf" --help="false" --hostname_lookup="true" --initialize_driver_logging="true" --ip_discovery_command="hostname -i" --log_auto_initialize="true" --log_dir="/var/log/mesosbox/mesos" --logbufsecs="0" --logging_level="INFO" --max_slave_ping_timeouts="5" --port="5050" --quiet="false" --recovery_slave_removal_limit="100%" --registry="in_memory" --registry_fetch_timeout="1mins" --registry_store_timeout="5secs" --registry_strict="false" --root_submissions="true" --slave_ping_timeout="15secs" --slave_reregister_timeout="10mins" --user_sorter="drf" --version="false" --webui_dir="/usr/share/mesos/webui" --zk_session_timeout="10secs"
I0410 18:20:17.604773  1414 master.cpp:425] Master allowing unauthenticated frameworks to register
I0410 18:20:17.604799  1414 master.cpp:430] Master allowing unauthenticated slaves to register
I0410 18:20:17.604811  1414 master.cpp:467] Using default 'crammd5' authenticator
W0410 18:20:17.604853  1414 authenticator.cpp:505] No credentials provided, authentication requests will be refused
I0410 18:20:17.604940  1414 authenticator.cpp:512] Initializing server SASL
I0410 18:20:18.252369  1414 master.cpp:1542] Successfully attached file '/var/log/mesosbox/mesos/mesos-master.INFO'
I0410 18:20:18.252441  1414 master.cpp:1603] The newly elected leader is master@172.31.27.173:5050 with id 51ee9789-bc63-42fb-8151-ee783e413ca4
I0410 18:20:18.252456  1414 master.cpp:1616] Elected as the leading master!
I0410 18:20:18.252465  1414 master.cpp:1376] Recovering from registrar
I0410 18:20:18.253573  1628 registrar.cpp:309] Recovering registrar
I0410 18:20:18.254418  1628 registrar.cpp:342] Successfully fetched the registry (0B) in 756992ns
I0410 18:20:18.256570  1628 registrar.cpp:441] Applied 1 operations in 2.095725ms; attempting to update the 'registry'
I0410 18:20:18.257774  1627 registrar.cpp:486] Successfully updated the 'registry' in 1.159168ms
I0410 18:20:18.257817  1627 registrar.cpp:372] Successfully recovered registrar
I0410 18:20:18.257881  1627 master.cpp:1413] Recovered 0 slaves from the Registry (136B) ; allowing 10mins for slaves to re-register
I0410 18:22:51.012012  1623 master.cpp:3862] Registering slave at slave(1)@172.31.21.96:5051 (ip-172-31-21-96.us-west-2.compute.internal) with id 51ee9789-bc63-42fb-8151-ee783e413ca4-S0
I0410 18:22:51.012177  1623 registrar.cpp:441] Applied 1 operations in 14655ns; attempting to update the 'registry'
I0410 18:22:51.013073  1623 registrar.cpp:486] Successfully updated the 'registry' in 869120ns
I0410 18:22:51.013504  1627 hierarchical.hpp:675] Added slave 51ee9789-bc63-42fb-8151-ee783e413ca4-S0 (ip-172-31-21-96.us-west-2.compute.internal) with cpus(*):2; mem(*):2928; disk(*):4970; ports(*):[31000-32000] (allocated: )
I0410 18:22:51.013406  1623 master.cpp:3930] Registered slave 51ee9789-bc63-42fb-8151-ee783e413ca4-S0 at slave(1)@172.31.21.96:5051 (ip-172-31-21-96.us-west-2.compute.internal) with cpus(*):2; mem(*):2928; disk(*):4970; ports(*):[31000-32000]
I0410 18:22:51.015022  1628 master.cpp:4272] Received update of slave 51ee9789-bc63-42fb-8151-ee783e413ca4-S0 at slave(1)@172.31.21.96:5051 (ip-172-31-21-96.us-west-2.compute.internal) with total oversubscribed resources 
I0410 18:22:51.015141  1628 hierarchical.hpp:735] Slave 51ee9789-bc63-42fb-8151-ee783e413ca4-S0 (ip-172-31-21-96.us-west-2.compute.internal) updated with oversubscribed resources  (total: cpus(*):2; mem(*):2928; disk(*):4970; ports(*):[31000-32000], allocated: )
```

```
ubuntu@ip-172-31-27-173:/var/log/mesosbox/mesos$ cat mesos-master.WARNING
Log file created at: 2016/04/10 18:20:17
Running on machine: ip-172-31-27-173
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0410 18:20:17.604853  1414 authenticator.cpp:505] No credentials provided, authentication requests will be refused
```

**Comment by tetron** [comment]
By the way, I logged in as "ubuntu" in order to be able to use "sudo".  I tried logging in again as "mesosbox" and running the same command, but got the same result.

**Comment by arkal** [comment]
Can you look at the slave logs? They will be on the slave at $TMPDIR/mesos/slaves/<some slave specific stuff here>/latest/stderr

**Comment by tetron** [comment]
mesos-slave.INFO
```
Log file created at: 2016/04/10 18:22:49
Running on machine: ip-172-31-21-96
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0410 18:22:49.534394  1414 logging.cpp:172] INFO level logging started!
I0410 18:22:49.534644  1414 main.cpp:185] Build: 2015-10-12 20:57:28 by root
I0410 18:22:49.534660  1414 main.cpp:187] Version: 0.25.0
I0410 18:22:49.534669  1414 main.cpp:190] Git tag: 0.25.0
I0410 18:22:49.534677  1414 main.cpp:194] Git SHA: 2dd7f7ee115fe00b8e098b0a10762a4fa8f4600f
I0410 18:22:49.809021  1414 containerizer.cpp:143] Using isolation: posix/cpu,posix/mem,filesystem/posix
W0410 18:22:49.900398  1414 backend.cpp:50] Failed to create 'bind' backend: BindBackend requires root privileges
I0410 18:22:49.906273  1414 main.cpp:272] Starting Mesos slave
I0410 18:22:49.909054  1414 slave.cpp:190] Slave started on 1)@172.31.21.96:5051
I0410 18:22:49.909082  1414 slave.cpp:191] Flags at startup: --appc_store_dir="/tmp/mesos/store/appc" --attributes="'preemptable:False'" --authenticatee="crammd5" --cgroups_cpu_enable_pids_and_tids_count="false" --cgroups_enable_cfs="false" --cgroups_hierarchy="/sys/fs/cgroup" --cgroups_limit_swap="false" --cgroups_root="mesos" --container_disk_watch_interval="15secs" --containerizers="mesos" --default_role="*" --disk_watch_interval="1mins" --docker="docker" --docker_kill_orphans="true" --docker_remove_delay="6hrs" --docker_socket="/var/run/docker.sock" --docker_stop_timeout="0ns" --enforce_container_disk_quota="false" --executor_registration_timeout="1mins" --executor_shutdown_grace_period="5secs" --fetcher_cache_dir="/tmp/mesos/fetch" --fetcher_cache_size="2GB" --frameworks_home="" --gc_delay="1weeks" --gc_disk_headroom="0.1" --hadoop_home="" --help="false" --hostname_lookup="true" --image_provisioner_backend="copy" --initialize_driver_logging="true" --isolation="posix/cpu,posix/mem" --launcher_dir="/usr/libexec/mesos" --log_dir="/var/log/mesosbox/mesos" --logbufsecs="0" --logging_level="INFO" --master="mesos-master:5050" --oversubscribed_resources_interval="15secs" --perf_duration="10secs" --perf_interval="1mins" --port="5051" --qos_correction_interval_min="0ns" --quiet="false" --recover="reconnect" --recovery_timeout="15mins" --registration_backoff_factor="1secs" --resource_monitoring_interval="1secs" --revocable_cpu_low_priority="true" --sandbox_directory="/mnt/mesos/sandbox" --strict="true" --switch_user="false" --systemd_runtime_directory="/run/systemd/system" --version="false" --work_dir="/var/lib/mesos"
I0410 18:22:49.912375  1414 slave.cpp:354] Slave resources: cpus(*):2; mem(*):2928; disk(*):4970; ports(*):[31000-32000]
I0410 18:22:50.128165  1414 slave.cpp:390] Slave hostname: ip-172-31-21-96.us-west-2.compute.internal
I0410 18:22:50.128222  1414 slave.cpp:395] Slave checkpoint: true
I0410 18:22:50.134354  1676 state.cpp:54] Recovering state from '/var/lib/mesos/meta'
I0410 18:22:50.134481  1676 status_update_manager.cpp:202] Recovering status update manager
I0410 18:22:50.136715  1678 containerizer.cpp:386] Recovering containerizer
I0410 18:22:50.138263  1678 slave.cpp:4110] Finished recovery
I0410 18:22:50.138573  1678 status_update_manager.cpp:176] Pausing sending status updates
I0410 18:22:50.138636  1672 slave.cpp:705] New master detected at master@172.31.27.173:5050
I0410 18:22:50.138799  1672 slave.cpp:730] No credentials provided. Attempting to register without authentication
I0410 18:22:50.138857  1672 slave.cpp:741] Detecting new master
I0410 18:22:51.018905  1674 slave.cpp:880] Registered with master master@172.31.27.173:5050; given slave ID 51ee9789-bc63-42fb-8151-ee783e413ca4-S0
I0410 18:22:51.019217  1673 status_update_manager.cpp:183] Resuming sending status updates
I0410 18:22:51.019333  1674 slave.cpp:939] Forwarding total oversubscribed resources 
I0410 18:23:50.141898  1675 slave.cpp:3926] Current disk usage 17.16%. Max allowed age: 5.098653194948380days
```

mesos-slave.WARNING
```
Log file created at: 2016/04/10 18:22:49
Running on machine: ip-172-31-21-96
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0410 18:22:49.900398  1414 backend.cpp:50] Failed to create 'bind' backend: BindBackend requires root privileges
```

**Comment by tetron** [comment]
Also `mesos/slaves/latest` does not contain a "stderr" file.

**Comment by tetron** [comment]
From syslog:

```
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [INFO] MainThread root: Starting run 1.
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [ERROR] MainThread boto: 400 Bad Request
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [ERROR] MainThread boto: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>AWS.SimpleQueueService.NonExistentQueue</Code><Message>The specified queue does not exist for this wsdl version.</Message><Detail/></Error><RequestId>a6d92c16-bcbe-5c75-954d-6392218c9d92</RequestId></ErrorResponse>
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [ERROR] MainThread boto: 400 Bad Request
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [ERROR] MainThread boto: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length</Message><Detail/></Error><RequestId>3e4468a3-797e-5e26-826c-2727e44c3fc1</RequestId></ErrorResponse>
Apr 10 18:26:58 ip-172-31-21-96 cgcloudagent[1045]: [ERROR] MainThread root: Abandoning run due to exception#012Traceback (most recent call last):#012  File "/opt/cgcloudagent/local/lib/python2.7/site-packages/cgcloud/agent/cli.py", line 131, in run#012    Agent( ctx, options ).run( )#012  File "/opt/cgcloudagent/local/lib/python2.7/site-packages/cgcloud/agent/__init__.py", line 37, in __init__#012    self.queue = self.ctx.sqs.create_queue( queue_name )#012  File "/opt/cgcloudagent/local/lib/python2.7/site-packages/boto/sqs/connection.py", line 96, in create_queue#012    return self.get_object('CreateQueue', params, Queue)#012  File "/opt/cgcloudagent/local/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object#012    raise self.ResponseError(response.status, response.reason, body)#012SQSError: SQSError: 400 Bad Request#012<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length</Message><Detail/></Error><RequestId>3e4468a3-797e-5e26-826c-2727e44c3fc1</RequestId></ErrorResponse>
```

**Comment by arkal** [comment]
The slave.info and warning look ok..... the executor logs generally tell a lot and that's usually in mesos/slaves/ all the way down the directory structure. So not `mesos/slaves/latest` but something like `/tmp/mesos/slaves/54a32fe9-66da-416f-aed6-0c0f97742741-S0/frameworks/54a32fe9-66da-416f-aed6-0c0f97742741-0000/executors/toil-1642/runs/latest/stderr`

**Comment by tetron** [comment]
I don't have a "frameworks" directory.

```
ubuntu@ip-172-31-21-96:~$ find /mnt/
/mnt/
/mnt/ephemeral
/mnt/ephemeral/var
/mnt/ephemeral/var/lib
/mnt/ephemeral/var/lib/mesos
/mnt/ephemeral/var/lib/mesos/slave_args
/mnt/ephemeral/var/lib/mesos/provisioner
/mnt/ephemeral/var/lib/mesos/meta
/mnt/ephemeral/var/lib/mesos/meta/slaves
/mnt/ephemeral/var/lib/mesos/meta/slaves/latest
/mnt/ephemeral/var/lib/mesos/meta/slaves/51ee9789-bc63-42fb-8151-ee783e413ca4-S0
/mnt/ephemeral/var/lib/mesos/meta/slaves/51ee9789-bc63-42fb-8151-ee783e413ca4-S0/slave.info
/mnt/ephemeral/var/lib/mesos/meta/boot_id
/mnt/ephemeral/var/lib/toil
/mnt/ephemeral/var/log
/mnt/ephemeral/var/log/mesosbox
/mnt/ephemeral/var/log/mesosbox/mesos
/mnt/ephemeral/var/log/mesosbox/mesos/mesos-slave.INFO
/mnt/ephemeral/var/log/mesosbox/mesos/mesos-slave.WARNING
/mnt/ephemeral/var/log/mesosbox/mesos/mesos-slave.ip-172-31-21-96.mesosbox.log.INFO.20160410-182249.1414
/mnt/ephemeral/var/log/mesosbox/mesos/mesos-slave.ip-172-31-21-96.mesosbox.log.WARNING.20160410-182249.1414
ubuntu@ip-172-31-21-96:~$ 
```

**Comment by arkal** [comment]
So that sort-of suggests that the executor isn't even starting up. That boto error is concerning and I honestly can't help you with that :(

**Comment by hannes-ucsc** [comment]
The cgcloudagent error is either benign or at least unrelated to this. What is your IAM username?

Re the main issue: I don't see a `--mesosMaster` in your script command line. The default is `localhost` which is probably why you are seeing this error. You should be passing `--mesosMaster=mesos-master`.

Ideally, `--mesosMaster` should not have a default and be mandatory if `--batchSystem=mesos` is passed. This is what #685 is about.

**Comment by tetron** [comment]
Now I'm getting a different Mesos error:

```
ubuntu@ip-172-31-31-240:~/common-workflow-language/draft-3/examples$ cwltoil --jobStore=aws:us-west-2:peter-cwltoil-test --batchSystem=mesos --mesosMaster=mesos-master example-1st.cwl  example-echo-job.json 
Error from Mesos: Failed to create a master detector for '172.31.31.240': Failed to parse '172.31.31.240' 
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'cwltoil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 585, in main
    outobj = toil.run(wf1)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 424, in run
    userScript=userScript)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 562, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 101, in __init__
    self._startDriver()
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 258, in _startDriver
    assert self.driver.start() == mesos_pb2.DRIVER_RUNNING
AssertionError
```

Also, is `--jobStore=aws:us-west-2:peter-cwltoil-test` correct?  Is there any additional documentation about using Toil with cgcloud+AWS+Mesos?  I'm having a difficult time.

**Comment by arkal** [comment]
The format for the jobstore is correct.

**Comment by arkal** [comment]
I think `--mesosMaster mesos-master:5050` is the right syntax

**Comment by tetron** [comment]
Thanks, that seems to work.  Some new errors:

Here's the first error:
```
cwltoil  --logDebug --jobStore=aws:us-west-2:peter-cwltoil-test --batchSystem=mesos --mesosMaster=mesos-master:5050 example-1st.cwl  example-echo-job.json 
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'cwltoil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 572, in main
    with Toil(options) as toil:
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 390, in __enter__
    config=None if self.config.restart else self.config)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 501, in loadOrCreateJobStore
    return AWSJobStore.loadOrCreateJobStore(jobStoreArgs, config=config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 117, in loadOrCreateJobStore
    return cls(region, namePrefix, config=config, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 166, in __init__
    self._checkJobStoreCreation(create, exists, region + ":" + namePrefix)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/abstractJobStore.py", line 200, in _checkJobStoreCreation
    "else remove it to start from scratch" % jobStoreString)
toil.jobStores.abstractJobStore.JobStoreCreationException: The job store 'us-west-2:peter-cwltoil-test' already exists. Use --restart or 'toil restart' to resume this jobStore, else remove it to start from scratch
```

I have no idea how to delete a SimpleDB jobStore, is there a Toil command or do I need to use some AWS UI or SDK?

Then I tried a different name for the jobStore:
```
cwltoil  --logDebug --jobStore=aws:us-west-2:peter-cwltoil-test2 --batchSystem=mesos --mesosMaster=mesos-master:5050 example-1st.cwl  example-echo-job.json 
I0412 20:38:21.903199  3605 sched.cpp:164] Version: 0.25.0
I0412 20:38:21.905033  3616 sched.cpp:262] New master detected at master@172.31.31.240:5050
I0412 20:38:21.905167  3616 sched.cpp:272] No credentials provided. Attempting to register without authentication
I0412 20:38:21.906024  3616 sched.cpp:641] Framework registered with 8c2c928f-d0e3-4557-952c-baa6a6535525-0002
No handlers could be found for logger "toil.leader"
I0412 20:38:36.381872  3605 sched.cpp:1771] Asked to stop the driver
I0412 20:38:36.382000  3613 sched.cpp:1040] Stopping framework '8c2c928f-d0e3-4557-952c-baa6a6535525-0002'
Traceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'cwltoil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 585, in main
    outobj = toil.run(wf1)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 463, in run
    return mainLoop(self.config, self.batchSystem, self.jobStore, rootJob, jobCache=self.jobCache)
  File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 653, in mainLoop
    raise FailedJobsException( config.jobStore, len(toilState.totalFailedJobs) )
toil.leader.FailedJobsException: The job store 'aws:us-west-2:peter-cwltoil-test2' contains 1 failed jobs
```

How do I get the failed job log?

**Comment by arkal** [comment]
`toil clean aws:us-west-2:peter-cwltoil-test` will clean your jobstore. Don't just delete the bucket from the S3 console.

**Comment by arkal** [comment]
The log usually is printed to your screen. This is where looking at the executor logs (XYZ/stderr) comes in handy!

**Comment by hannes-ucsc** [comment]
Re: documentation: The documentation PR adds some more meat:  For example,

http://toil.readthedocs.org/en/issues-741-fix-documentation-for-paper-rebased/running.html#running-on-aws
http://toil.readthedocs.org/en/issues-741-fix-documentation-for-paper-rebased/cli.html?highlight=clean

> `No handlers could be found for logger "toil.leader"`

This worries me. Could this be a cwltoil-specific issue? Try running the HelloWorld.py script from the docs.

**Comment by tetron** [comment]
It works!

```
ubuntu@ip-172-31-24-34:~/common-workflow-language/draft-3/examples$ cwltoil  --logDebug --jobStore=aws:us-west-2:peter-cwltoil-test --batchSystem=mesos --mesosMaster=mesos-master:5050 example-stdout.cwl  example-echo-job.json 
I0413 15:18:20.573896  3159 sched.cpp:164] Version: 0.25.0
I0413 15:18:20.575754  3165 sched.cpp:262] New master detected at master@172.31.24.34:5050
I0413 15:18:20.575884  3165 sched.cpp:272] No credentials provided. Attempting to register without authentication
I0413 15:18:20.576802  3170 sched.cpp:641] Framework registered with 8088d9de-6e46-4a50-9e6e-4b76aede18ae-0001
I0413 15:18:38.859632  3159 sched.cpp:1771] Asked to stop the driver
I0413 15:18:38.859735  3168 sched.cpp:1040] Stopping framework '8088d9de-6e46-4a50-9e6e-4b76aede18ae-0001'
{
    "output": {
        "path": "/home/ubuntu/common-workflow-language/draft-3/examples/output.txt", 
        "checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b", 
        "class": "File", 
        "size": 13
    }
}ubuntu@ip-172-31-24-34:~/common-workflow-language/draft-3/examples$ cat output.txt 
Hello world!
```

**Comment by hannes-ucsc** [comment]
Cool! Did you change anything to address the `No handlers` message? I'm not seeing it in your latest transcript.
