### ISSUE TITLE
`toil clean` fails due to job store missing workflow ID

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil#789]
Toil clean produces the following error sometimes when a jobstore is cleaned from a different cluster than where it was created. [I think that's not correct. See below. (Hannes)]
```
$ toil clean aws:us-west-2:almussel-job-store-3
2016-04-13 20:07:46,140 INFO:toil.lib.bioio: Logging set at level: INFO
2016-04-13 20:07:46,141 INFO:toil.utils.toilClean: Parsed arguments
2016-04-13 20:07:46,141 INFO:toil.utils.toilClean: Checking if we have files for toil
Traceback (most recent call last):
  File "/usr/local/bin/toil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'toil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/utils/toilMain.py", line 30, in main
    module.main()
  File "/usr/local/lib/python2.7/dist-packages/toil/utils/toilClean.py", line 53, in main
    jobStore = Toil.loadOrCreateJobStore(options.jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 501, in loadOrCreateJobStore
    return AWSJobStore.loadOrCreateJobStore(jobStoreArgs, config=config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 117, in loadOrCreateJobStore
    return cls(region, namePrefix, config=config, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 182, in __init__
    super(AWSJobStore, self).__init__(config=config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/abstractJobStore.py", line 120, in __init__
    assert config.workflowID is not None
AttributeError: 'Config' object has no attribute 'workflowID'
```

**Comment by hannes-ucsc** [comment]
I don't think it matters where `toil clean` is run. This particular job store just wan't initialized all the way and that way cleaning it up is failing. How can we make `toil clean` more robust and able to handle incompletely setup job stores.

**Comment by cket** [comment]
Related to #785 and #754
