### ISSUE TITLE
cwltool conflict version?

### ISSUE THREAD

**Issue by guillermo-carrasco** [BD2KGenomics/toil#824]
Hi,

I'm trying to run a CWL workflow for bcbio-nextgen in our SLURM cluster using Toil. To do so, I'm running the following command: `cwltoil --verbose --preserve-environment PATH HOME --no-container run_info-cwl-workflow/main-run_info-cwl.cwl run_info-cwl-workflow/main-run_info-cwl-samples.json`.

The command is the same than the one specified in [bcbio-nextgen docs](http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#running), just that I use `cwltoil` instead of `cwltool`.

When doing so, I'm getting the following error:

```
 login01 /scratch/gcarrasco/tests/test_bcbio_cwl ~> cwltoil --verbose --preserve-environment PATH HOME --no-container run_info-cwl-workflow/main-run_info-cwl.cwl run_info-cwl-workflow/main-run_info-cwl-samples.json                        Traceback (most recent call last):
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2', 'console_scripts', 'cwltoil')()
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2201, in load
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 2218, in require
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 835, in resolve
pkg_resources.VersionConflict: (cwltool 1.0.20160422204730 (/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/cwltool-1.0.20160422204730-py2.7.egg), Requirement.parse('cwltool==1.0.20160413143011'))
```

Looking at the code I saw that the version of `cwltool` required is set in [`setup.py`](https://github.com/BD2KGenomics/toil/blob/master/setup.py). Isn't this a too strict requirement? I'd suggest changing it for 

```
        'cwl': [
            'cwltool>=1.0]},
```

Ping @tetron :)

**Comment by guillermo-carrasco** [comment]
okay, just realised that doing that, I get:

```
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 28, in <module>
    from cwltool.aslist import aslist
ImportError: No module named aslist
```

since `aslist` was moved to `cwltool.util` [15 days ago](https://github.com/common-workflow-language/cwltool/blob/b77c6ef44192458e4e93400d644f351f42ffb420/cwltool/utils.py), what would be the best approach here? I can see two obvious solutions:

* Change the requirement
* Implement a `try` `except` within the imports

Since the `cwltool` code is changing fast and constantly, I really don't know how to proceed. Any suggestions @mr-c ?

**Comment by mr-c** [comment]
I'd change the requirement to use the newer cwltool. We'll have a more stable API after the 1.0 release of the standards

**Comment by mr-c** [comment]
So yes, https://github.com/BD2KGenomics/toil/blob/master/setup.py#L43 should be changed to use a `>=` a known working version.

**Comment by guillermo-carrasco** [comment]
ok, thanks!

**Comment by hannes-ucsc** [comment]
Use of '>=' version constraints are discouraged. See #827 for discussion.
