### ISSUE TITLE
`Connection reset by peer` in stats collector

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#845]
http://jenkins.cgcloud.info/job/toil-pull-requests/1233/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsMesos/

referenced in https://github.com/BD2KGenomics/toil/pull/843#issuecomment-216737542

These random outages will happen. We need to figure out why boto's retry didn't catch this and how we handle failures in the stats collector. We may not want failures in the collector prevent the workflow from succeeding.

```
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/leader.py", line 89, in statsAndLoggingAggregatorProcess
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/jobStores/aws/jobStore.py", line 399, in readStatsAndLogging
    info.save()
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/jobStores/aws/jobStore.py", line 702, in save
    assert self.outer.filesDomain.put_attributes(item_name=self.fileID,
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/boto/sdb/domain.py", line 94, in put_attributes
    replace, expected_value)
  File "/mnt/ephemeral/workspace/toil-pull-requests/src/toil/jobStores/aws/sdbUtils.py", line 166, in _put_attributes_using_post
    return self.get_status('PutAttributes', params, verb='POST')
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1214, in get_status
    body = response.read()
  File "/mnt/ephemeral/workspace/toil-pull-requests/venv/local/lib/python2.7/site-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 630, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 104] Connection reset by peer
```

**Comment by cket** [comment]
https://github.com/boto/boto/issues/2207
Looks to be a known issue with a couple workaround that I'll look into implementing.

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/toil-pull-requests/1405/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsMesos/
