### ISSUE TITLE
Unable to import files

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#859]
File import does not give any feedback.  It seems to be adding a file to the S3 bucket but gets stuck.  I hit ^C after about 15 minutes of no progress and no network activity.  It appears to waiting for a response:

```
$ cwltoil --logDebug --batchSystem=mesos --mesosMaster=mesos-master:5050 --jobStore=aws:us-west-2:cwltoil-test-pa2 main-bwa_freebayes_HG01977.cwl main-bwa_freebayes_HG01977-samples.json 
2016-05-11 14:17:31,458 INFO:toil.lib.bioio: Logging set at level: DEBUG
2016-05-11 14:18:04,334 INFO:toil.lib.bioio: Logging set at level: DEBUG
2016-05-11 14:18:04,398 DEBUG:toil.jobStores.aws.jobStore: Instantiating <class 'toil.jobStores.aws.jobStore.AWSJobStore'> for region us-west-2 and name prefix 'cwltoil-test-pa2'
2016-05-11 14:18:08,300 INFO:toil.jobStores.abstractJobStore: The workflow ID is: '75205970-692b-4e0e-b3b7-3f457c55e77b'
2016-05-11 14:18:08,648 DEBUG:toil.jobStores.aws.jobStore: Wrote FileInfo(fileID='a77581f6-ad82-5142-acb7-5a6b01eab3fb', ownerID='891f7db6-e4d9-4221-a58e-ab6cc4395f94', encrypted=False, version='', previousVersion='', content='\x80\x02ctoil.co...ryCountq6K\x00ub.', _numContentChunks=2) bound to <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7f4fb88c3890> for shared file 'config.pickle'.
2016-05-11 14:18:08,734 INFO:toil.jobStores.abstractJobStore: Unable to import 'toil.jobStores.azureJobStore'

^CTraceback (most recent call last):
  File "/usr/local/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2', 'console_scripts', 'cwltoil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 580, in main
    adjustFiles(builder.job, functools.partial(writeFile, toil.importFile, {}))
  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 128, in adjustFiles
    adjustFiles(rec[d], op)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 131, in adjustFiles
    adjustFiles(d, op)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 131, in adjustFiles
    adjustFiles(d, op)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/process.py", line 126, in adjustFiles
    rec["path"] = op(rec["path"])
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 162, in writeFile
    index[x] = (writeFunc(rp), os.path.basename(x))
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 653, in importFile
    return self._jobStore.importFile(srcUrl)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/abstractJobStore.py", line 259, in importFile
    return self._importFile(findJobStoreForUrl(url), url)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 279, in _importFile
    info.copyFrom(srcKey)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 846, in copyFrom
    headers=self._s3EncryptionHeaders()).version_id
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 878, in _copyKey
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 85, in copyKeyMultipart
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 306, in copy_part_from_key
    query_args=query_args)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 872, in copy_key
    body = response.read()
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 630, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
KeyboardInterrupt
```

**Comment by hannes-ucsc** [comment]
Is the destination job store in the same AWS region as the source object's bucket?

How big is the file?

**Comment by hannes-ucsc** [comment]
And by "no network activity" you mean very little activity, or literally none? When importing from S3, the copying takes place server-side (on S3) so I would expect there to be little activity, but not no activity at all.

**Comment by hannes-ucsc** [comment]
@JakeNarkizian, at the very least we we should add a debug log statement for every part.

**Comment by hannes-ucsc** [comment]
@JakeNarkizian we should also consider multi-threading the copy such that we copy several parts at once. This would be reasonably easy to do with Python's [futures backport](https://pypi.python.org/pypi/futures).

**Comment by tetron** [comment]
Hi @hannes-ucsc, thanks for a quick response.  It is entirely possible data is being transferred correctly and it is just impossible to tell due to lack of logging.  I said "no data" because the network device stats were much too low for a file transfer going through the node, but that is understandable for a server to server copy.  Also, no files appeared in the S3 bucket via the web interface, but that could be due to eventual consistency or need to "commit" the file?

It is about 75 GiB of data.  I don't know what region the original buckets are in, I will have to check.

**Comment by tetron** [comment]
At minimum the logging (at info level, I think) should say which files are being imported and when each transfer begins & ends.

**Comment by hannes-ucsc** [comment]
> Also, no files appeared in the S3 bucket via the web interface, but that could be due to eventual consistency or need to "commit" the file?

Correct. First, the parts are uploaded with individual requests and then the parts are concatenated in a separate "commit" request that creates the object by concatenating the parts. Before that, the object will not exist.

@JakeNarkizian, here's what we should do:

1) Use INFO level log statement at the beginning and end of each importFile/exportFile invocation

2) Use DEBUG level log statements for each part

3) Copy parts in parallel using a thread pool. This will vastly improve the performance. That way, we should be able to copy a 75G file in under 10min as long as source and destination are in the same region. I'm thinking 10 or 16 concurrent CopyParts operations.

4) Ensure that uploads are being cancelled in case of exceptions during import or export.

5) When an AWS job store is cleaned and therefore the corresponding bucket is deleted, we should cancel all unfinished uploads.

**Comment by JakeNarkizian** [comment]
@hannes-ucsc, there is [code](https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/aws/jobStore.py#L1004-1005) in master that already takes care of deleting uploads during toil clean.

**Comment by hannes-ucsc** [comment]
@tetron, so while @JakeNarkizian is making great strides in improving the performance of the multipart copy, I would also like to mention that you probably don't want to stage files from S3 like that. Large files should be downloaded directly onto the worker from the primary location in S3 unless the file is needed several times during a workflow *and* is in a different region than the job store.

**Comment by tetron** [comment]
@hannes-ucsc I think I have been misunderstanding how file handling is intended to work in Toil.  I was under the impression the job file store was supposed to be the only abstraction for handling files.  However I gather from what you're saying that I shouldn't "import" these files, I should have the job steps download them directly (at least until something like https://github.com/BD2KGenomics/toil/issues/819 is implemented, in which case the two strategies would be equivalent?)

Can I call `fileStore.readGlobalFile()` with a `s3://` URL or do I need to handle that some other way?

**Comment by hannes-ucsc** [comment]
The job store is the main abstraction for handling files but as with most abstractions there is a generality vs efficiency trade-off. While you *can* import s3:// files on the leader, that is going to be inefficient if those files are large and are only used once in a workflow. because you are doing one redundant copy. But Jake's fix is going to alleviate that inefficiency to a large degree.

However, if there are N files per sample to import and you have many samples, the import really should happen on the workers, i.e. inside job functions, such that you benefit from parallelization. The FileStore interface which is exposed to job functions as `job.FileStore` (where `job` is the first argument to the function) has `importFile` and `exportFile` for that very purpose. The main motivation for adding `Toil.importFile` and `Toil.exportFile` was to enable importing of files local to the leader.

We should document the trade-offs better.

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/toil/issues/875
