### ISSUE TITLE
Regression in SortTest.testGoogleMesos

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#897]
~~http://jenkins.cgcloud.info/job/toil-branches/branch/master/lastCompletedBuild/testReport/src.toil.test.sort.sortTest/SortTest/testGoogleMesos/~~

```RuntimeError: Stats/logging collator failed with exit code 1.```

http://jenkins.cgcloud.info/job/toil-branches/branch/master/159/testReport/junit/src.toil.test.sort.sortTest/SortTest/testGoogleMesos/

With this exception being the primary cause:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/leader.py", line 89, in statsAndLoggingAggregatorProcess
    if jobStore.readStatsAndLogging(callback) == 0:
  File "/mnt/ephemeral/workspace/toil-branches/master/src/toil/jobStores/googleJobStore.py", line 282, in readStatsAndLogging
    for key in list(self.files.list(prefix=prefix)):
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 472, in get_all_keys
    '', headers, **params)
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 399, in _get_all
    body = response.read()
  File "/mnt/ephemeral/workspace/toil-branches/master/venv/local/lib/python2.7/site-packages/boto/connection.py", line 410, in read
    self._cached_response = http_client.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1751)```

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/lastCompletedBuild/testReport/src.toil.test.sort.sortTest/SortTest/testGoogleMesos/

**Comment by cket** [comment]
That link seems to go to the most recent build so is now out of data:
http://jenkins.cgcloud.info/job/toil-branches/branch/master/159/testReport/junit/src.toil.test.sort.sortTest/SortTest/testGoogleMesos/

**Comment by cket** [comment]
There are many similar issues reported but they all seem to be related to client libraries using the non-thread safe httplib2 module, which is not the case for Boto. 

https://forums.aws.amazon.com/message.jspa?messageID=460058
This is the only report of this error  I could find that affected Boto and it ended up being an issue with AWS so we might be seeing a similar problem on Google's end.

**Comment by cket** [comment]
Here's another unrelated(?) failure on google sort test:
http://jenkins.cgcloud.info/job/toil-pull-requests/1345/testReport/junit/src.toil.test.sort.sortTest/SortTest/testGoogleMesos/

**Comment by hannes-ucsc** [comment]
I think we are lumping different issues together. They all cause the logging collator to fail but for very different reasons, depending on the job store being used. I will open individual tickets.

**Comment by hannes-ucsc** [comment]
See #905, #907 and #909.
